services:
  nats:
    image: nats:latest
    container_name: nats
    restart: unless-stopped
    command: ["-js", "--store_dir=/data"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    networks:
      - mylib

  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - acme:/etc/traefik/acme
    networks:
      - mylib

volumes:
  acme:
  nats-data:

networks:
  mylib:
    external: true