-- Converted from MySQL to PostgreSQL
SET session_replication_role = 'replica';



-- ----------------------------
-- Table structure for admin_user_roles
-- ----------------------------
DROP TABLE IF EXISTS admin_user_roles;
CREATE TABLE "admin_user_roles" (
  "admin_user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  PRIMARY KEY ("admin_user_id", "role_id")
);

-- ----------------------------
-- Records of admin_user_roles
-- ----------------------------
INSERT INTO admin_user_roles VALUES (1, 1);
INSERT INTO admin_user_roles VALUES (2, 2);
INSERT INTO admin_user_roles VALUES (3, 2);

-- ----------------------------
-- Table structure for admin_users
-- ----------------------------
DROP TABLE IF EXISTS admin_users;
CREATE TABLE "admin_users" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar(50) NOT NULL,
  "password" varchar(100) NOT NULL,
  "admin_level" integer NOT NULL DEFAULT 1,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "admin_users_username" UNIQUE (username)
);

-- ----------------------------
-- Records of admin_users
-- ----------------------------
INSERT INTO admin_users VALUES (1, 'admin', '$2a$10$LaQOY69/vt9IyHo1kwiKPeetblSK3Ka9lm1oLg4NL7OoV3tI3ClNe', 2, '2026-03-05 22:50:02', '2026-03-14 21:37:40');
INSERT INTO admin_users VALUES (2, 'string', '$2a$10$LaQOY69/vt9IyHo1kwiKPeetblSK3Ka9lm1oLg4NL7OoV3tI3ClNe', 1, '2026-03-05 23:06:44', '2026-03-05 23:06:44');
INSERT INTO admin_users VALUES (3, 'string1', '$2a$10$LaQOY69/vt9IyHo1kwiKPeetblSK3Ka9lm1oLg4NL7OoV3tI3ClNe', 1, '2026-03-05 23:23:15', '2026-03-14 21:37:36');

-- ----------------------------
-- Table structure for ai_chat_messages
-- ----------------------------
DROP TABLE IF EXISTS ai_chat_messages;
CREATE TABLE "ai_chat_messages" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "conversation_id" bigint NOT NULL,
  "role" varchar(20) NOT NULL,
  "content" text NOT NULL,
  "token_count" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of ai_chat_messages
-- ----------------------------

-- ----------------------------
-- Table structure for ai_conversations
-- ----------------------------
DROP TABLE IF EXISTS ai_conversations;
CREATE TABLE "ai_conversations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "title" varchar(255) NOT NULL DEFAULT 'AI客服对话',
  "status" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of ai_conversations
-- ----------------------------

-- ----------------------------
-- Table structure for banner_images
-- ----------------------------
DROP TABLE IF EXISTS banner_images;
CREATE TABLE "banner_images" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(255) NULL DEFAULT NULL,
  "image_url" varchar(500) NULL DEFAULT NULL,
  "link_url" varchar(500) NULL DEFAULT NULL,
  "sort_order" integer NULL DEFAULT 0,
  "status" integer NULL DEFAULT 1,
  "type" integer NOT NULL,
  "category_id" integer NULL DEFAULT NULL,
  "start_time" timestamp NULL DEFAULT NULL,
  "end_time" timestamp NULL DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of banner_images
-- ----------------------------

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS categories;
CREATE TABLE "categories" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "categories_name" UNIQUE (name)
);

-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO categories VALUES (1, '人工智能', '2026-03-02 18:28:07', '2026-03-19 23:06:22');
INSERT INTO categories VALUES (2, '电子', '2026-03-02 18:28:07', '2026-03-19 22:24:53');
INSERT INTO categories VALUES (3, '数学', '2026-03-02 18:28:07', '2026-03-19 22:24:58');
INSERT INTO categories VALUES (4, '英语', '2026-03-02 18:28:07', '2026-03-19 22:25:10');
INSERT INTO categories VALUES (5, '运动', '2026-03-02 18:28:07', '2026-03-20 18:30:30');
INSERT INTO categories VALUES (6, '心理学', '2026-03-02 18:28:07', '2026-03-19 22:50:25');
INSERT INTO categories VALUES (7, '软件', '2026-03-02 18:28:07', '2026-03-19 22:50:31');
INSERT INTO categories VALUES (8, '硬件', '2026-03-02 18:28:07', '2026-03-19 22:50:35');
INSERT INTO categories VALUES (9, '物理', '2026-03-02 18:28:07', '2026-03-19 22:50:45');
INSERT INTO categories VALUES (10, '机械', '2026-03-02 18:28:07', '2026-03-19 23:07:22');
INSERT INTO categories VALUES (11, '科技', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO categories VALUES (12, '政治', '2026-03-02 18:28:07', '2026-03-20 18:30:22');
INSERT INTO categories VALUES (13, '历史', '2026-03-02 18:28:07', '2026-03-20 18:30:43');
INSERT INTO categories VALUES (14, '经济', '2026-03-02 18:28:07', '2026-03-20 18:30:14');
INSERT INTO categories VALUES (15, '文学', '2026-03-02 18:28:07', '2026-03-20 18:30:50');
INSERT INTO categories VALUES (16, '哲学', '2026-03-02 18:28:07', '2026-03-20 18:31:37');
INSERT INTO categories VALUES (17, '教育学', '2026-03-02 18:28:07', '2026-03-20 18:31:47');
INSERT INTO categories VALUES (18, '医学', '2026-03-02 18:28:07', '2026-03-20 18:32:00');
INSERT INTO categories VALUES (19, '管理学', '2026-03-02 18:28:07', '2026-03-20 18:32:07');
INSERT INTO categories VALUES (20, '艺术', '2026-03-02 18:28:07', '2026-03-20 18:32:16');
INSERT INTO categories VALUES (21, '地理', '2026-03-02 18:28:07', '2026-03-20 18:32:57');
INSERT INTO categories VALUES (22, '语言', '2026-03-02 18:28:07', '2026-03-20 18:33:01');
INSERT INTO categories VALUES (23, '测试', '2026-03-19 23:07:36', '2026-03-19 23:07:36');

-- ----------------------------
-- Table structure for comments
-- ----------------------------
DROP TABLE IF EXISTS comments;
CREATE TABLE "comments" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "manuscript_id" integer NULL DEFAULT NULL,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "like_count" integer NULL DEFAULT 0,
  "reply_count" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "status" integer NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of comments
-- ----------------------------
INSERT INTO comments VALUES (3, 10, 4, '你好', 2, 3, '2026-03-15 14:23:23', '2026-04-07 12:51:18', 0);
INSERT INTO comments VALUES (6, NULL, 4, '测试', 1, 3, '2026-03-16 21:56:24', '2026-03-20 18:23:08', 0);
INSERT INTO comments VALUES (7, 14, 4, '交流电压跟直流电压有什么区别呀？😁', 1, 2, '2026-04-06 22:50:22', '2026-05-09 19:42:10', 0);
INSERT INTO comments VALUES (8, 10, 4, '有人吗？', 0, 0, '2026-04-07 12:51:34', '2026-04-07 12:51:34', 0);
INSERT INTO comments VALUES (9, 13, 4, '数学好难呀', 1, 3, '2026-04-10 17:48:37', '2026-04-10 18:16:28', 0);
INSERT INTO comments VALUES (10, 11, 4, '大家都在用什么工具写代码呀？', 1, 0, '2026-04-10 18:05:37', '2026-05-06 23:52:33', 0);
INSERT INTO comments VALUES (11, 29, 4, '你好', 0, 0, '2026-04-12 22:32:57', '2026-04-12 22:32:57', 0);
INSERT INTO comments VALUES (12, 29, 4, '我会打乒乓球', 2, 0, '2026-04-12 22:39:51', '2026-05-09 17:41:09', 0);
INSERT INTO comments VALUES (13, 29, 4, '乒乓球怎么打？', 1, 1, '2026-04-12 23:31:55', '2026-05-09 17:41:07', 0);
INSERT INTO comments VALUES (14, 27, 4, 'hello', 0, 0, '2026-04-12 23:39:32', '2026-04-12 23:39:32', 0);
INSERT INTO comments VALUES (15, 27, 4, '你好', 1, 1, '2026-04-12 23:55:50', '2026-05-09 19:07:41', 0);
INSERT INTO comments VALUES (16, 12, 4, 'crawfish', 2, 0, '2026-04-29 15:55:17', '2026-05-09 15:48:54', 0);
INSERT INTO comments VALUES (17, 12, 5, '小龙虾 飞书机器人', 0, 0, '2026-05-09 22:51:11', '2026-05-09 22:51:11', 0);

-- ----------------------------
-- Table structure for conversations
-- ----------------------------
DROP TABLE IF EXISTS conversations;
CREATE TABLE "conversations" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "target_user_id" integer NOT NULL,
  "last_message_id" integer NULL DEFAULT NULL,
  "last_message_content" varchar(500) NULL DEFAULT NULL,
  "last_message_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "unread_count" integer NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "conversations_uk_user_target" UNIQUE (user_id, target_user_id)
);

-- ----------------------------
-- Records of conversations
-- ----------------------------
INSERT INTO conversations VALUES (7, 5, 4, 90, '在吗', '2026-05-09 19:41:24', 0, '2026-03-17 10:39:14', '2026-05-09 19:41:23');
INSERT INTO conversations VALUES (8, 4, 5, 90, '在吗', '2026-05-09 19:41:24', 0, '2026-03-17 10:39:14', '2026-05-16 20:35:54');
INSERT INTO conversations VALUES (9, 5, 6, 91, '在吗在吗', '2026-05-09 19:41:37', 0, '2026-03-17 12:25:40', '2026-05-09 19:41:37');
INSERT INTO conversations VALUES (10, 6, 5, 91, '在吗在吗', '2026-05-09 19:41:38', 1, '2026-03-17 12:25:40', '2026-05-09 19:41:37');
INSERT INTO conversations VALUES (11, 6, 4, 83, '你好，请问找我有什么事吗', '2026-04-10 21:00:06', 1, '2026-03-20 11:48:21', '2026-04-10 21:00:05');
INSERT INTO conversations VALUES (12, 4, 6, 83, '你好，请问找我有什么事吗', '2026-04-10 21:00:05', 0, '2026-03-20 11:48:21', '2026-04-10 21:00:05');

-- ----------------------------
-- Table structure for creator_settings
-- ----------------------------
DROP TABLE IF EXISTS creator_settings;
CREATE TABLE "creator_settings" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "default_category_id" integer NULL DEFAULT NULL,
  "auto_publish" smallint NULL DEFAULT 0,
  "comment_notify" smallint NULL DEFAULT 1,
  "like_notify" smallint NULL DEFAULT 1,
  "follow_notify" smallint NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "creator_settings_user_id" UNIQUE (user_id)
);

-- ----------------------------
-- Records of creator_settings
-- ----------------------------
INSERT INTO creator_settings VALUES (1, 5, NULL, 0, 1, 1, 1, '2026-03-17 14:10:56', '2026-03-17 14:10:56');
INSERT INTO creator_settings VALUES (2, 4, NULL, 0, 1, 1, 1, '2026-03-17 14:12:03', '2026-03-17 14:12:03');

-- ----------------------------
-- Table structure for dynamic_comments
-- ----------------------------
DROP TABLE IF EXISTS dynamic_comments;
CREATE TABLE "dynamic_comments" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "dynamic_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "parent_id" integer NULL DEFAULT NULL,
  "reply_user_id" integer NULL DEFAULT NULL,
  "like_count" integer NULL DEFAULT 0,
  "status" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of dynamic_comments
-- ----------------------------
INSERT INTO dynamic_comments VALUES (1, 3, 5, '你好', NULL, NULL, 0, 1, '2026-03-30 22:07:36', '2026-03-30 22:07:36');
INSERT INTO dynamic_comments VALUES (6, 1, 4, '你们好😄', NULL, NULL, 0, 0, '2026-04-08 12:11:31', '2026-04-08 12:11:31');
INSERT INTO dynamic_comments VALUES (7, 1, 4, '你们好', NULL, NULL, 0, 0, '2026-04-08 12:11:48', '2026-04-08 12:11:48');
INSERT INTO dynamic_comments VALUES (8, 1, 4, '你们好啊', NULL, NULL, 0, 0, '2026-04-22 14:04:26', '2026-04-22 14:04:26');
INSERT INTO dynamic_comments VALUES (9, 1, 4, '你们好啊', NULL, NULL, 1, 0, '2026-04-22 14:05:02', '2026-05-02 22:56:39');
INSERT INTO dynamic_comments VALUES (10, 3, 4, '这是什么图片？', NULL, NULL, 1, 0, '2026-04-30 10:32:57', '2026-04-30 13:46:45');
INSERT INTO dynamic_comments VALUES (11, 2, 4, '你好', NULL, NULL, 1, 0, '2026-04-30 13:47:01', '2026-04-30 13:47:03');
INSERT INTO dynamic_comments VALUES (12, 3, 4, '哈喽哈喽', 10, NULL, 0, 0, '2026-04-30 15:33:59', '2026-04-30 15:33:59');
INSERT INTO dynamic_comments VALUES (13, 3, 4, '你好', 10, NULL, 0, 0, '2026-04-30 15:54:04', '2026-04-30 15:54:04');
INSERT INTO dynamic_comments VALUES (14, 3, 4, '怎么说', 10, 4, 0, 0, '2026-04-30 15:54:14', '2026-04-30 15:54:14');
INSERT INTO dynamic_comments VALUES (15, 3, 4, '你好', 10, NULL, 0, 0, '2026-04-30 15:59:54', '2026-04-30 15:59:54');
INSERT INTO dynamic_comments VALUES (16, 1, 4, '6666', 9, NULL, 1, 0, '2026-05-02 22:57:02', '2026-05-02 22:57:04');
INSERT INTO dynamic_comments VALUES (17, 1, 4, '66666', 9, 4, 0, 0, '2026-05-09 14:32:52', '2026-05-09 14:32:52');

-- ----------------------------
-- Table structure for favorite_folders
-- ----------------------------
DROP TABLE IF EXISTS favorite_folders;
CREATE TABLE "favorite_folders" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" varchar(50) NOT NULL,
  "collect_count" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "favorite_folders_user_id" UNIQUE (user_id, name)
);

-- ----------------------------
-- Records of favorite_folders
-- ----------------------------
INSERT INTO favorite_folders VALUES (1, 5, '数学', 3, '2026-03-12 17:45:36', '2026-03-20 20:30:38');
INSERT INTO favorite_folders VALUES (2, 5, 'AI', 3, '2026-03-12 17:45:58', '2026-03-20 20:30:38');
INSERT INTO favorite_folders VALUES (3, 4, '默认收藏夹', 3, '2026-03-13 17:34:21', '2026-04-30 22:40:05');
INSERT INTO favorite_folders VALUES (4, 4, 'AI', 1, '2026-03-15 14:49:02', '2026-05-08 14:41:35');
INSERT INTO favorite_folders VALUES (5, 5, '默认收藏夹', 3, '2026-03-11 20:47:41', '2026-03-20 20:30:38');
INSERT INTO favorite_folders VALUES (6, 6, '默认收藏夹', 0, '2026-03-17 09:00:09', '2026-03-17 09:00:09');
INSERT INTO favorite_folders VALUES (7, 5, '计算机', 1, '2026-05-09 16:52:06', '2026-05-09 17:41:57');
INSERT INTO favorite_folders VALUES (8, 5, '篮球', 1, '2026-05-09 16:52:14', '2026-05-09 16:52:16');
INSERT INTO favorite_folders VALUES (14, 7, '默认收藏夹', 0, '2026-05-20 23:34:58', '2026-05-20 23:34:58');

-- ----------------------------
-- Table structure for favorite_manuscripts
-- ----------------------------
DROP TABLE IF EXISTS favorite_manuscripts;
CREATE TABLE "favorite_manuscripts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "folder_id" integer NOT NULL,
  "manuscript_id" integer NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "favorite_manuscripts_uk_folder_manuscript" UNIQUE (folder_id, manuscript_id)
);

-- ----------------------------
-- Records of favorite_manuscripts
-- ----------------------------
INSERT INTO favorite_manuscripts VALUES (19, 1, 10, '2026-03-20 12:00:48');
INSERT INTO favorite_manuscripts VALUES (20, 2, 10, '2026-03-20 12:00:48');
INSERT INTO favorite_manuscripts VALUES (21, 2, 12, '2026-03-20 12:00:57');
INSERT INTO favorite_manuscripts VALUES (22, 5, 12, '2026-03-20 12:00:57');
INSERT INTO favorite_manuscripts VALUES (23, 1, 13, '2026-03-20 12:01:05');
INSERT INTO favorite_manuscripts VALUES (24, 5, 14, '2026-03-20 14:03:20');
INSERT INTO favorite_manuscripts VALUES (25, 1, 11, '2026-03-20 20:30:38');
INSERT INTO favorite_manuscripts VALUES (26, 2, 11, '2026-03-20 20:30:38');
INSERT INTO favorite_manuscripts VALUES (27, 5, 11, '2026-03-20 20:30:38');
INSERT INTO favorite_manuscripts VALUES (29, 3, 14, '2026-03-28 14:26:41');
INSERT INTO favorite_manuscripts VALUES (31, 3, 11, '2026-04-11 12:21:57');
INSERT INTO favorite_manuscripts VALUES (32, 4, 11, '2026-04-11 12:21:57');
INSERT INTO favorite_manuscripts VALUES (33, 3, 29, '2026-04-30 22:40:05');
INSERT INTO favorite_manuscripts VALUES (34, 8, 27, '2026-05-09 16:52:16');
INSERT INTO favorite_manuscripts VALUES (35, 7, 14, '2026-05-09 17:41:57');

-- ----------------------------
-- Table structure for live_linkmic
-- ----------------------------
DROP TABLE IF EXISTS live_linkmic;
CREATE TABLE "live_linkmic" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "room_id" bigint NOT NULL,
  "streamer_id" bigint NOT NULL,
  "viewer_id" bigint NOT NULL,
  "viewer_name" varchar(50) NOT NULL,
  "status" smallint NULL DEFAULT 0,
  "audio_enabled" smallint NULL DEFAULT 0,
  "video_enabled" smallint NULL DEFAULT 0,
  "max_linkmics" integer NULL DEFAULT 3,
  "apply_time" timestamp NULL DEFAULT NULL,
  "connect_time" timestamp NULL DEFAULT NULL,
  "end_time" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of live_linkmic
-- ----------------------------

-- ----------------------------
-- Table structure for live_rooms
-- ----------------------------
DROP TABLE IF EXISTS live_rooms;
CREATE TABLE "live_rooms" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "room_name" varchar(100) NOT NULL DEFAULT '',
  "stream_key" varchar(64) NOT NULL,
  "status" varchar(10) NOT NULL DEFAULT 'offline',
  "cover_url" varchar(255) NULL DEFAULT NULL,
  "viewer_count" integer NOT NULL DEFAULT 0,
  "category" varchar(50) NULL DEFAULT NULL,
  "scheduled_at" timestamp NULL DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "live_rooms_uk_stream_key" UNIQUE (stream_key)
);

-- ----------------------------
-- Records of live_rooms
-- ----------------------------
INSERT INTO live_rooms VALUES (1, 4, '我的直播间', 'e4a53048e3fd45c6a91964b44df6262b', 'live', NULL, 0, NULL, NULL, '2026-05-19 11:31:55', '2026-05-19 12:22:28');
INSERT INTO live_rooms VALUES (2, 5, '我的直播间', '7d42fcf7f4d84cbf9f24b763b46a34a9', 'offline', NULL, 0, NULL, NULL, '2026-05-20 22:57:40', '2026-05-20 22:57:40');

-- ----------------------------
-- Table structure for manuscript_collection_relations
-- ----------------------------
DROP TABLE IF EXISTS manuscript_collection_relations;
CREATE TABLE "manuscript_collection_relations" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "manuscript_id" integer NOT NULL,
  "collection_id" integer NOT NULL,
  "collection_order" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "manuscript_collection_relations_uk_manuscript_collection" UNIQUE (manuscript_id, collection_id)
);

-- ----------------------------
-- Records of manuscript_collection_relations
-- ----------------------------
INSERT INTO manuscript_collection_relations VALUES (1, 12, 3, 0, '2026-03-16 23:20:36');
INSERT INTO manuscript_collection_relations VALUES (2, 13, 3, 0, '2026-03-16 23:23:05');
INSERT INTO manuscript_collection_relations VALUES (1637826563, 11, 1444888585, 0, '2026-04-07 21:03:00');
INSERT INTO manuscript_collection_relations VALUES (1637826564, 27, 3, 3, '2026-05-08 12:57:20');
INSERT INTO manuscript_collection_relations VALUES (1637826565, 10, 1444888586, 0, '2026-05-09 13:19:44');
INSERT INTO manuscript_collection_relations VALUES (1637826566, 11, 1444888586, 1, '2026-05-09 14:32:42');

-- ----------------------------
-- Table structure for manuscript_collections
-- ----------------------------
DROP TABLE IF EXISTS manuscript_collections;
CREATE TABLE "manuscript_collections" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(100) NOT NULL,
  "description" text NULL,
  "cover_url" varchar(500) NULL DEFAULT NULL,
  "user_id" integer NOT NULL,
  "manuscript_count" integer NULL DEFAULT 0,
  "view_count" integer NULL DEFAULT 0,
  "status" smallint NULL DEFAULT 1,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of manuscript_collections
-- ----------------------------
INSERT INTO manuscript_collections VALUES (3, 'AI合集', 'AI合集', '/uploads/manuscripts/27/cover.jpg', 5, 3, 0, 1, '2026-03-17 09:54:07', '2026-05-08 13:34:01');
INSERT INTO manuscript_collections VALUES (1444888585, '人工智能', '', NULL, 4, 1, NULL, 1, '2026-04-07 21:03:00', '2026-04-29 16:51:07');
INSERT INTO manuscript_collections VALUES (1444888586, '电子', '烧录工具', '/uploads/manuscripts/10/cover.jpg', 4, 2, NULL, 1, '2026-05-09 13:19:44', '2026-05-09 14:32:42');

-- ----------------------------
-- Table structure for manuscripts
-- ----------------------------
DROP TABLE IF EXISTS manuscripts;
CREATE TABLE "manuscripts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(100) NOT NULL,
  "description" text NULL,
  "cover_url" varchar(500) NULL DEFAULT NULL,
  "user_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "view_count" integer NULL DEFAULT 0,
  "like_count" integer NULL DEFAULT 0,
  "coin_count" integer NULL DEFAULT 0,
  "collect_count" integer NULL DEFAULT 0,
  "share_count" integer NULL DEFAULT 0,
  "comment_count" integer NULL DEFAULT 0,
  "danmaku_count" integer NULL DEFAULT 0,
  "status" integer NULL DEFAULT 0,
  "review_status" integer NULL DEFAULT 0,
  "review_reason" varchar(500) NULL DEFAULT NULL,
  "review_time" timestamp NULL DEFAULT NULL,
  "reviewer_id" integer NULL DEFAULT NULL,
  "upload_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "duration" varchar(20) NULL DEFAULT NULL,
  "duration_seconds" integer NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of manuscripts
-- ----------------------------
INSERT INTO manuscripts VALUES (10, '无限零成本token，我给OpenClaw换了个永动机芯！【小白安装教程】', '本视频为无限token版本的openclaw安装教程\r\n任意Windows电脑均可安装 无需付费 无需高配电脑\r\n如果觉得视频对你有帮助 请一键三连加关注 随时关注主播最新教程\r\n如有问题可评论区留言或私信 随缘解答 无套路。小龙虾', '/uploads/manuscripts/10/cover.jpg', 4, 1, 321, 3, 1, 3, 0, 2, 0, 3, 0, NULL, NULL, NULL, '2026-03-15 11:01:33', '2026-05-16 23:49:46', '6:24', 384);
INSERT INTO manuscripts VALUES (11, 'AI Agent正在重走操作系统的老路', '一个MCP工具号称能省98%的Context Token，社区瞬间炸锅。但深挖后我发现，这不是一个“省钱”的问题——AI Agent开发正在重演操作系统的进化史。Context就是新时代的内存，而我们还停留在手动管理阶段。一次工具调用吃掉50K token，3-4次就烧掉半个窗口。本期拆解“沙盒+索引+按需检索”架构，以及协议层的结构性缺陷。', '/uploads/manuscripts/11/cover.jpg', 4, 1, 122, 2, 1, 2, 1, 1, 0, 3, 0, NULL, NULL, NULL, '2026-03-16 22:51:00', '2026-05-16 20:33:57', '4:31', 271);
INSERT INTO manuscripts VALUES (12, '把 OpenClaw 翻译成“小龙虾”的，出来挨打！', '', '/uploads/manuscripts/12/cover.jpg', 5, 4, 42, 2, 0, 1, 1, 2, 0, 3, 0, NULL, NULL, NULL, '2026-03-16 23:20:36', '2026-05-10 09:27:49', '3:16', 196);
INSERT INTO manuscripts VALUES (13, '数学怎么提分', '数学怎么提分#家长收藏孩子受益 #家长必读 #学习方法 #学霸秘籍', '/uploads/manuscripts/13/cover.jpg', 5, 3, 29, 2, 0, 1, 0, 1, 0, 3, 0, NULL, NULL, NULL, '2026-03-16 23:23:05', '2026-05-09 16:49:14', '1:11', 71);
INSERT INTO manuscripts VALUES (14, '每天学习一个电子知识，今天学习如何测电压', '', '/uploads/manuscripts/14/cover.jpg', 5, 2, 195, 3, 0, 2, 0, 1, 0, 3, 0, NULL, NULL, NULL, '2026-03-16 23:28:29', '2026-05-10 00:02:32', '0:26', 26);
INSERT INTO manuscripts VALUES (27, '投篮力线错误？这样改！', '投篮力线错误？这样改！', '/uploads/manuscripts/27/cover.jpg', 5, 5, 33, 2, 0, 1, 0, 2, 0, 3, 1, NULL, NULL, NULL, '2026-04-03 18:02:58', '2026-05-10 07:55:40', '01:09', 69);
INSERT INTO manuscripts VALUES (29, '少儿乒乓球训练', '少儿乒乓球训练', '/uploads/manuscripts/29/cover.jpg', 5, 5, 78, 2, 1, 1, 2, 3, 0, 3, 0, NULL, NULL, NULL, '2026-04-03 19:12:28', '2026-05-09 20:13:44', '00:38', 38);
INSERT INTO manuscripts VALUES (31, 'github短视频生成工具', 'github短视频生成工具', '/uploads/manuscripts/31/cover.jpg', 4, 7, 3, 1, 0, 0, 0, 0, 0, 3, 1, NULL, NULL, NULL, '2026-05-09 23:37:44', '2026-05-16 20:33:07', '00:47', 47);
INSERT INTO manuscripts VALUES (32, 'Skills', '开源Skills', '/uploads/manuscripts/32/cover.jpg', 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, '2026-05-10 08:04:36', '2026-05-10 08:05:27', '00:27', 27);

-- ----------------------------
-- Table structure for meeting_participant
-- ----------------------------
DROP TABLE IF EXISTS meeting_participant;
CREATE TABLE "meeting_participant" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "room_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "user_name" varchar(50) NOT NULL,
  "user_avatar" varchar(255) NULL DEFAULT NULL,
  "role" smallint NULL DEFAULT 0,
  "audio_enabled" smallint NULL DEFAULT 0,
  "video_enabled" smallint NULL DEFAULT 0,
  "screen_share_enabled" smallint NULL DEFAULT 0,
  "join_time" timestamp NULL DEFAULT NULL,
  "leave_time" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of meeting_participant
-- ----------------------------

-- ----------------------------
-- Table structure for meeting_room
-- ----------------------------
DROP TABLE IF EXISTS meeting_room;
CREATE TABLE "meeting_room" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "room_name" varchar(100) NOT NULL,
  "room_code" varchar(10) NOT NULL,
  "creator_id" bigint NOT NULL,
  "creator_name" varchar(50) NOT NULL,
  "max_participants" integer NULL DEFAULT 5,
  "status" smallint NULL DEFAULT 0,
  "start_time" timestamp NULL DEFAULT NULL,
  "end_time" timestamp NULL DEFAULT NULL,
  "scheduled_start" timestamp NULL DEFAULT NULL,
  "scheduled_end" timestamp NULL DEFAULT NULL,
  "scheduled_reason" varchar(500) NULL DEFAULT NULL,
  "create_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "meeting_room_room_code" UNIQUE (room_code)
);

-- ----------------------------
-- Records of meeting_room
-- ----------------------------

-- ----------------------------
-- Table structure for message_settings
-- ----------------------------
DROP TABLE IF EXISTS message_settings;
CREATE TABLE "message_settings" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "private_message_notification" smallint NULL DEFAULT 1,
  "reply_notification" smallint NULL DEFAULT 1,
  "at_notification" smallint NULL DEFAULT 1,
  "like_notification" smallint NULL DEFAULT 1,
  "system_notification" smallint NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "message_settings_user_id" UNIQUE (user_id)
);

-- ----------------------------
-- Records of message_settings
-- ----------------------------
INSERT INTO message_settings VALUES (1, 5, 1, 1, 1, 1, 1, '2026-03-27 21:00:02', '2026-03-27 21:00:02');
INSERT INTO message_settings VALUES (2, 4, 1, 1, 1, 1, 1, '2026-04-10 09:45:42', '2026-05-09 13:10:00');

-- ----------------------------
-- Table structure for messages
-- ----------------------------
DROP TABLE IF EXISTS messages;
CREATE TABLE "messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "sender_id" integer NOT NULL,
  "receiver_id" integer NOT NULL,
  "content" text NOT NULL,
  "is_read" smallint NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "message_type" smallint NULL DEFAULT 1,
  "target_id" integer NULL DEFAULT NULL,
  "media_url" varchar(500) NULL DEFAULT NULL,
  "conversation_id" integer NULL DEFAULT NULL,
  "comment_id" integer NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of messages
-- ----------------------------
INSERT INTO messages VALUES (11, 5, 4, '你好', 1, '2026-03-17 10:39:14', '2026-03-17 12:18:29', 1, NULL, NULL, 7, NULL);
INSERT INTO messages VALUES (12, 5, 4, '你好', 1, '2026-03-17 10:42:41', '2026-03-17 12:18:29', 1, NULL, NULL, 7, NULL);
INSERT INTO messages VALUES (13, 5, 6, '你好兄弟', 1, '2026-03-17 12:25:40', '2026-03-17 12:26:04', 1, NULL, NULL, 9, NULL);
INSERT INTO messages VALUES (14, 6, 5, '你好朋友', 1, '2026-03-17 12:26:19', '2026-03-17 12:26:31', 1, NULL, NULL, 10, NULL);
INSERT INTO messages VALUES (15, 6, 4, '你好', 1, '2026-03-20 11:48:21', '2026-03-28 14:22:31', 1, NULL, NULL, 11, NULL);
INSERT INTO messages VALUES (42, 5, 4, '赞了你的视频《无限零成本token，我给OpenClaw换了个永动机芯！【小白安装教程】》', 1, '2026-03-20 11:53:38', '2026-03-28 14:22:29', 4, 25, NULL, NULL, NULL);
INSERT INTO messages VALUES (43, 5, 4, '赞了你的视频《AI Agent正在重走操作系统的老路》', 1, '2026-03-16 23:19:34', '2026-03-28 14:22:29', 4, 26, NULL, NULL, NULL);
INSERT INTO messages VALUES (73, 5, 4, '赞了你的视频《无限零成本token，我给OpenClaw换了个永动机芯！【小白安装教程】', 1, '2026-03-20 11:53:38', '2026-04-10 16:19:03', 4, 25, NULL, NULL, NULL);
INSERT INTO messages VALUES (74, 5, 4, '赞了你的视频《AI Agent正在重走操作系统的老路》', 1, '2026-03-16 23:19:34', '2026-04-10 16:19:03', 4, 26, NULL, NULL, NULL);
INSERT INTO messages VALUES (76, 5, 4, '赞了你的视频《周鸿祎建议大家别只把AI当搜索引擎用》', 1, '2026-04-01 10:00:00', '2026-04-10 16:19:03', 4, 27, NULL, NULL, NULL);
INSERT INTO messages VALUES (77, 6, 4, '回复了你的评论：你们好😄', 1, '2026-04-08 12:15:00', '2026-04-10 16:19:01', 2, 1, NULL, NULL, NULL);
INSERT INTO messages VALUES (78, 5, 4, '回复了你的评论：你好', 1, '2026-03-30 22:10:00', '2026-04-10 16:19:01', 2, 1, NULL, NULL, NULL);
INSERT INTO messages VALUES (79, 5, 4, '您的稿件《无限零成本token，我给OpenClaw换了个永动机芯！》已通过审核并成功上架啦！', 1, '2026-03-15 10:00:00', '2026-04-10 16:19:16', 5, NULL, NULL, NULL, NULL);
INSERT INTO messages VALUES (80, 6, 4, '您的稿件《AI Agent正在重走操作系统的老路》已通过审核并成功上架啦！', 1, '2026-03-16 20:00:00', '2026-04-10 16:19:16', 5, NULL, NULL, NULL, NULL);
INSERT INTO messages VALUES (81, 4, 5, '您的稿件《每天学习一个电子知识，今天学习如何测电压》已通过审核并成功上架啦！', 1, '2026-03-18 15:00:00', '2026-05-04 22:26:45', 5, NULL, NULL, NULL, NULL);
INSERT INTO messages VALUES (82, 6, 5, '您的稿件《投篮发力差的共性和修改思路》已通过审核并成功上架啦！', 1, '2026-04-05 09:00:00', '2026-05-04 22:26:45', 5, NULL, NULL, NULL, NULL);
INSERT INTO messages VALUES (83, 4, 6, '你好，请问找我有什么事吗', 0, '2026-04-10 21:00:05', '2026-04-10 21:00:05', 1, NULL, NULL, 12, NULL);
INSERT INTO messages VALUES (84, 4, 5, '你好，找我有什么事吗？', 1, '2026-04-12 14:47:27', '2026-05-04 22:26:47', 1, NULL, NULL, 8, NULL);
INSERT INTO messages VALUES (85, 5, 4, '赞了你的评论\"怎么说\"', 0, '2026-05-09 14:41:56', '2026-05-09 14:41:56', 6, NULL, NULL, NULL, 13);
INSERT INTO messages VALUES (86, 5, 4, '赞了你的评论\"crawfish\"', 0, '2026-05-09 15:48:54', '2026-05-09 15:48:54', 6, NULL, NULL, NULL, 16);
INSERT INTO messages VALUES (87, 5, 4, '赞了你的评论\"乒乓球怎么打？\"', 0, '2026-05-09 17:41:06', '2026-05-09 17:41:06', 6, NULL, NULL, NULL, 13);
INSERT INTO messages VALUES (88, 5, 4, '赞了你的评论\"我会打乒乓球\"', 0, '2026-05-09 17:41:09', '2026-05-09 17:41:09', 6, NULL, NULL, NULL, 12);
INSERT INTO messages VALUES (89, 5, 4, '赞了你的评论\"你好\"', 0, '2026-05-09 19:07:31', '2026-05-09 19:07:31', 6, NULL, NULL, NULL, 15);
INSERT INTO messages VALUES (90, 5, 4, '在吗', 1, '2026-05-09 19:41:23', '2026-05-16 20:35:47', 1, NULL, NULL, 7, NULL);
INSERT INTO messages VALUES (91, 5, 6, '在吗在吗', 0, '2026-05-09 19:41:37', '2026-05-09 19:41:37', 1, NULL, NULL, 9, NULL);
INSERT INTO messages VALUES (92, 5, 4, '赞了你的评论\"哈哈哈\"', 0, '2026-05-09 19:41:59', '2026-05-09 19:41:59', 6, NULL, NULL, NULL, 7);
INSERT INTO messages VALUES (93, 5, 4, '赞了你的评论\"交流电压跟直流电压有什么区别呀？😁\"', 0, '2026-05-09 19:41:59', '2026-05-09 19:41:59', 6, NULL, NULL, NULL, 7);
INSERT INTO messages VALUES (94, 5, 4, '回复了你：@测试用户：交流电 直流电🤨', 1, '2026-05-09 19:42:10', '2026-05-16 20:35:54', 2, 14, NULL, NULL, 7);
INSERT INTO messages VALUES (95, 5, 4, '赞了你的评论\"crawfish\"', 0, '2026-05-09 22:50:52', '2026-05-09 22:50:52', 6, NULL, NULL, NULL, 16);

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS permissions;
CREATE TABLE "permissions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NOT NULL,
  "code" varchar(50) NOT NULL,
  "url" varchar(255) NULL DEFAULT NULL,
  "method" varchar(20) NULL DEFAULT NULL,
  "parent_id" integer NULL DEFAULT NULL,
  "description" varchar(255) NULL DEFAULT NULL,
  "create_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "permissions_name" UNIQUE (name),
  CONSTRAINT "permissions_code" UNIQUE (code)
);

-- ----------------------------
-- Records of permissions
-- ----------------------------
INSERT INTO permissions VALUES (1, '用户管理', 'user:manage', '/users', 'GET', NULL, '用户管理权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (2, '视频管理', 'video:manage', '/videos', 'GET', NULL, '视频管理权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (3, '评论管理', 'comment:manage', '/comments', 'GET', NULL, '评论管理权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (4, '分类管理', 'category:manage', '/categories', 'GET', NULL, '分类管理权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (5, '标签管理', 'tag:manage', '/tags', 'GET', NULL, '标签管理权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (6, '内容审核', 'review:manage', '/review', 'GET', NULL, '内容审核权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (7, '统计分析', 'statistics:manage', '/statistics', 'GET', NULL, '统计分析权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (8, '角色管理', 'role:manage', '/roles', 'GET', NULL, '角色管理权限', '2026-03-06 20:47:32', '2026-03-06 20:47:32');
INSERT INTO permissions VALUES (9, '管理员管理', 'admin:manage', '/admin', 'GET', NULL, '管理员账号管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (10, '安全设置', 'security:manage', '/security-settings', 'GET', NULL, '安全设置和登录日志管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (11, '直播管理', 'live:manage', '/live', 'GET', NULL, '直播间管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (12, '会议管理', 'meeting:manage', '/meeting', 'GET', NULL, '会议室管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (13, '存储管理', 'storage:manage', '/storage', 'POST', NULL, '对象存储迁移管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (14, '轮播图管理', 'banner:manage', '/banner-images', 'GET', NULL, '轮播图和背景图管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (15, '搜索索引管理', 'search:manage', '/search/admin/index', 'GET', NULL, '搜索索引管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (16, 'AI管理', 'ai:manage', '/ai', 'GET', NULL, 'AI配置、技能和处理任务管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (17, '消息管理', 'message:manage', '/message', 'POST', NULL, '系统消息广播管理权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (18, '审计日志管理', 'audit:manage', '/audit-logs', 'GET', NULL, '后台操作审计日志查询权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');
INSERT INTO permissions VALUES (19, '任务中心管理', 'operation:manage', '/operation-tasks', 'GET', NULL, '统一任务中心查询权限', '2026-05-31 00:00:00', '2026-05-31 00:00:00');

-- ----------------------------
-- Table structure for audit_logs
-- ----------------------------
DROP TABLE IF EXISTS audit_logs;
CREATE TABLE "audit_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "operator_id" integer NULL DEFAULT NULL,
  "operator_name" varchar(64) NULL DEFAULT NULL,
  "operator_role" varchar(64) NULL DEFAULT NULL,
  "module" varchar(64) NOT NULL,
  "action" varchar(64) NOT NULL,
  "target_type" varchar(64) NULL DEFAULT NULL,
  "target_id" varchar(128) NULL DEFAULT NULL,
  "request_method" varchar(16) NULL DEFAULT NULL,
  "request_uri" varchar(255) NULL DEFAULT NULL,
  "client_ip" varchar(64) NULL DEFAULT NULL,
  "user_agent" varchar(512) NULL DEFAULT NULL,
  "result" smallint NOT NULL,
  "message" varchar(255) NULL DEFAULT NULL,
  "detail" text NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Table structure for operation_tasks
-- ----------------------------
DROP TABLE IF EXISTS operation_tasks;
CREATE TABLE "operation_tasks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "task_key" varchar(128) NOT NULL,
  "task_type" varchar(64) NOT NULL,
  "task_name" varchar(128) NOT NULL,
  "target_type" varchar(64) NULL DEFAULT NULL,
  "target_id" varchar(128) NULL DEFAULT NULL,
  "status" varchar(32) NOT NULL,
  "progress" integer NOT NULL DEFAULT 0,
  "stage" varchar(128) NULL DEFAULT NULL,
  "message" varchar(255) NULL DEFAULT NULL,
  "error_message" text NULL,
  "operator_id" integer NULL DEFAULT NULL,
  "operator_name" varchar(64) NULL DEFAULT NULL,
  "started_at" timestamp NULL DEFAULT NULL,
  "finished_at" timestamp NULL DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "operation_tasks_uk_operation_task_key" UNIQUE (task_key)
);

-- ----------------------------
-- Table structure for prohibited_word
-- ----------------------------
DROP TABLE IF EXISTS prohibited_word;
CREATE TABLE "prohibited_word" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "word" varchar(100) NOT NULL,
  "match_type" varchar(20) NULL DEFAULT 'CONTAINS',
  "category" varchar(50) NULL DEFAULT NULL,
  "is_enabled" smallint NULL DEFAULT 1,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "prohibited_word_uk_word" UNIQUE (word)
);

-- ----------------------------
-- Records of prohibited_word
-- ----------------------------

-- ----------------------------
-- Table structure for prohibited_words
-- ----------------------------
DROP TABLE IF EXISTS prohibited_words;
CREATE TABLE "prohibited_words" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "word" varchar(255) NOT NULL,
  "match_type" varchar(20) NULL DEFAULT 'CONTAINS',
  "category" varchar(50) NULL DEFAULT NULL,
  "is_enabled" integer NULL DEFAULT 1,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of prohibited_words
-- ----------------------------
INSERT INTO prohibited_words VALUES (1, '骗子', 'CONTAINS', 'FRAUD', 1, '2026-04-24 15:08:49', '2026-04-24 15:08:49');
INSERT INTO prohibited_words VALUES (2, '傻子', 'EXACT', 'OTHER', 1, '2026-04-24 15:08:49', '2026-04-24 15:08:49');
INSERT INTO prohibited_words VALUES (3, '广告', 'CONTAINS', 'AD', 1, '2026-04-24 15:08:49', '2026-04-24 15:08:49');
INSERT INTO prohibited_words VALUES (4, '政治敏感', 'CONTAINS', 'POLITICS', 1, '2026-04-24 15:08:49', '2026-04-24 15:08:49');
INSERT INTO prohibited_words VALUES (5, '测试违禁词', 'CONTAINS', 'TEST', 0, '2026-04-24 15:08:49', '2026-04-24 15:08:49');

-- ----------------------------
-- Table structure for replies
-- ----------------------------
DROP TABLE IF EXISTS replies;
CREATE TABLE "replies" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "comment_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "like_count" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "reply_to_user_id" integer NULL DEFAULT NULL,
  "status" varchar(20) NULL DEFAULT 'NORMAL',
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of replies
-- ----------------------------
INSERT INTO replies VALUES (1, 3, 4, '你好', 0, '2026-03-15 14:23:33', '2026-03-15 14:23:33', NULL, 'NORMAL');
INSERT INTO replies VALUES (2, 3, 4, '@string：你好', 0, '2026-03-15 14:23:40', '2026-03-15 14:23:40', 4, 'NORMAL');
INSERT INTO replies VALUES (3, 6, 4, '测试', 0, '2026-03-16 21:56:39', '2026-03-16 21:56:39', NULL, 'NORMAL');
INSERT INTO replies VALUES (4, 6, 4, '@string：@string 测试', 0, '2026-03-16 22:13:13', '2026-03-16 22:13:13', 4, 'NORMAL');
INSERT INTO replies VALUES (5, 6, 4, '@string：测试', 0, '2026-03-16 22:19:09', '2026-03-16 22:19:09', 4, 'NORMAL');
INSERT INTO replies VALUES (6, 3, 5, '你好', 0, '2026-03-22 20:30:08', '2026-03-22 20:30:08', NULL, 'NORMAL');
INSERT INTO replies VALUES (7, 7, 4, '哈哈哈', 1, '2026-04-10 17:53:39', '2026-05-09 19:41:59', NULL, 'NORMAL');
INSERT INTO replies VALUES (8, 9, 4, '数学如何快速提分？', 1, '2026-04-10 18:06:33', '2026-04-10 18:25:29', NULL, 'NORMAL');
INSERT INTO replies VALUES (9, 9, 4, '数学如何快速提分？', 0, '2026-04-10 18:06:52', '2026-04-10 18:06:52', NULL, 'NORMAL');
INSERT INTO replies VALUES (10, 9, 4, '大家是怎么学数学的?', 0, '2026-04-10 18:16:28', '2026-04-10 18:16:28', NULL, 'NORMAL');
INSERT INTO replies VALUES (11, 13, 4, '怎么说', 1, '2026-05-02 14:18:26', '2026-05-09 14:41:56', NULL, 'NORMAL');
INSERT INTO replies VALUES (12, 15, 5, '😗😗😗', 1, '2026-05-09 19:07:41', '2026-05-09 19:07:46', NULL, 'NORMAL');
INSERT INTO replies VALUES (13, 7, 5, '@测试用户：交流电 直流电🤨', 0, '2026-05-09 19:42:10', '2026-05-09 19:42:10', 4, 'NORMAL');

-- ----------------------------
-- Table structure for reports
-- ----------------------------
DROP TABLE IF EXISTS reports;
CREATE TABLE "reports" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "reporter_id" integer NOT NULL,
  "target_type" varchar(30) NOT NULL,
  "target_id" integer NOT NULL,
  "manuscript_id" integer NULL DEFAULT NULL,
  "reason" varchar(50) NOT NULL,
  "description" varchar(500) NULL DEFAULT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'PENDING',
  "admin_remark" varchar(500) NULL DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "processed_at" timestamp NULL DEFAULT NULL,
  "ai_review_status" varchar(20) NULL DEFAULT 'PENDING',
  "ai_verdict" varchar(500) NULL DEFAULT NULL,
  "ai_risk_level" varchar(10) NULL DEFAULT NULL,
  "ai_reviewed_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of reports
-- ----------------------------
INSERT INTO reports VALUES (1, 5, 'MANUSCRIPT', 27, 27, '欺诈诈骗', '引战', 'PENDING', NULL, '2026-05-09 19:31:22', NULL, 'PENDING', NULL, NULL, NULL);

-- ----------------------------
-- Table structure for role_permissions
-- ----------------------------
DROP TABLE IF EXISTS role_permissions;
CREATE TABLE "role_permissions" (
  "role_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("role_id", "permission_id")
);

-- ----------------------------
-- Records of role_permissions
-- ----------------------------
INSERT INTO role_permissions VALUES (1, 1);
INSERT INTO role_permissions VALUES (2, 1);
INSERT INTO role_permissions VALUES (1, 2);
INSERT INTO role_permissions VALUES (2, 2);
INSERT INTO role_permissions VALUES (1, 3);
INSERT INTO role_permissions VALUES (2, 3);
INSERT INTO role_permissions VALUES (1, 4);
INSERT INTO role_permissions VALUES (1, 5);
INSERT INTO role_permissions VALUES (1, 6);
INSERT INTO role_permissions VALUES (2, 6);
INSERT INTO role_permissions VALUES (1, 7);
INSERT INTO role_permissions VALUES (2, 7);
INSERT INTO role_permissions VALUES (1, 8);
INSERT INTO role_permissions VALUES (1, 9);
INSERT INTO role_permissions VALUES (1, 10);
INSERT INTO role_permissions VALUES (1, 11);
INSERT INTO role_permissions VALUES (2, 11);
INSERT INTO role_permissions VALUES (1, 12);
INSERT INTO role_permissions VALUES (2, 12);
INSERT INTO role_permissions VALUES (1, 13);
INSERT INTO role_permissions VALUES (1, 14);
INSERT INTO role_permissions VALUES (1, 15);
INSERT INTO role_permissions VALUES (1, 16);
INSERT INTO role_permissions VALUES (2, 16);
INSERT INTO role_permissions VALUES (1, 17);
INSERT INTO role_permissions VALUES (1, 18);
INSERT INTO role_permissions VALUES (2, 18);
INSERT INTO role_permissions VALUES (1, 19);
INSERT INTO role_permissions VALUES (2, 19);


-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS roles;
CREATE TABLE "roles" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NOT NULL,
  "description" varchar(255) NULL DEFAULT NULL,
  "create_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "roles_name" UNIQUE (name)
);

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO roles VALUES (1, '超级管理员', '拥有所有权限', '2026-03-06 20:46:56', '2026-03-06 20:46:56');
INSERT INTO roles VALUES (2, '普通管理员', '拥有基本管理权限', '2026-03-06 20:46:56', '2026-03-06 20:46:56');

-- ----------------------------
-- Table structure for shares
-- ----------------------------
DROP TABLE IF EXISTS shares;
CREATE TABLE "shares" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NULL DEFAULT NULL,
  "manuscript_id" integer NOT NULL,
  "channel" varchar(50) NULL DEFAULT 'unknown',
  "ip_address" varchar(50) NULL DEFAULT NULL,
  "create_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of shares
-- ----------------------------
INSERT INTO shares VALUES (1, 4, 29, 'unknown', NULL, '2026-05-01 13:29:26');
INSERT INTO shares VALUES (2, 4, 29, 'unknown', NULL, '2026-05-02 14:17:56');
INSERT INTO shares VALUES (3, 4, 29, 'unknown', NULL, '2026-05-02 14:18:01');
INSERT INTO shares VALUES (4, 4, 29, 'unknown', NULL, '2026-05-02 14:20:44');
INSERT INTO shares VALUES (5, 4, 29, 'unknown', NULL, '2026-05-02 14:20:51');
INSERT INTO shares VALUES (6, 4, 11, 'unknown', NULL, '2026-05-08 15:05:53');
INSERT INTO shares VALUES (7, 5, 29, 'unknown', NULL, '2026-05-09 14:45:17');
INSERT INTO shares VALUES (8, 5, 29, 'unknown', NULL, '2026-05-09 14:45:30');
INSERT INTO shares VALUES (9, 5, 12, 'unknown', NULL, '2026-05-09 15:48:49');

-- ----------------------------
-- Table structure for tags
-- ----------------------------
DROP TABLE IF EXISTS tags;
CREATE TABLE "tags" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "tags_name" UNIQUE (name)
);

-- ----------------------------
-- Records of tags
-- ----------------------------
INSERT INTO tags VALUES (-2111918079, 'AI', '2026-05-09 23:38:34', '2026-05-09 23:38:34');
INSERT INTO tags VALUES (-2044809214, 'github', '2026-05-09 23:38:34', '2026-05-09 23:38:34');
INSERT INTO tags VALUES (-1650552831, '训练', '2026-04-03 19:12:28', '2026-04-03 19:12:28');
INSERT INTO tags VALUES (-1587638271, '乒乓球', '2026-04-03 19:12:28', '2026-04-03 19:12:28');
INSERT INTO tags VALUES (-161566718, '线性代数', '2026-05-09 22:54:22', '2026-05-09 22:54:22');
INSERT INTO tags VALUES (-161566717, '线代', '2026-05-09 22:54:22', '2026-05-09 22:54:22');
INSERT INTO tags VALUES (-98652158, '高数', '2026-05-09 22:54:22', '2026-05-09 22:54:22');
INSERT INTO tags VALUES (-98652157, '数学', '2026-05-09 22:54:22', '2026-05-09 22:54:22');
INSERT INTO tags VALUES (1, '原神', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (2, '我的世界', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (3, '英雄联盟', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (4, '鬼畜视频', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (5, '美食制作', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (6, '动漫推荐', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (7, '游戏攻略', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (8, '音乐MV', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (9, '舞蹈教学', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (10, '科技测评', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (11, '生活日常', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (12, '旅行', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (13, '健身', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (14, '学习', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (15, '职场', '2026-03-02 18:28:07', '2026-03-02 18:28:07');
INSERT INTO tags VALUES (16, 'string', '2026-03-04 00:02:23', '2026-03-04 00:02:23');
INSERT INTO tags VALUES (17, '11', '2026-03-09 14:43:26', '2026-03-09 14:43:26');
INSERT INTO tags VALUES (18, '123', '2026-03-09 15:52:29', '2026-03-09 15:52:29');
INSERT INTO tags VALUES (19, 'uioi', '2026-03-09 15:53:37', '2026-03-09 15:53:37');
INSERT INTO tags VALUES (20, '111', '2026-03-09 17:30:02', '2026-03-09 17:30:02');
INSERT INTO tags VALUES (21, '9999', '2026-03-09 17:31:01', '2026-03-09 17:31:01');
INSERT INTO tags VALUES (22, '999', '2026-03-09 17:31:01', '2026-03-09 17:31:01');
INSERT INTO tags VALUES (23, '5555', '2026-03-11 12:46:05', '2026-03-11 12:46:05');
INSERT INTO tags VALUES (24, '555', '2026-03-11 15:35:16', '2026-03-11 15:35:16');
INSERT INTO tags VALUES (25, '1', '2026-03-14 22:36:01', '2026-03-14 22:36:01');
INSERT INTO tags VALUES (26, '篮球', '2026-03-20 20:12:18', '2026-03-20 20:12:18');
INSERT INTO tags VALUES (27, '投篮', '2026-03-20 20:12:18', '2026-03-20 20:12:18');
INSERT INTO tags VALUES (28, '运动', '2026-03-20 20:12:18', '2026-03-20 20:12:18');
INSERT INTO tags VALUES (29, '体育', '2026-03-20 20:12:18', '2026-03-20 20:12:18');
INSERT INTO tags VALUES (400424961, '人工智能', '2026-05-10 08:05:27', '2026-05-10 08:05:27');
INSERT INTO tags VALUES (438173698, '开源', '2026-05-10 08:05:27', '2026-05-10 08:05:27');
INSERT INTO tags VALUES (2120134657, '软件', '2026-05-09 23:38:34', '2026-05-09 23:38:34');

-- ----------------------------
-- Table structure for user_dynamics
-- ----------------------------
DROP TABLE IF EXISTS user_dynamics;
CREATE TABLE "user_dynamics" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "dynamic_type" smallint NULL DEFAULT 0,
  "image_url" varchar(2000) NULL DEFAULT NULL,
  "ref_manuscript_id" integer NULL DEFAULT NULL,
  "like_count" integer NULL DEFAULT 0,
  "comment_count" integer NULL DEFAULT 0,
  "share_count" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "status" integer NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of user_dynamics
-- ----------------------------
INSERT INTO user_dynamics VALUES (-576823294, 4, 'hermes agent', 1, NULL, NULL, 1, 0, 0, '2026-05-09 23:32:37', 0);
INSERT INTO user_dynamics VALUES (1, 4, '6666', 0, NULL, NULL, 2, 4, 0, '2026-03-07 12:15:24', 0);
INSERT INTO user_dynamics VALUES (2, 6, '大家好', 0, NULL, NULL, 1, 1, 0, '2026-03-20 11:52:09', 0);
INSERT INTO user_dynamics VALUES (3, 5, '😀😀😀AI agent', 2, '/uploads/images/20260320152632_cc7c57ed-539c-4e58-a15c-211b194cacc8.jpg', 12, 2, 1, 3, '2026-03-20 15:26:33', 0);
INSERT INTO user_dynamics VALUES (1520365569, 5, '海思芯片', 1, '/covers/29ab6969-d9d0-41c1-9690-8eb7905c15a6.png', NULL, 1, 0, 0, '2026-05-05 22:24:51', 0);

-- ----------------------------
-- Table structure for user_interactions
-- ----------------------------
DROP TABLE IF EXISTS user_interactions;
CREATE TABLE "user_interactions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "target_type" varchar(20) NOT NULL,
  "target_id" integer NOT NULL,
  "interaction_type" varchar(20) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_interactions_uk_user_interaction" UNIQUE (user_id, target_type, target_id, interaction_type)
);

-- ----------------------------
-- Records of user_interactions
-- ----------------------------
INSERT INTO user_interactions VALUES (15, 4, 'MANUSCRIPT', 10, 'LIKE', '2026-03-16 17:15:11');
INSERT INTO user_interactions VALUES (29, 4, 'DYNAMIC', 1, 'LIKE', '2026-03-16 21:27:11');
INSERT INTO user_interactions VALUES (31, 5, 'MANUSCRIPT', 11, 'LIKE', '2026-03-16 23:19:34');
INSERT INTO user_interactions VALUES (32, 5, 'MANUSCRIPT', 12, 'LIKE', '2026-03-17 11:57:40');
INSERT INTO user_interactions VALUES (35, 4, 'COMMENT', 6, 'LIKE', '2026-03-19 20:32:07');
INSERT INTO user_interactions VALUES (36, 5, 'MANUSCRIPT', 14, 'LIKE', '2026-03-19 21:48:30');
INSERT INTO user_interactions VALUES (37, 4, 'MANUSCRIPT', 14, 'LIKE', '2026-03-20 11:15:41');
INSERT INTO user_interactions VALUES (39, 6, 'USER', 5, 'FOLLOW', '2026-03-20 11:47:54');
INSERT INTO user_interactions VALUES (40, 6, 'USER', 4, 'FOLLOW', '2026-03-20 11:47:59');
INSERT INTO user_interactions VALUES (42, 5, 'MANUSCRIPT', 10, 'COLLECT', '2026-03-20 12:00:48');
INSERT INTO user_interactions VALUES (43, 5, 'MANUSCRIPT', 12, 'COLLECT', '2026-03-20 12:00:57');
INSERT INTO user_interactions VALUES (44, 5, 'MANUSCRIPT', 13, 'COLLECT', '2026-03-20 12:01:05');
INSERT INTO user_interactions VALUES (45, 5, 'MANUSCRIPT', 13, 'LIKE', '2026-03-20 12:01:06');
INSERT INTO user_interactions VALUES (46, 5, 'MANUSCRIPT', 14, 'COLLECT', '2026-03-20 14:03:20');
INSERT INTO user_interactions VALUES (48, 5, 'MANUSCRIPT', 11, 'COLLECT', '2026-03-20 20:30:38');
INSERT INTO user_interactions VALUES (2037433097214943234, 1, 'MANUSCRIPT', 10, 'LIKE', '2026-03-27 15:34:38');
INSERT INTO user_interactions VALUES (2037435642637352962, 1, 'MANUSCRIPT', 10, 'COLLECT', '2026-03-27 15:44:45');
INSERT INTO user_interactions VALUES (2037533243521048577, 5, 'MANUSCRIPT', 10, 'LIKE', '2026-03-27 22:12:35');
INSERT INTO user_interactions VALUES (2037777389754122242, 4, 'MANUSCRIPT', 13, 'LIKE', '2026-03-28 14:22:44');
INSERT INTO user_interactions VALUES (2037778383862890497, 4, 'MANUSCRIPT', 14, 'COLLECT', '2026-03-28 14:26:41');
INSERT INTO user_interactions VALUES (2038926608628125698, 5, 'COMMENT', 3, 'LIKE', '2026-03-31 18:29:19');
INSERT INTO user_interactions VALUES (2041375449751134209, 4, 'DYNAMIC_COMMENT', 2, 'LIKE', '2026-04-07 12:40:08');
INSERT INTO user_interactions VALUES (2041378259502800898, 4, 'COMMENT', 3, 'LIKE', '2026-04-07 12:51:18');
INSERT INTO user_interactions VALUES (2041505816273395714, 4, 'DYNAMIC_COMMENT', 1, 'LIKE', '2026-04-07 21:18:10');
INSERT INTO user_interactions VALUES (2042129247121657857, 4, 'MANUSCRIPT', 12, 'LIKE', '2026-04-09 14:35:28');
INSERT INTO user_interactions VALUES (2042544719495352322, 4, 'COMMENT', 9, 'LIKE', '2026-04-10 18:06:24');
INSERT INTO user_interactions VALUES (2042549522392862721, 4, 'REPLY', 8, 'LIKE', '2026-04-10 18:25:29');
INSERT INTO user_interactions VALUES (2042550318928941058, 4, 'MANUSCRIPT', 10, 'COIN', '2026-04-10 18:28:39');
INSERT INTO user_interactions VALUES (2042820136252936194, 4, 'MANUSCRIPT', 11, 'COIN', '2026-04-11 12:20:48');
INSERT INTO user_interactions VALUES (2042820424225460226, 4, 'MANUSCRIPT', 11, 'COLLECT', '2026-04-11 12:21:57');
INSERT INTO user_interactions VALUES (2049405363599355905, 4, 'COMMENT', 16, 'LIKE', '2026-04-29 16:28:09');
INSERT INTO user_interactions VALUES (2049423707421470722, 5, 'MANUSCRIPT', 29, 'LIKE', '2026-04-29 17:41:02');
INSERT INTO user_interactions VALUES (2049503931651805185, 4, 'MANUSCRIPT', 27, 'LIKE', '2026-04-29 22:59:49');
INSERT INTO user_interactions VALUES (2049727135955755010, 4, 'DYNAMIC_COMMENT', 10, 'LIKE', '2026-04-30 13:46:45');
INSERT INTO user_interactions VALUES (2049727211285454849, 4, 'DYNAMIC_COMMENT', 11, 'LIKE', '2026-04-30 13:47:03');
INSERT INTO user_interactions VALUES (2049861294334361602, 4, 'MANUSCRIPT', 29, 'COIN', '2026-04-30 22:39:51');
INSERT INTO user_interactions VALUES (2049861351209123842, 4, 'MANUSCRIPT', 29, 'COLLECT', '2026-04-30 22:40:05');
INSERT INTO user_interactions VALUES (2049861654306308098, 4, 'COMMENT', 12, 'LIKE', '2026-04-30 22:41:17');
INSERT INTO user_interactions VALUES (2049865328583720962, 4, 'COMMENT', 13, 'LIKE', '2026-04-30 22:55:53');
INSERT INTO user_interactions VALUES (2050085165146738689, 4, 'MANUSCRIPT', 29, 'SHARE', '2026-05-01 13:29:26');
INSERT INTO user_interactions VALUES (2050460485855141890, 4, 'MANUSCRIPT', 29, 'LIKE', '2026-05-02 14:20:50');
INSERT INTO user_interactions VALUES (2050590296812511233, 4, 'DYNAMIC_COMMENT', 9, 'LIKE', '2026-05-02 22:56:39');
INSERT INTO user_interactions VALUES (2050590400021749761, 4, 'DYNAMIC_COMMENT', 16, 'LIKE', '2026-05-02 22:57:04');
INSERT INTO user_interactions VALUES (2051300263848775681, 4, 'MANUSCRIPT', 11, 'LIKE', '2026-05-04 21:57:48');
INSERT INTO user_interactions VALUES (2052037123977973762, 5, 'user', 4, 'follow', '2026-05-06 22:45:50');
INSERT INTO user_interactions VALUES (2052053913630101506, 5, 'COMMENT', 10, 'LIKE', '2026-05-06 23:52:33');
INSERT INTO user_interactions VALUES (2052646150667677698, 4, 'MANUSCRIPT', 11, 'SHARE', '2026-05-08 15:05:53');
INSERT INTO user_interactions VALUES (2052979238669025282, 4, 'user', 5, 'follow', '2026-05-09 13:09:27');
INSERT INTO user_interactions VALUES (2053002510399918081, 5, 'REPLY', 11, 'LIKE', '2026-05-09 14:41:56');
INSERT INTO user_interactions VALUES (2053003356332314625, 5, 'MANUSCRIPT', 29, 'SHARE', '2026-05-09 14:45:17');
INSERT INTO user_interactions VALUES (2053019345874800642, 5, 'MANUSCRIPT', 12, 'SHARE', '2026-05-09 15:48:49');
INSERT INTO user_interactions VALUES (2053019363348271105, 5, 'COMMENT', 16, 'LIKE', '2026-05-09 15:48:54');
INSERT INTO user_interactions VALUES (2053035215422390274, 5, 'MANUSCRIPT', 27, 'LIKE', '2026-05-09 16:51:53');
INSERT INTO user_interactions VALUES (2053035313002872833, 5, 'MANUSCRIPT', 27, 'COLLECT', '2026-05-09 16:52:16');
INSERT INTO user_interactions VALUES (2053047614149943297, 5, 'COMMENT', 12, 'LIKE', '2026-05-09 17:41:09');
INSERT INTO user_interactions VALUES (2053069347250688001, 5, 'COMMENT', 15, 'LIKE', '2026-05-09 19:07:31');
INSERT INTO user_interactions VALUES (2053069412103016449, 5, 'REPLY', 12, 'LIKE', '2026-05-09 19:07:46');
INSERT INTO user_interactions VALUES (2053078020538646529, 5, 'REPLY', 7, 'LIKE', '2026-05-09 19:41:59');
INSERT INTO user_interactions VALUES (2053078023940227073, 5, 'COMMENT', 7, 'LIKE', '2026-05-09 19:41:59');
INSERT INTO user_interactions VALUES (2053116048023904258, -69271551, 'MANUSCRIPT', 14, 'LIKE', '2026-05-09 22:13:05');
INSERT INTO user_interactions VALUES (2053116721885020162, -69271551, 'user', 5, 'follow', '2026-05-09 22:15:46');
INSERT INTO user_interactions VALUES (2053143553313259522, 4, 'MANUSCRIPT', 31, 'LIKE', '2026-05-10 00:02:23');

-- ----------------------------
-- Table structure for user_privacy_settings
-- ----------------------------
DROP TABLE IF EXISTS user_privacy_settings;
CREATE TABLE "user_privacy_settings" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "public_collection" smallint NULL DEFAULT 1,
  "public_birthday_tags" smallint NULL DEFAULT 0,
  "public_coin_videos" smallint NULL DEFAULT 0,
  "public_like_videos" smallint NULL DEFAULT 0,
  "public_following_list" smallint NULL DEFAULT 0,
  "public_followers_list" smallint NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_privacy_settings_uk_user_id" UNIQUE (user_id)
);

-- ----------------------------
-- Records of user_privacy_settings
-- ----------------------------
INSERT INTO user_privacy_settings VALUES (-2145452031, -1767964670, 1, 0, 0, 0, 0, 0, '2026-05-20 22:45:34', '2026-05-20 22:45:34');
INSERT INTO user_privacy_settings VALUES (-2019622911, -69271551, 1, 0, 0, 0, 0, 0, '2026-05-09 22:12:46', '2026-05-09 22:12:46');
INSERT INTO user_privacy_settings VALUES (-1906376703, 4, 1, 0, 0, 0, 0, 0, '2026-05-02 17:55:22', '2026-05-02 17:55:22');
INSERT INTO user_privacy_settings VALUES (-1713426431, 5, 1, 0, 0, 0, 0, 0, '2026-05-04 22:26:50', '2026-05-04 22:26:50');

-- ----------------------------
-- Table structure for user_tags
-- ----------------------------
DROP TABLE IF EXISTS user_tags;
CREATE TABLE "user_tags" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "tag_name" varchar(50) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_tags_uk_user_tag" UNIQUE (user_id, tag_name)
);

-- ----------------------------
-- Records of user_tags
-- ----------------------------
INSERT INTO user_tags VALUES (-1629548543, 5, '全栈工程师', '2026-05-06 22:45:16');
INSERT INTO user_tags VALUES (-731967487, 5, '前端开发者', '2026-05-06 22:45:09');
INSERT INTO user_tags VALUES (752762881, 4, '程序员', '2026-05-03 23:07:56');

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS users;
CREATE TABLE "users" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar(50) NOT NULL,
  "password" varchar(255) NOT NULL,
  "nickname" varchar(50) NOT NULL,
  "avatar" varchar(255) NULL DEFAULT NULL,
  "email" varchar(100) NULL DEFAULT NULL,
  "phone" varchar(20) NULL DEFAULT NULL,
  "gender" smallint NULL DEFAULT 0,
  "signature" varchar(255) NULL DEFAULT '',
  "birthdate" date NULL DEFAULT NULL,
  "level" integer NULL DEFAULT 1,
  "following_count" integer NULL DEFAULT 0,
  "follower_count" integer NULL DEFAULT 0,
  "manuscript_count" integer NULL DEFAULT 0,
  "liked_count" integer NULL DEFAULT 0,
  "coin_count" integer NULL DEFAULT 0,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "status" integer NULL DEFAULT 0,
  "pinned_video_id" integer NULL DEFAULT NULL,
  "experience" integer NULL DEFAULT 0,
  "bio" text NULL,
  "announcement" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_username" UNIQUE (username),
  CONSTRAINT "users_email" UNIQUE (email),
  CONSTRAINT "users_phone" UNIQUE (phone)
);

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO users VALUES (4, 'string', '$2a$10$4CcJDm2RUaRhXMppYr.Rj.Q7yMK.NQFSRi7QdeH8FUa/ELfLGpwXG', '测试用户', '/uploads/avatars/4/avatar.jpg', '123@qq.com', '13011011111', 1, '你好朋友们', '2026-03-17', 1, 1, 1, 0, 11, 207, '2026-03-02 22:31:41', '2026-05-20 00:00:01', 1, 10, 57, '', '999');
INSERT INTO users VALUES (5, 'test', '$2a$10$EiwLhC5FdeaALJmFEdVdg.fQvbuKaTNM2HWFweipvK6ieoQbSMzV6', 'test666', '/uploads/avatars/5/avatar.jpg', '321@qq.com', '17733311111', 1, '哈哈哈哈哈', '2026-03-09', 1, 1, 2, 0, 13, 210, '2026-03-04 20:48:47', '2026-05-20 00:00:01', 1, 14, 9, '666', '666');
INSERT INTO users VALUES (6, 'admin', '$2a$10$FpNqkWXQJoaOwAYCeWzK6u5EMMgSypBWwuvU5H7lUbolDB3AXtf.W', 'admin', 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', '12111@qq.com', '11111111111', NULL, '', '2026-03-19', 1, 0, 0, 0, 0, 210, '2026-03-17 09:00:05', '2026-05-20 23:36:33', 1, NULL, 0, '', NULL);
INSERT INTO users VALUES (7, 'stringstring', '$2a$10$pnyDK2JNckAbQljEOiKuxeb0wZmJgiOdPIlOt8.5nLQGC7Az3vkUG', 'stringstring', 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', '123123@123.com', NULL, 0, '', NULL, 1, 0, 0, 0, 0, 0, '2026-05-20 23:34:50', '2026-05-20 23:36:33', 1, NULL, 0, '', NULL);

-- ----------------------------
-- Table structure for video_tags
-- ----------------------------
DROP TABLE IF EXISTS video_tags;
CREATE TABLE "video_tags" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "video_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "video_tags_uk_video_tag" UNIQUE (video_id, tag_id)
);

-- ----------------------------
-- Records of video_tags
-- ----------------------------
INSERT INTO video_tags VALUES (1, 29, 20, '2026-03-16 23:20:36');
INSERT INTO video_tags VALUES (2, 30, 20, '2026-03-16 23:23:05');
INSERT INTO video_tags VALUES (3, 31, 20, '2026-03-16 23:28:28');
INSERT INTO video_tags VALUES (9, 34, 26, '2026-04-03 18:02:58');
INSERT INTO video_tags VALUES (10, 36, -1650552831, '2026-04-03 19:12:28');
INSERT INTO video_tags VALUES (11, 36, -1587638271, '2026-04-03 19:12:28');
INSERT INTO video_tags VALUES (16, 38, 2120134657, '2026-05-09 23:38:34');
INSERT INTO video_tags VALUES (17, 38, -2111918079, '2026-05-09 23:38:34');
INSERT INTO video_tags VALUES (18, 38, -2044809214, '2026-05-09 23:38:34');
INSERT INTO video_tags VALUES (19, 39, 400424961, '2026-05-10 08:05:27');
INSERT INTO video_tags VALUES (20, 39, 2120134657, '2026-05-10 08:05:27');
INSERT INTO video_tags VALUES (21, 39, 438173698, '2026-05-10 08:05:27');

-- ----------------------------
-- Table structure for videos
-- ----------------------------
DROP TABLE IF EXISTS videos;
CREATE TABLE "videos" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "manuscript_id" integer NULL DEFAULT NULL,
  "video_order" integer NULL DEFAULT 0,
  "title" varchar(100) NOT NULL,
  "play_url_hd" varchar(255) NULL DEFAULT NULL,
  "play_url_sd" varchar(255) NULL DEFAULT NULL,
  "play_url_ld" varchar(255) NULL DEFAULT NULL,
  "upload_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "process_progress" integer NULL DEFAULT 0,
  "process_stage" varchar(50) NULL DEFAULT NULL,
  "has_subtitle" smallint NULL DEFAULT 0,
  "has_summary" smallint NULL DEFAULT 0,
  "process_status" integer NULL DEFAULT 0,
  "process_error" varchar(500) NULL DEFAULT NULL,
  "source_video_url" varchar(500) NULL DEFAULT NULL,
  "duration_seconds" integer NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of videos
-- ----------------------------
INSERT INTO videos VALUES (25, 10, 0, '无限零成本token，我给OpenClaw换了个永动机芯！【小白安装教程】', '/uploads/manuscripts/10/videos/25/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/10/videos/25/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/10/videos/25/transcoded/480p/playlist.m3u8', '2026-03-15 11:01:32', '2026-04-11 10:49:04', 0, NULL, 1, 1, 5, '', '/uploads/manuscripts/10/videos/25/source/video.mp4', 384);
INSERT INTO videos VALUES (26, 11, 0, 'AI Agent正在重走操作系统的老路', '/uploads/manuscripts/11/videos/26/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/11/videos/26/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/11/videos/26/transcoded/480p/playlist.m3u8', '2026-03-16 22:50:59', '2026-04-11 10:49:04', 0, NULL, 0, 1, 5, NULL, '/uploads/manuscripts/11/videos/26/source/video.mp4', 271);
INSERT INTO videos VALUES (27, 11, 1, '谁在给AI投毒？GEO灰产是如何割韭菜的？', '/uploads/manuscripts/11/videos/27/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/11/videos/27/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/11/videos/27/transcoded/480p/playlist.m3u8', '2026-03-16 22:50:59', '2026-04-11 16:17:49', 0, NULL, 0, 1, 5, NULL, '/uploads/manuscripts/11/videos/27/source/video.mp4', 230);
INSERT INTO videos VALUES (28, 11, 2, '周鸿祎建议大家别只把AI当搜索引擎用', '/uploads/manuscripts/11/videos/28/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/11/videos/28/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/11/videos/28/transcoded/480p/playlist.m3u8', '2026-03-16 22:50:59', '2026-04-11 17:13:39', 0, NULL, 1, 1, 5, NULL, '/uploads/manuscripts/11/videos/28/source/video.mp4', 155);
INSERT INTO videos VALUES (29, 12, 0, '把 OpenClaw 翻译成“小龙虾”的，出来挨打！', '/uploads/manuscripts/12/videos/29/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/12/videos/29/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/12/videos/29/transcoded/480p/playlist.m3u8', '2026-03-16 23:20:36', '2026-04-11 22:21:28', 0, NULL, 0, 1, 5, NULL, '/uploads/manuscripts/12/videos/29/source/video.mp4', 196);
INSERT INTO videos VALUES (30, 13, 0, '数学怎么提分', '/uploads/manuscripts/13/videos/30/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/13/videos/30/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/13/videos/30/transcoded/480p/playlist.m3u8', '2026-03-16 23:23:05', '2026-04-11 22:35:43', 0, NULL, 0, 1, 5, NULL, '/uploads/manuscripts/13/videos/30/source/video.mp4', 71);
INSERT INTO videos VALUES (31, 14, 0, '每天学习一个电子知识，今天学习如何测电压', '/uploads/manuscripts/14/videos/31/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/14/videos/31/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/14/videos/31/transcoded/480p/playlist.m3u8', '2026-03-16 23:28:28', '2026-04-11 10:49:04', 0, NULL, 1, 1, 5, NULL, '/uploads/manuscripts/14/videos/31/source/video.mp4', 26);
INSERT INTO videos VALUES (34, 27, 0, '投篮力线错误？这样改！', '/uploads/manuscripts/27/videos/34/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/27/videos/34/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/27/videos/34/transcoded/480p/playlist.m3u8', '2026-04-03 18:02:58', '2026-05-09 14:01:34', 100, 'AI_SUCCESS', 1, 1, 5, NULL, '/uploads/manuscripts/27/videos/34/source/video.mp4', 69);
INSERT INTO videos VALUES (36, 29, 0, '9', '/uploads/manuscripts/29/videos/36/transcoded/1080p/playlist.m3u8', '/uploads/manuscripts/29/videos/36/transcoded/720p/playlist.m3u8', '/uploads/manuscripts/29/videos/36/transcoded/480p/playlist.m3u8', '2026-04-03 19:12:28', '2026-05-09 23:11:28', 100, 'AI_SUCCESS', 1, 1, 5, NULL, '/uploads/manuscripts/29/videos/36/source/video.mp4', 38);
INSERT INTO videos VALUES (38, 31, 0, 'github短视频生成工具', NULL, NULL, NULL, '2026-05-09 23:38:34', '2026-05-09 23:54:47', 0, 'AI_SUCCESS', 1, 1, 5, NULL, '/uploads/manuscripts/31/videos/38/source/video.mp4', 47);
INSERT INTO videos VALUES (39, 32, 0, '开源Skills', NULL, NULL, NULL, '2026-05-10 08:05:28', '2026-05-10 08:05:27', 0, NULL, NULL, NULL, 0, NULL, '/uploads/manuscripts/32/videos/39/source/video.mp4', 27);




-- Create indexes
CREATE INDEX IF NOT EXISTS "admin_user_roles_role_id" ON "admin_user_roles" (role_id);
CREATE INDEX IF NOT EXISTS "ai_chat_messages_idx_conversation_id" ON "ai_chat_messages" (conversation_id);
CREATE INDEX IF NOT EXISTS "ai_conversations_idx_user_id" ON "ai_conversations" (user_id);
CREATE INDEX IF NOT EXISTS "banner_images_idx_type" ON "banner_images" (type);
CREATE INDEX IF NOT EXISTS "banner_images_idx_category_id" ON "banner_images" (category_id);
CREATE INDEX IF NOT EXISTS "banner_images_idx_status" ON "banner_images" (status);
CREATE INDEX IF NOT EXISTS "comments_user_id" ON "comments" (user_id);
CREATE INDEX IF NOT EXISTS "comments_idx_comments_video_id" ON "comments" (manuscript_id);
CREATE INDEX IF NOT EXISTS "conversations_idx_user_id" ON "conversations" (user_id);
CREATE INDEX IF NOT EXISTS "conversations_idx_target_user_id" ON "conversations" (target_user_id);
CREATE INDEX IF NOT EXISTS "conversations_idx_last_message_time" ON "conversations" (last_message_time);
CREATE INDEX IF NOT EXISTS "creator_settings_idx_user_id" ON "creator_settings" (user_id);
CREATE INDEX IF NOT EXISTS "creator_settings_idx_default_category_id" ON "creator_settings" (default_category_id);
CREATE INDEX IF NOT EXISTS "dynamic_comments_idx_dynamic_id" ON "dynamic_comments" (dynamic_id);
CREATE INDEX IF NOT EXISTS "dynamic_comments_idx_user_id" ON "dynamic_comments" (user_id);
CREATE INDEX IF NOT EXISTS "dynamic_comments_idx_parent_id" ON "dynamic_comments" (parent_id);
CREATE INDEX IF NOT EXISTS "favorite_manuscripts_fk_favorite_manuscripts_manuscript" ON "favorite_manuscripts" (manuscript_id);
CREATE INDEX IF NOT EXISTS "live_linkmic_idx_room_id" ON "live_linkmic" (room_id);
CREATE INDEX IF NOT EXISTS "live_linkmic_idx_viewer_id" ON "live_linkmic" (viewer_id);
CREATE INDEX IF NOT EXISTS "live_linkmic_idx_status" ON "live_linkmic" (status);
CREATE INDEX IF NOT EXISTS "live_rooms_idx_user_id" ON "live_rooms" (user_id);
CREATE INDEX IF NOT EXISTS "live_rooms_idx_status" ON "live_rooms" (status);
CREATE INDEX IF NOT EXISTS "manuscript_collection_relations_idx_collection_id" ON "manuscript_collection_relations" (collection_id);
CREATE INDEX IF NOT EXISTS "manuscript_collection_relations_idx_collection_order" ON "manuscript_collection_relations" (collection_id, collection_order);
CREATE INDEX IF NOT EXISTS "manuscript_collections_idx_user_id" ON "manuscript_collections" (user_id);
CREATE INDEX IF NOT EXISTS "manuscript_collections_idx_status" ON "manuscript_collections" (status);
CREATE INDEX IF NOT EXISTS "manuscripts_idx_user_id" ON "manuscripts" (user_id);
CREATE INDEX IF NOT EXISTS "manuscripts_idx_category_id" ON "manuscripts" (category_id);
CREATE INDEX IF NOT EXISTS "manuscripts_idx_status" ON "manuscripts" (status);
CREATE INDEX IF NOT EXISTS "manuscripts_idx_upload_time" ON "manuscripts" (upload_time);
CREATE INDEX IF NOT EXISTS "meeting_participant_idx_room_id" ON "meeting_participant" (room_id);
CREATE INDEX IF NOT EXISTS "meeting_participant_idx_user_id" ON "meeting_participant" (user_id);
CREATE INDEX IF NOT EXISTS "meeting_room_idx_room_code" ON "meeting_room" (room_code);
CREATE INDEX IF NOT EXISTS "meeting_room_idx_creator_id" ON "meeting_room" (creator_id);
CREATE INDEX IF NOT EXISTS "message_settings_idx_user_id" ON "message_settings" (user_id);
CREATE INDEX IF NOT EXISTS "messages_sender_id" ON "messages" (sender_id);
CREATE INDEX IF NOT EXISTS "messages_receiver_id" ON "messages" (receiver_id);
CREATE INDEX IF NOT EXISTS "permissions_parent_id" ON "permissions" (parent_id);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_operator" ON "audit_logs" (operator_id);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_module_action" ON "audit_logs" (module, action);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_result" ON "audit_logs" (result);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_target" ON "audit_logs" (target_type, target_id);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_created_at" ON "audit_logs" (created_at);
CREATE INDEX IF NOT EXISTS "operation_tasks_idx_operation_task_type" ON "operation_tasks" (task_type);
CREATE INDEX IF NOT EXISTS "operation_tasks_idx_operation_task_status" ON "operation_tasks" (status);
CREATE INDEX IF NOT EXISTS "operation_tasks_idx_operation_task_target" ON "operation_tasks" (target_type, target_id);
CREATE INDEX IF NOT EXISTS "operation_tasks_idx_operation_task_created_at" ON "operation_tasks" (created_at);
CREATE INDEX IF NOT EXISTS "prohibited_words_idx_word" ON "prohibited_words" (word);
CREATE INDEX IF NOT EXISTS "prohibited_words_idx_category" ON "prohibited_words" (category);
CREATE INDEX IF NOT EXISTS "prohibited_words_idx_is_enabled" ON "prohibited_words" (is_enabled);
CREATE INDEX IF NOT EXISTS "replies_user_id" ON "replies" (user_id);
CREATE INDEX IF NOT EXISTS "replies_idx_replies_comment_id" ON "replies" (comment_id);
CREATE INDEX IF NOT EXISTS "replies_reply_to_user_id" ON "replies" (reply_to_user_id);
CREATE INDEX IF NOT EXISTS "role_permissions_permission_id" ON "role_permissions" (permission_id);
CREATE INDEX IF NOT EXISTS "shares_idx_manuscript_id" ON "shares" (manuscript_id);
CREATE INDEX IF NOT EXISTS "user_dynamics_user_id" ON "user_dynamics" (user_id);
CREATE INDEX IF NOT EXISTS "user_interactions_idx_target" ON "user_interactions" (target_type, target_id, interaction_type);
CREATE INDEX IF NOT EXISTS "user_interactions_idx_user" ON "user_interactions" (user_id, interaction_type, created_at);
CREATE INDEX IF NOT EXISTS "user_interactions_idx_user_target" ON "user_interactions" (user_id, target_type, target_id);
CREATE INDEX IF NOT EXISTS "user_tags_idx_user_id" ON "user_tags" (user_id);
CREATE INDEX IF NOT EXISTS "users_idx_users_pinned_video_id" ON "users" (pinned_video_id);
CREATE INDEX IF NOT EXISTS "video_tags_tag_id" ON "video_tags" (tag_id);
CREATE INDEX IF NOT EXISTS "videos_idx_videos_upload_time" ON "videos" (upload_time);
CREATE INDEX IF NOT EXISTS "videos_idx_manuscript_id" ON "videos" (manuscript_id);

-- Add foreign key constraints
ALTER TABLE "admin_user_roles" ADD CONSTRAINT "admin_user_roles_ibfk_1" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "admin_user_roles" ADD CONSTRAINT "admin_user_roles_ibfk_2" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ai_chat_messages" ADD CONSTRAINT "fk_ai_msg_conversation" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "comments" ADD CONSTRAINT "comments_ibfk_2" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_manuscript" FOREIGN KEY ("manuscript_id") REFERENCES "manuscripts" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_ibfk_2" FOREIGN KEY ("target_user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "creator_settings" ADD CONSTRAINT "creator_settings_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "creator_settings" ADD CONSTRAINT "creator_settings_ibfk_2" FOREIGN KEY ("default_category_id") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE "favorite_folders" ADD CONSTRAINT "favorite_folders_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "favorite_manuscripts" ADD CONSTRAINT "fk_favorite_manuscripts_folder" FOREIGN KEY ("folder_id") REFERENCES "favorite_folders" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "favorite_manuscripts" ADD CONSTRAINT "fk_favorite_manuscripts_manuscript" FOREIGN KEY ("manuscript_id") REFERENCES "manuscripts" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "manuscript_collection_relations" ADD CONSTRAINT "manuscript_collection_relations_ibfk_1" FOREIGN KEY ("manuscript_id") REFERENCES "manuscripts" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "manuscript_collection_relations" ADD CONSTRAINT "manuscript_collection_relations_ibfk_2" FOREIGN KEY ("collection_id") REFERENCES "manuscript_collections" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "manuscript_collections" ADD CONSTRAINT "manuscript_collections_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "manuscripts" ADD CONSTRAINT "fk_manuscripts_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "message_settings" ADD CONSTRAINT "message_settings_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "messages" ADD CONSTRAINT "messages_ibfk_1" FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "messages" ADD CONSTRAINT "messages_ibfk_2" FOREIGN KEY ("receiver_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "permissions" ADD CONSTRAINT "permissions_ibfk_1" FOREIGN KEY ("parent_id") REFERENCES "permissions" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "replies" ADD CONSTRAINT "replies_ibfk_1" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "replies" ADD CONSTRAINT "replies_ibfk_2" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "replies" ADD CONSTRAINT "replies_ibfk_3" FOREIGN KEY ("reply_to_user_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_ibfk_1" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_ibfk_2" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "user_dynamics" ADD CONSTRAINT "user_dynamics_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "video_tags" ADD CONSTRAINT "video_tags_ibfk_1" FOREIGN KEY ("video_id") REFERENCES "videos" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "video_tags" ADD CONSTRAINT "video_tags_ibfk_2" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "videos" ADD CONSTRAINT "fk_videos_manuscript" FOREIGN KEY ("manuscript_id") REFERENCES "manuscripts" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;

-- Reset sequences
SELECT setval(pg_get_serial_sequence('"admin_users"', 'id'), COALESCE((SELECT MAX(id) FROM "admin_users" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"categories"', 'id'), COALESCE((SELECT MAX(id) FROM "categories" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"comments"', 'id'), COALESCE((SELECT MAX(id) FROM "comments" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"conversations"', 'id'), COALESCE((SELECT MAX(id) FROM "conversations" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"creator_settings"', 'id'), COALESCE((SELECT MAX(id) FROM "creator_settings" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"dynamic_comments"', 'id'), COALESCE((SELECT MAX(id) FROM "dynamic_comments" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"favorite_folders"', 'id'), COALESCE((SELECT MAX(id) FROM "favorite_folders" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"favorite_manuscripts"', 'id'), COALESCE((SELECT MAX(id) FROM "favorite_manuscripts" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"live_rooms"', 'id'), COALESCE((SELECT MAX(id) FROM "live_rooms" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"manuscript_collection_relations"', 'id'), COALESCE((SELECT MAX(id) FROM "manuscript_collection_relations" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"manuscript_collections"', 'id'), COALESCE((SELECT MAX(id) FROM "manuscript_collections" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"manuscripts"', 'id'), COALESCE((SELECT MAX(id) FROM "manuscripts" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"message_settings"', 'id'), COALESCE((SELECT MAX(id) FROM "message_settings" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"messages"', 'id'), COALESCE((SELECT MAX(id) FROM "messages" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"permissions"', 'id'), COALESCE((SELECT MAX(id) FROM "permissions" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"prohibited_words"', 'id'), COALESCE((SELECT MAX(id) FROM "prohibited_words" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"replies"', 'id'), COALESCE((SELECT MAX(id) FROM "replies" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"reports"', 'id'), COALESCE((SELECT MAX(id) FROM "reports" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"roles"', 'id'), COALESCE((SELECT MAX(id) FROM "roles" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"shares"', 'id'), COALESCE((SELECT MAX(id) FROM "shares" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"tags"', 'id'), COALESCE((SELECT MAX(id) FROM "tags" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"user_dynamics"', 'id'), COALESCE((SELECT MAX(id) FROM "user_dynamics" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"user_interactions"', 'id'), COALESCE((SELECT MAX(id) FROM "user_interactions" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"user_privacy_settings"', 'id'), COALESCE((SELECT MAX(id) FROM "user_privacy_settings" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"user_tags"', 'id'), COALESCE((SELECT MAX(id) FROM "user_tags" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"users"', 'id'), COALESCE((SELECT MAX(id) FROM "users" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"video_tags"', 'id'), COALESCE((SELECT MAX(id) FROM "video_tags" WHERE id > 0), 1))
UNION ALL SELECT setval(pg_get_serial_sequence('"videos"', 'id'), COALESCE((SELECT MAX(id) FROM "videos" WHERE id > 0), 1));

SET session_replication_role = 'origin';