// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/core/v1/interaction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionService_LikeManuscript_FullMethodName          = "/core.v1.InteractionService/LikeManuscript"
	InteractionService_UnlikeManuscript_FullMethodName        = "/core.v1.InteractionService/UnlikeManuscript"
	InteractionService_CoinManuscript_FullMethodName          = "/core.v1.InteractionService/CoinManuscript"
	InteractionService_CollectManuscript_FullMethodName       = "/core.v1.InteractionService/CollectManuscript"
	InteractionService_UncollectManuscript_FullMethodName     = "/core.v1.InteractionService/UncollectManuscript"
	InteractionService_ShareManuscript_FullMethodName         = "/core.v1.InteractionService/ShareManuscript"
	InteractionService_GetInteractionStatus_FullMethodName    = "/core.v1.InteractionService/GetInteractionStatus"
	InteractionService_FollowUser_FullMethodName              = "/core.v1.InteractionService/FollowUser"
	InteractionService_UnfollowUser_FullMethodName            = "/core.v1.InteractionService/UnfollowUser"
	InteractionService_CheckFollow_FullMethodName             = "/core.v1.InteractionService/CheckFollow"
	InteractionService_GetFollowCount_FullMethodName          = "/core.v1.InteractionService/GetFollowCount"
	InteractionService_GetLikedManuscripts_FullMethodName     = "/core.v1.InteractionService/GetLikedManuscripts"
	InteractionService_GetCollectedManuscripts_FullMethodName = "/core.v1.InteractionService/GetCollectedManuscripts"
	InteractionService_AddWatchHistory_FullMethodName         = "/core.v1.InteractionService/AddWatchHistory"
	InteractionService_GetWatchHistory_FullMethodName         = "/core.v1.InteractionService/GetWatchHistory"
	InteractionService_ClearWatchHistory_FullMethodName       = "/core.v1.InteractionService/ClearWatchHistory"
)

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionServiceClient interface {
	LikeManuscript(ctx context.Context, in *LikeManuscriptRequest, opts ...grpc.CallOption) (*LikeManuscriptResponse, error)
	UnlikeManuscript(ctx context.Context, in *UnlikeManuscriptRequest, opts ...grpc.CallOption) (*UnlikeManuscriptResponse, error)
	CoinManuscript(ctx context.Context, in *CoinManuscriptRequest, opts ...grpc.CallOption) (*CoinManuscriptResponse, error)
	CollectManuscript(ctx context.Context, in *CollectManuscriptRequest, opts ...grpc.CallOption) (*CollectManuscriptResponse, error)
	UncollectManuscript(ctx context.Context, in *UncollectManuscriptRequest, opts ...grpc.CallOption) (*UncollectManuscriptResponse, error)
	ShareManuscript(ctx context.Context, in *ShareManuscriptRequest, opts ...grpc.CallOption) (*ShareManuscriptResponse, error)
	GetInteractionStatus(ctx context.Context, in *GetInteractionStatusRequest, opts ...grpc.CallOption) (*GetInteractionStatusResponse, error)
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error)
	CheckFollow(ctx context.Context, in *CheckFollowRequest, opts ...grpc.CallOption) (*CheckFollowResponse, error)
	GetFollowCount(ctx context.Context, in *GetFollowCountRequest, opts ...grpc.CallOption) (*GetFollowCountResponse, error)
	GetLikedManuscripts(ctx context.Context, in *GetLikedManuscriptsRequest, opts ...grpc.CallOption) (*GetLikedManuscriptsResponse, error)
	GetCollectedManuscripts(ctx context.Context, in *GetCollectedManuscriptsRequest, opts ...grpc.CallOption) (*GetCollectedManuscriptsResponse, error)
	AddWatchHistory(ctx context.Context, in *AddWatchHistoryRequest, opts ...grpc.CallOption) (*AddWatchHistoryResponse, error)
	GetWatchHistory(ctx context.Context, in *GetWatchHistoryRequest, opts ...grpc.CallOption) (*GetWatchHistoryResponse, error)
	ClearWatchHistory(ctx context.Context, in *ClearWatchHistoryRequest, opts ...grpc.CallOption) (*ClearWatchHistoryResponse, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) LikeManuscript(ctx context.Context, in *LikeManuscriptRequest, opts ...grpc.CallOption) (*LikeManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeManuscriptResponse)
	err := c.cc.Invoke(ctx, InteractionService_LikeManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UnlikeManuscript(ctx context.Context, in *UnlikeManuscriptRequest, opts ...grpc.CallOption) (*UnlikeManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeManuscriptResponse)
	err := c.cc.Invoke(ctx, InteractionService_UnlikeManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CoinManuscript(ctx context.Context, in *CoinManuscriptRequest, opts ...grpc.CallOption) (*CoinManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoinManuscriptResponse)
	err := c.cc.Invoke(ctx, InteractionService_CoinManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CollectManuscript(ctx context.Context, in *CollectManuscriptRequest, opts ...grpc.CallOption) (*CollectManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectManuscriptResponse)
	err := c.cc.Invoke(ctx, InteractionService_CollectManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UncollectManuscript(ctx context.Context, in *UncollectManuscriptRequest, opts ...grpc.CallOption) (*UncollectManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UncollectManuscriptResponse)
	err := c.cc.Invoke(ctx, InteractionService_UncollectManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) ShareManuscript(ctx context.Context, in *ShareManuscriptRequest, opts ...grpc.CallOption) (*ShareManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareManuscriptResponse)
	err := c.cc.Invoke(ctx, InteractionService_ShareManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetInteractionStatus(ctx context.Context, in *GetInteractionStatusRequest, opts ...grpc.CallOption) (*GetInteractionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInteractionStatusResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetInteractionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, InteractionService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserResponse)
	err := c.cc.Invoke(ctx, InteractionService_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CheckFollow(ctx context.Context, in *CheckFollowRequest, opts ...grpc.CallOption) (*CheckFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFollowResponse)
	err := c.cc.Invoke(ctx, InteractionService_CheckFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetFollowCount(ctx context.Context, in *GetFollowCountRequest, opts ...grpc.CallOption) (*GetFollowCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowCountResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetFollowCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetLikedManuscripts(ctx context.Context, in *GetLikedManuscriptsRequest, opts ...grpc.CallOption) (*GetLikedManuscriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikedManuscriptsResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetLikedManuscripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetCollectedManuscripts(ctx context.Context, in *GetCollectedManuscriptsRequest, opts ...grpc.CallOption) (*GetCollectedManuscriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectedManuscriptsResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetCollectedManuscripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) AddWatchHistory(ctx context.Context, in *AddWatchHistoryRequest, opts ...grpc.CallOption) (*AddWatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWatchHistoryResponse)
	err := c.cc.Invoke(ctx, InteractionService_AddWatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetWatchHistory(ctx context.Context, in *GetWatchHistoryRequest, opts ...grpc.CallOption) (*GetWatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWatchHistoryResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetWatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) ClearWatchHistory(ctx context.Context, in *ClearWatchHistoryRequest, opts ...grpc.CallOption) (*ClearWatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearWatchHistoryResponse)
	err := c.cc.Invoke(ctx, InteractionService_ClearWatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
// All implementations must embed UnimplementedInteractionServiceServer
// for forward compatibility.
type InteractionServiceServer interface {
	LikeManuscript(context.Context, *LikeManuscriptRequest) (*LikeManuscriptResponse, error)
	UnlikeManuscript(context.Context, *UnlikeManuscriptRequest) (*UnlikeManuscriptResponse, error)
	CoinManuscript(context.Context, *CoinManuscriptRequest) (*CoinManuscriptResponse, error)
	CollectManuscript(context.Context, *CollectManuscriptRequest) (*CollectManuscriptResponse, error)
	UncollectManuscript(context.Context, *UncollectManuscriptRequest) (*UncollectManuscriptResponse, error)
	ShareManuscript(context.Context, *ShareManuscriptRequest) (*ShareManuscriptResponse, error)
	GetInteractionStatus(context.Context, *GetInteractionStatusRequest) (*GetInteractionStatusResponse, error)
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error)
	CheckFollow(context.Context, *CheckFollowRequest) (*CheckFollowResponse, error)
	GetFollowCount(context.Context, *GetFollowCountRequest) (*GetFollowCountResponse, error)
	GetLikedManuscripts(context.Context, *GetLikedManuscriptsRequest) (*GetLikedManuscriptsResponse, error)
	GetCollectedManuscripts(context.Context, *GetCollectedManuscriptsRequest) (*GetCollectedManuscriptsResponse, error)
	AddWatchHistory(context.Context, *AddWatchHistoryRequest) (*AddWatchHistoryResponse, error)
	GetWatchHistory(context.Context, *GetWatchHistoryRequest) (*GetWatchHistoryResponse, error)
	ClearWatchHistory(context.Context, *ClearWatchHistoryRequest) (*ClearWatchHistoryResponse, error)
	mustEmbedUnimplementedInteractionServiceServer()
}

// UnimplementedInteractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServiceServer struct{}

func (UnimplementedInteractionServiceServer) LikeManuscript(context.Context, *LikeManuscriptRequest) (*LikeManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeManuscript not implemented")
}
func (UnimplementedInteractionServiceServer) UnlikeManuscript(context.Context, *UnlikeManuscriptRequest) (*UnlikeManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeManuscript not implemented")
}
func (UnimplementedInteractionServiceServer) CoinManuscript(context.Context, *CoinManuscriptRequest) (*CoinManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoinManuscript not implemented")
}
func (UnimplementedInteractionServiceServer) CollectManuscript(context.Context, *CollectManuscriptRequest) (*CollectManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectManuscript not implemented")
}
func (UnimplementedInteractionServiceServer) UncollectManuscript(context.Context, *UncollectManuscriptRequest) (*UncollectManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UncollectManuscript not implemented")
}
func (UnimplementedInteractionServiceServer) ShareManuscript(context.Context, *ShareManuscriptRequest) (*ShareManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareManuscript not implemented")
}
func (UnimplementedInteractionServiceServer) GetInteractionStatus(context.Context, *GetInteractionStatusRequest) (*GetInteractionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInteractionStatus not implemented")
}
func (UnimplementedInteractionServiceServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedInteractionServiceServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedInteractionServiceServer) CheckFollow(context.Context, *CheckFollowRequest) (*CheckFollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFollow not implemented")
}
func (UnimplementedInteractionServiceServer) GetFollowCount(context.Context, *GetFollowCountRequest) (*GetFollowCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowCount not implemented")
}
func (UnimplementedInteractionServiceServer) GetLikedManuscripts(context.Context, *GetLikedManuscriptsRequest) (*GetLikedManuscriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikedManuscripts not implemented")
}
func (UnimplementedInteractionServiceServer) GetCollectedManuscripts(context.Context, *GetCollectedManuscriptsRequest) (*GetCollectedManuscriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectedManuscripts not implemented")
}
func (UnimplementedInteractionServiceServer) AddWatchHistory(context.Context, *AddWatchHistoryRequest) (*AddWatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWatchHistory not implemented")
}
func (UnimplementedInteractionServiceServer) GetWatchHistory(context.Context, *GetWatchHistoryRequest) (*GetWatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWatchHistory not implemented")
}
func (UnimplementedInteractionServiceServer) ClearWatchHistory(context.Context, *ClearWatchHistoryRequest) (*ClearWatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearWatchHistory not implemented")
}
func (UnimplementedInteractionServiceServer) mustEmbedUnimplementedInteractionServiceServer() {}
func (UnimplementedInteractionServiceServer) testEmbeddedByValue()                            {}

// UnsafeInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServiceServer will
// result in compilation errors.
type UnsafeInteractionServiceServer interface {
	mustEmbedUnimplementedInteractionServiceServer()
}

func RegisterInteractionServiceServer(s grpc.ServiceRegistrar, srv InteractionServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionService_ServiceDesc, srv)
}

func _InteractionService_LikeManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).LikeManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_LikeManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).LikeManuscript(ctx, req.(*LikeManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UnlikeManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UnlikeManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UnlikeManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UnlikeManuscript(ctx, req.(*UnlikeManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CoinManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CoinManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CoinManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CoinManuscript(ctx, req.(*CoinManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CollectManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CollectManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CollectManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CollectManuscript(ctx, req.(*CollectManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UncollectManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncollectManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UncollectManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UncollectManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UncollectManuscript(ctx, req.(*UncollectManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_ShareManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).ShareManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_ShareManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).ShareManuscript(ctx, req.(*ShareManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetInteractionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInteractionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetInteractionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetInteractionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetInteractionStatus(ctx, req.(*GetInteractionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CheckFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CheckFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CheckFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CheckFollow(ctx, req.(*CheckFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetFollowCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetFollowCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetFollowCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetFollowCount(ctx, req.(*GetFollowCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetLikedManuscripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedManuscriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetLikedManuscripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetLikedManuscripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetLikedManuscripts(ctx, req.(*GetLikedManuscriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetCollectedManuscripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectedManuscriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetCollectedManuscripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetCollectedManuscripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetCollectedManuscripts(ctx, req.(*GetCollectedManuscriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_AddWatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).AddWatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_AddWatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).AddWatchHistory(ctx, req.(*AddWatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetWatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetWatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetWatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetWatchHistory(ctx, req.(*GetWatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_ClearWatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearWatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).ClearWatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_ClearWatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).ClearWatchHistory(ctx, req.(*ClearWatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionService_ServiceDesc is the grpc.ServiceDesc for InteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.v1.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeManuscript",
			Handler:    _InteractionService_LikeManuscript_Handler,
		},
		{
			MethodName: "UnlikeManuscript",
			Handler:    _InteractionService_UnlikeManuscript_Handler,
		},
		{
			MethodName: "CoinManuscript",
			Handler:    _InteractionService_CoinManuscript_Handler,
		},
		{
			MethodName: "CollectManuscript",
			Handler:    _InteractionService_CollectManuscript_Handler,
		},
		{
			MethodName: "UncollectManuscript",
			Handler:    _InteractionService_UncollectManuscript_Handler,
		},
		{
			MethodName: "ShareManuscript",
			Handler:    _InteractionService_ShareManuscript_Handler,
		},
		{
			MethodName: "GetInteractionStatus",
			Handler:    _InteractionService_GetInteractionStatus_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _InteractionService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _InteractionService_UnfollowUser_Handler,
		},
		{
			MethodName: "CheckFollow",
			Handler:    _InteractionService_CheckFollow_Handler,
		},
		{
			MethodName: "GetFollowCount",
			Handler:    _InteractionService_GetFollowCount_Handler,
		},
		{
			MethodName: "GetLikedManuscripts",
			Handler:    _InteractionService_GetLikedManuscripts_Handler,
		},
		{
			MethodName: "GetCollectedManuscripts",
			Handler:    _InteractionService_GetCollectedManuscripts_Handler,
		},
		{
			MethodName: "AddWatchHistory",
			Handler:    _InteractionService_AddWatchHistory_Handler,
		},
		{
			MethodName: "GetWatchHistory",
			Handler:    _InteractionService_GetWatchHistory_Handler,
		},
		{
			MethodName: "ClearWatchHistory",
			Handler:    _InteractionService_ClearWatchHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/interaction.proto",
}
