// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: core/v1/msg_danmaku.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MsgDanmakuService_SendMessage_FullMethodName = "/core.v1.MsgDanmakuService/SendMessage"
)

// MsgDanmakuServiceClient is the client API for MsgDanmakuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgDanmakuServiceClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type msgDanmakuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgDanmakuServiceClient(cc grpc.ClientConnInterface) MsgDanmakuServiceClient {
	return &msgDanmakuServiceClient{cc}
}

func (c *msgDanmakuServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, MsgDanmakuService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgDanmakuServiceServer is the server API for MsgDanmakuService service.
// All implementations must embed UnimplementedMsgDanmakuServiceServer
// for forward compatibility.
type MsgDanmakuServiceServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedMsgDanmakuServiceServer()
}

// UnimplementedMsgDanmakuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgDanmakuServiceServer struct{}

func (UnimplementedMsgDanmakuServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMsgDanmakuServiceServer) mustEmbedUnimplementedMsgDanmakuServiceServer() {}
func (UnimplementedMsgDanmakuServiceServer) testEmbeddedByValue()                           {}

// UnsafeMsgDanmakuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgDanmakuServiceServer will
// result in compilation errors.
type UnsafeMsgDanmakuServiceServer interface {
	mustEmbedUnimplementedMsgDanmakuServiceServer()
}

func RegisterMsgDanmakuServiceServer(s grpc.ServiceRegistrar, srv MsgDanmakuServiceServer) {
	// If the following call panics, it indicates UnimplementedMsgDanmakuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MsgDanmakuService_ServiceDesc, srv)
}

func _MsgDanmakuService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgDanmakuServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgDanmakuService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgDanmakuServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgDanmakuService_ServiceDesc is the grpc.ServiceDesc for MsgDanmakuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgDanmakuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.v1.MsgDanmakuService",
	HandlerType: (*MsgDanmakuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MsgDanmakuService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/msg_danmaku.proto",
}
