// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: core/v1/search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Order         string                 `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosRequest) Reset() {
	*x = SearchVideosRequest{}
	mi := &file_core_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosRequest) ProtoMessage() {}

func (x *SearchVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosRequest.ProtoReflect.Descriptor instead.
func (*SearchVideosRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchVideosRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchVideosRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchVideosRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type SearchVideoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	UploaderId    int64                  `protobuf:"varint,4,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	UploaderName  string                 `protobuf:"bytes,5,opt,name=uploader_name,json=uploaderName,proto3" json:"uploader_name,omitempty"`
	ViewCount     int64                  `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Duration      int32                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoItem) Reset() {
	*x = SearchVideoItem{}
	mi := &file_core_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoItem) ProtoMessage() {}

func (x *SearchVideoItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoItem.ProtoReflect.Descriptor instead.
func (*SearchVideoItem) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchVideoItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchVideoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchVideoItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *SearchVideoItem) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

func (x *SearchVideoItem) GetUploaderName() string {
	if x != nil {
		return x.UploaderName
	}
	return ""
}

func (x *SearchVideoItem) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *SearchVideoItem) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *SearchVideoItem) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SearchVideoItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchVideoItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SearchVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SearchVideoItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosResponse) Reset() {
	*x = SearchVideosResponse{}
	mi := &file_core_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosResponse) ProtoMessage() {}

func (x *SearchVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosResponse.ProtoReflect.Descriptor instead.
func (*SearchVideosResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVideosResponse) GetList() []*SearchVideoItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchVideosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchVideosResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideosResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetHotSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotSearchRequest) Reset() {
	*x = GetHotSearchRequest{}
	mi := &file_core_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotSearchRequest) ProtoMessage() {}

func (x *GetHotSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotSearchRequest.ProtoReflect.Descriptor instead.
func (*GetHotSearchRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{3}
}

type HotKeyword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	SearchCount   int64                  `protobuf:"varint,3,opt,name=search_count,json=searchCount,proto3" json:"search_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotKeyword) Reset() {
	*x = HotKeyword{}
	mi := &file_core_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotKeyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotKeyword) ProtoMessage() {}

func (x *HotKeyword) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotKeyword.ProtoReflect.Descriptor instead.
func (*HotKeyword) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *HotKeyword) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *HotKeyword) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *HotKeyword) GetSearchCount() int64 {
	if x != nil {
		return x.SearchCount
	}
	return 0
}

type GetHotSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HotKeyword          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotSearchResponse) Reset() {
	*x = GetHotSearchResponse{}
	mi := &file_core_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotSearchResponse) ProtoMessage() {}

func (x *GetHotSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotSearchResponse.ProtoReflect.Descriptor instead.
func (*GetHotSearchResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *GetHotSearchResponse) GetList() []*HotKeyword {
	if x != nil {
		return x.List
	}
	return nil
}

type GetSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsRequest) Reset() {
	*x = GetSuggestionsRequest{}
	mi := &file_core_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsRequest) ProtoMessage() {}

func (x *GetSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *GetSuggestionsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetSuggestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsResponse) Reset() {
	*x = GetSuggestionsResponse{}
	mi := &file_core_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsResponse) ProtoMessage() {}

func (x *GetSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *GetSuggestionsResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_core_v1_search_proto protoreflect.FileDescriptor

const file_core_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x14core/v1/search.proto\x12\acore.v1\"\x97\x01\n" +
	"\x13SearchVideosRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05order\x18\x05 \x01(\tR\x05order\"\xae\x02\n" +
	"\x0fSearchVideoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x1f\n" +
	"\vuploader_id\x18\x04 \x01(\x03R\n" +
	"uploaderId\x12#\n" +
	"\ruploader_name\x18\x05 \x01(\tR\fuploaderName\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12\x1a\n" +
	"\bduration\x18\b \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\x8b\x01\n" +
	"\x14SearchVideosResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.core.v1.SearchVideoItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x15\n" +
	"\x13GetHotSearchRequest\"_\n" +
	"\n" +
	"HotKeyword\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12!\n" +
	"\fsearch_count\x18\x03 \x01(\x03R\vsearchCount\"?\n" +
	"\x14GetHotSearchResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.core.v1.HotKeywordR\x04list\"G\n" +
	"\x15GetSuggestionsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\":\n" +
	"\x16GetSuggestionsResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions2\xfc\x01\n" +
	"\rSearchService\x12K\n" +
	"\fSearchVideos\x12\x1c.core.v1.SearchVideosRequest\x1a\x1d.core.v1.SearchVideosResponse\x12K\n" +
	"\fGetHotSearch\x12\x1c.core.v1.GetHotSearchRequest\x1a\x1d.core.v1.GetHotSearchResponse\x12Q\n" +
	"\x0eGetSuggestions\x12\x1e.core.v1.GetSuggestionsRequest\x1a\x1f.core.v1.GetSuggestionsResponseB\x13Z\x11mybilibili/pkg/pbb\x06proto3"

var (
	file_core_v1_search_proto_rawDescOnce sync.Once
	file_core_v1_search_proto_rawDescData []byte
)

func file_core_v1_search_proto_rawDescGZIP() []byte {
	file_core_v1_search_proto_rawDescOnce.Do(func() {
		file_core_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_search_proto_rawDesc), len(file_core_v1_search_proto_rawDesc)))
	})
	return file_core_v1_search_proto_rawDescData
}

var file_core_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_core_v1_search_proto_goTypes = []any{
	(*SearchVideosRequest)(nil),    // 0: core.v1.SearchVideosRequest
	(*SearchVideoItem)(nil),        // 1: core.v1.SearchVideoItem
	(*SearchVideosResponse)(nil),   // 2: core.v1.SearchVideosResponse
	(*GetHotSearchRequest)(nil),    // 3: core.v1.GetHotSearchRequest
	(*HotKeyword)(nil),             // 4: core.v1.HotKeyword
	(*GetHotSearchResponse)(nil),   // 5: core.v1.GetHotSearchResponse
	(*GetSuggestionsRequest)(nil),  // 6: core.v1.GetSuggestionsRequest
	(*GetSuggestionsResponse)(nil), // 7: core.v1.GetSuggestionsResponse
}
var file_core_v1_search_proto_depIdxs = []int32{
	1, // 0: core.v1.SearchVideosResponse.list:type_name -> core.v1.SearchVideoItem
	4, // 1: core.v1.GetHotSearchResponse.list:type_name -> core.v1.HotKeyword
	0, // 2: core.v1.SearchService.SearchVideos:input_type -> core.v1.SearchVideosRequest
	3, // 3: core.v1.SearchService.GetHotSearch:input_type -> core.v1.GetHotSearchRequest
	6, // 4: core.v1.SearchService.GetSuggestions:input_type -> core.v1.GetSuggestionsRequest
	2, // 5: core.v1.SearchService.SearchVideos:output_type -> core.v1.SearchVideosResponse
	5, // 6: core.v1.SearchService.GetHotSearch:output_type -> core.v1.GetHotSearchResponse
	7, // 7: core.v1.SearchService.GetSuggestions:output_type -> core.v1.GetSuggestionsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_v1_search_proto_init() }
func file_core_v1_search_proto_init() {
	if File_core_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_search_proto_rawDesc), len(file_core_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_search_proto_goTypes,
		DependencyIndexes: file_core_v1_search_proto_depIdxs,
		MessageInfos:      file_core_v1_search_proto_msgTypes,
	}.Build()
	File_core_v1_search_proto = out.File
	file_core_v1_search_proto_goTypes = nil
	file_core_v1_search_proto_depIdxs = nil
}
