// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: core/v1/ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewContentRequest) Reset() {
	*x = ReviewContentRequest{}
	mi := &file_core_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewContentRequest) ProtoMessage() {}

func (x *ReviewContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewContentRequest.ProtoReflect.Descriptor instead.
func (*ReviewContentRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewContentRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

type ReviewContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewContentResponse) Reset() {
	*x = ReviewContentResponse{}
	mi := &file_core_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewContentResponse) ProtoMessage() {}

func (x *ReviewContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewContentResponse.ProtoReflect.Descriptor instead.
func (*ReviewContentResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewContentResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ReviewContentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReviewContentResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ManuscriptId  int64                  `protobuf:"varint,2,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_core_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetSummaryRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetSummaryRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	HasSummary    bool                   `protobuf:"varint,2,opt,name=has_summary,json=hasSummary,proto3" json:"has_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_core_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GetSummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetSummaryResponse) GetHasSummary() bool {
	if x != nil {
		return x.HasSummary
	}
	return false
}

var File_core_v1_ai_proto protoreflect.FileDescriptor

const file_core_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x10core/v1/ai.proto\x12\acore.v1\"F\n" +
	"\x14ReviewContentRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\"]\n" +
	"\x15ReviewContentResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"S\n" +
	"\x11GetSummaryRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12#\n" +
	"\rmanuscript_id\x18\x02 \x01(\x03R\fmanuscriptId\"O\n" +
	"\x12GetSummaryResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1f\n" +
	"\vhas_summary\x18\x02 \x01(\bR\n" +
	"hasSummary2\xa2\x01\n" +
	"\tAiService\x12N\n" +
	"\rReviewContent\x12\x1d.core.v1.ReviewContentRequest\x1a\x1e.core.v1.ReviewContentResponse\x12E\n" +
	"\n" +
	"GetSummary\x12\x1a.core.v1.GetSummaryRequest\x1a\x1b.core.v1.GetSummaryResponseB\x13Z\x11mybilibili/pkg/pbb\x06proto3"

var (
	file_core_v1_ai_proto_rawDescOnce sync.Once
	file_core_v1_ai_proto_rawDescData []byte
)

func file_core_v1_ai_proto_rawDescGZIP() []byte {
	file_core_v1_ai_proto_rawDescOnce.Do(func() {
		file_core_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_ai_proto_rawDesc), len(file_core_v1_ai_proto_rawDesc)))
	})
	return file_core_v1_ai_proto_rawDescData
}

var file_core_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_v1_ai_proto_goTypes = []any{
	(*ReviewContentRequest)(nil),  // 0: core.v1.ReviewContentRequest
	(*ReviewContentResponse)(nil), // 1: core.v1.ReviewContentResponse
	(*GetSummaryRequest)(nil),     // 2: core.v1.GetSummaryRequest
	(*GetSummaryResponse)(nil),    // 3: core.v1.GetSummaryResponse
}
var file_core_v1_ai_proto_depIdxs = []int32{
	0, // 0: core.v1.AiService.ReviewContent:input_type -> core.v1.ReviewContentRequest
	2, // 1: core.v1.AiService.GetSummary:input_type -> core.v1.GetSummaryRequest
	1, // 2: core.v1.AiService.ReviewContent:output_type -> core.v1.ReviewContentResponse
	3, // 3: core.v1.AiService.GetSummary:output_type -> core.v1.GetSummaryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_ai_proto_init() }
func file_core_v1_ai_proto_init() {
	if File_core_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_ai_proto_rawDesc), len(file_core_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_ai_proto_goTypes,
		DependencyIndexes: file_core_v1_ai_proto_depIdxs,
		MessageInfos:      file_core_v1_ai_proto_msgTypes,
	}.Build()
	File_core_v1_ai_proto = out.File
	file_core_v1_ai_proto_goTypes = nil
	file_core_v1_ai_proto_depIdxs = nil
}
