// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/core/v1/comment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ManuscriptId  int64                  `protobuf:"varint,2,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserAvatar    string                 `protobuf:"bytes,5,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	UserLevel     int32                  `protobuf:"varint,6,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     int32                  `protobuf:"varint,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,9,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Liked         bool                   `protobuf:"varint,11,opt,name=liked,proto3" json:"liked,omitempty"`
	Replies       []*ReplyInfo           `protobuf:"bytes,12,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *CommentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CommentInfo) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *CommentInfo) GetUserLevel() int32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *CommentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentInfo) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *CommentInfo) GetReplies() []*ReplyInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

type ReplyInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CommentId       int64                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId          int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName        string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserAvatar      string                 `protobuf:"bytes,5,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	UserLevel       int32                  `protobuf:"varint,6,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	Content         string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount       int32                  `protobuf:"varint,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReplyToUserName string                 `protobuf:"bytes,10,opt,name=reply_to_user_name,json=replyToUserName,proto3" json:"reply_to_user_name,omitempty"`
	Liked           bool                   `protobuf:"varint,11,opt,name=liked,proto3" json:"liked,omitempty"`
	ReplyToUserId   int64                  `protobuf:"varint,12,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplyInfo) Reset() {
	*x = ReplyInfo{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyInfo) ProtoMessage() {}

func (x *ReplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyInfo.ProtoReflect.Descriptor instead.
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplyInfo) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ReplyInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplyInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReplyInfo) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *ReplyInfo) GetUserLevel() int32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

func (x *ReplyInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyInfo) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ReplyInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReplyInfo) GetReplyToUserName() string {
	if x != nil {
		return x.ReplyToUserName
	}
	return ""
}

func (x *ReplyInfo) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *ReplyInfo) GetReplyToUserId() int64 {
	if x != nil {
		return x.ReplyToUserId
	}
	return 0
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *AddCommentRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *AddCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentInfo           `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *AddCommentResponse) GetComment() *CommentInfo {
	if x != nil {
		return x.Comment
	}
	return nil
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommentsRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *ListCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListCommentsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommentsResponse) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{7}
}

type AddReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ReplyToUserId int64                  `protobuf:"varint,4,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplyRequest) Reset() {
	*x = AddReplyRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyRequest) ProtoMessage() {}

func (x *AddReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyRequest.ProtoReflect.Descriptor instead.
func (*AddReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *AddReplyRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *AddReplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddReplyRequest) GetReplyToUserId() int64 {
	if x != nil {
		return x.ReplyToUserId
	}
	return 0
}

type AddReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *ReplyInfo             `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplyResponse) Reset() {
	*x = AddReplyResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyResponse) ProtoMessage() {}

func (x *AddReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyResponse.ProtoReflect.Descriptor instead.
func (*AddReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *AddReplyResponse) GetReply() *ReplyInfo {
	if x != nil {
		return x.Reply
	}
	return nil
}

type GetRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesRequest) Reset() {
	*x = GetRepliesRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesRequest) ProtoMessage() {}

func (x *GetRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetRepliesRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *GetRepliesRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *GetRepliesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRepliesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRepliesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*ReplyInfo           `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesResponse) Reset() {
	*x = GetRepliesResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesResponse) ProtoMessage() {}

func (x *GetRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesResponse.ProtoReflect.Descriptor instead.
func (*GetRepliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{11}
}

func (x *GetRepliesResponse) GetReplies() []*ReplyInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

type DeleteReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteReplyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteReplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyResponse) Reset() {
	*x = DeleteReplyResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyResponse) ProtoMessage() {}

func (x *DeleteReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{13}
}

type LikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{14}
}

func (x *LikeCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResponse) Reset() {
	*x = LikeCommentResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResponse) ProtoMessage() {}

func (x *LikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResponse.ProtoReflect.Descriptor instead.
func (*LikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{15}
}

type UnlikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentRequest) Reset() {
	*x = UnlikeCommentRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentRequest) ProtoMessage() {}

func (x *UnlikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentRequest.ProtoReflect.Descriptor instead.
func (*UnlikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{16}
}

func (x *UnlikeCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *UnlikeCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentResponse) Reset() {
	*x = UnlikeCommentResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentResponse) ProtoMessage() {}

func (x *UnlikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentResponse.ProtoReflect.Descriptor instead.
func (*UnlikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{17}
}

type LikeReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReplyRequest) Reset() {
	*x = LikeReplyRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReplyRequest) ProtoMessage() {}

func (x *LikeReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReplyRequest.ProtoReflect.Descriptor instead.
func (*LikeReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{18}
}

func (x *LikeReplyRequest) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *LikeReplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikeReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReplyResponse) Reset() {
	*x = LikeReplyResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReplyResponse) ProtoMessage() {}

func (x *LikeReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReplyResponse.ProtoReflect.Descriptor instead.
func (*LikeReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{19}
}

type UnlikeReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReplyRequest) Reset() {
	*x = UnlikeReplyRequest{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReplyRequest) ProtoMessage() {}

func (x *UnlikeReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReplyRequest.ProtoReflect.Descriptor instead.
func (*UnlikeReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{20}
}

func (x *UnlikeReplyRequest) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *UnlikeReplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlikeReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReplyResponse) Reset() {
	*x = UnlikeReplyResponse{}
	mi := &file_proto_core_v1_comment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReplyResponse) ProtoMessage() {}

func (x *UnlikeReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_comment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReplyResponse.ProtoReflect.Descriptor instead.
func (*UnlikeReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_comment_proto_rawDescGZIP(), []int{21}
}

var File_proto_core_v1_comment_proto protoreflect.FileDescriptor

const file_proto_core_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/core/v1/comment.proto\x12\acore.v1\"\xf5\x02\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rmanuscript_id\x18\x02 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_avatar\x18\x05 \x01(\tR\n" +
	"userAvatar\x12\x1d\n" +
	"\n" +
	"user_level\x18\x06 \x01(\x05R\tuserLevel\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\x05R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\t \x01(\x05R\n" +
	"replyCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05liked\x18\v \x01(\bR\x05liked\x12,\n" +
	"\areplies\x18\f \x03(\v2\x12.core.v1.ReplyInfoR\areplies\"\xf4\x02\n" +
	"\tReplyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_avatar\x18\x05 \x01(\tR\n" +
	"userAvatar\x12\x1d\n" +
	"\n" +
	"user_level\x18\x06 \x01(\x05R\tuserLevel\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\x05R\tlikeCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12+\n" +
	"\x12reply_to_user_name\x18\n" +
	" \x01(\tR\x0freplyToUserName\x12\x14\n" +
	"\x05liked\x18\v \x01(\bR\x05liked\x12'\n" +
	"\x10reply_to_user_id\x18\f \x01(\x03R\rreplyToUserId\"k\n" +
	"\x11AddCommentRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"D\n" +
	"\x12AddCommentResponse\x12.\n" +
	"\acomment\x18\x01 \x01(\v2\x14.core.v1.CommentInfoR\acomment\"\x98\x01\n" +
	"\x13ListCommentsRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\"H\n" +
	"\x14ListCommentsResponse\x120\n" +
	"\bcomments\x18\x01 \x03(\v2\x14.core.v1.CommentInfoR\bcomments\"?\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x17\n" +
	"\x15DeleteCommentResponse\"\x8c\x01\n" +
	"\x0fAddReplyRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x10reply_to_user_id\x18\x04 \x01(\x03R\rreplyToUserId\"<\n" +
	"\x10AddReplyResponse\x12(\n" +
	"\x05reply\x18\x01 \x01(\v2\x12.core.v1.ReplyInfoR\x05reply\"|\n" +
	"\x11GetRepliesRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"B\n" +
	"\x12GetRepliesResponse\x12,\n" +
	"\areplies\x18\x01 \x03(\v2\x12.core.v1.ReplyInfoR\areplies\"=\n" +
	"\x12DeleteReplyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x15\n" +
	"\x13DeleteReplyResponse\"L\n" +
	"\x12LikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x15\n" +
	"\x13LikeCommentResponse\"N\n" +
	"\x14UnlikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x17\n" +
	"\x15UnlikeCommentResponse\"F\n" +
	"\x10LikeReplyRequest\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\x03R\areplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x13\n" +
	"\x11LikeReplyResponse\"H\n" +
	"\x12UnlikeReplyRequest\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\x03R\areplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x15\n" +
	"\x13UnlikeReplyResponse2\xee\x05\n" +
	"\x0eCommentService\x12E\n" +
	"\n" +
	"AddComment\x12\x1a.core.v1.AddCommentRequest\x1a\x1b.core.v1.AddCommentResponse\x12K\n" +
	"\fListComments\x12\x1c.core.v1.ListCommentsRequest\x1a\x1d.core.v1.ListCommentsResponse\x12N\n" +
	"\rDeleteComment\x12\x1d.core.v1.DeleteCommentRequest\x1a\x1e.core.v1.DeleteCommentResponse\x12?\n" +
	"\bAddReply\x12\x18.core.v1.AddReplyRequest\x1a\x19.core.v1.AddReplyResponse\x12E\n" +
	"\n" +
	"GetReplies\x12\x1a.core.v1.GetRepliesRequest\x1a\x1b.core.v1.GetRepliesResponse\x12H\n" +
	"\vDeleteReply\x12\x1b.core.v1.DeleteReplyRequest\x1a\x1c.core.v1.DeleteReplyResponse\x12H\n" +
	"\vLikeComment\x12\x1b.core.v1.LikeCommentRequest\x1a\x1c.core.v1.LikeCommentResponse\x12N\n" +
	"\rUnlikeComment\x12\x1d.core.v1.UnlikeCommentRequest\x1a\x1e.core.v1.UnlikeCommentResponse\x12B\n" +
	"\tLikeReply\x12\x19.core.v1.LikeReplyRequest\x1a\x1a.core.v1.LikeReplyResponse\x12H\n" +
	"\vUnlikeReply\x12\x1b.core.v1.UnlikeReplyRequest\x1a\x1c.core.v1.UnlikeReplyResponseB\x1dZ\x1bmybilibili/internal/core/pbb\x06proto3"

var (
	file_proto_core_v1_comment_proto_rawDescOnce sync.Once
	file_proto_core_v1_comment_proto_rawDescData []byte
)

func file_proto_core_v1_comment_proto_rawDescGZIP() []byte {
	file_proto_core_v1_comment_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_comment_proto_rawDesc), len(file_proto_core_v1_comment_proto_rawDesc)))
	})
	return file_proto_core_v1_comment_proto_rawDescData
}

var file_proto_core_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_core_v1_comment_proto_goTypes = []any{
	(*CommentInfo)(nil),           // 0: core.v1.CommentInfo
	(*ReplyInfo)(nil),             // 1: core.v1.ReplyInfo
	(*AddCommentRequest)(nil),     // 2: core.v1.AddCommentRequest
	(*AddCommentResponse)(nil),    // 3: core.v1.AddCommentResponse
	(*ListCommentsRequest)(nil),   // 4: core.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),  // 5: core.v1.ListCommentsResponse
	(*DeleteCommentRequest)(nil),  // 6: core.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil), // 7: core.v1.DeleteCommentResponse
	(*AddReplyRequest)(nil),       // 8: core.v1.AddReplyRequest
	(*AddReplyResponse)(nil),      // 9: core.v1.AddReplyResponse
	(*GetRepliesRequest)(nil),     // 10: core.v1.GetRepliesRequest
	(*GetRepliesResponse)(nil),    // 11: core.v1.GetRepliesResponse
	(*DeleteReplyRequest)(nil),    // 12: core.v1.DeleteReplyRequest
	(*DeleteReplyResponse)(nil),   // 13: core.v1.DeleteReplyResponse
	(*LikeCommentRequest)(nil),    // 14: core.v1.LikeCommentRequest
	(*LikeCommentResponse)(nil),   // 15: core.v1.LikeCommentResponse
	(*UnlikeCommentRequest)(nil),  // 16: core.v1.UnlikeCommentRequest
	(*UnlikeCommentResponse)(nil), // 17: core.v1.UnlikeCommentResponse
	(*LikeReplyRequest)(nil),      // 18: core.v1.LikeReplyRequest
	(*LikeReplyResponse)(nil),     // 19: core.v1.LikeReplyResponse
	(*UnlikeReplyRequest)(nil),    // 20: core.v1.UnlikeReplyRequest
	(*UnlikeReplyResponse)(nil),   // 21: core.v1.UnlikeReplyResponse
}
var file_proto_core_v1_comment_proto_depIdxs = []int32{
	1,  // 0: core.v1.CommentInfo.replies:type_name -> core.v1.ReplyInfo
	0,  // 1: core.v1.AddCommentResponse.comment:type_name -> core.v1.CommentInfo
	0,  // 2: core.v1.ListCommentsResponse.comments:type_name -> core.v1.CommentInfo
	1,  // 3: core.v1.AddReplyResponse.reply:type_name -> core.v1.ReplyInfo
	1,  // 4: core.v1.GetRepliesResponse.replies:type_name -> core.v1.ReplyInfo
	2,  // 5: core.v1.CommentService.AddComment:input_type -> core.v1.AddCommentRequest
	4,  // 6: core.v1.CommentService.ListComments:input_type -> core.v1.ListCommentsRequest
	6,  // 7: core.v1.CommentService.DeleteComment:input_type -> core.v1.DeleteCommentRequest
	8,  // 8: core.v1.CommentService.AddReply:input_type -> core.v1.AddReplyRequest
	10, // 9: core.v1.CommentService.GetReplies:input_type -> core.v1.GetRepliesRequest
	12, // 10: core.v1.CommentService.DeleteReply:input_type -> core.v1.DeleteReplyRequest
	14, // 11: core.v1.CommentService.LikeComment:input_type -> core.v1.LikeCommentRequest
	16, // 12: core.v1.CommentService.UnlikeComment:input_type -> core.v1.UnlikeCommentRequest
	18, // 13: core.v1.CommentService.LikeReply:input_type -> core.v1.LikeReplyRequest
	20, // 14: core.v1.CommentService.UnlikeReply:input_type -> core.v1.UnlikeReplyRequest
	3,  // 15: core.v1.CommentService.AddComment:output_type -> core.v1.AddCommentResponse
	5,  // 16: core.v1.CommentService.ListComments:output_type -> core.v1.ListCommentsResponse
	7,  // 17: core.v1.CommentService.DeleteComment:output_type -> core.v1.DeleteCommentResponse
	9,  // 18: core.v1.CommentService.AddReply:output_type -> core.v1.AddReplyResponse
	11, // 19: core.v1.CommentService.GetReplies:output_type -> core.v1.GetRepliesResponse
	13, // 20: core.v1.CommentService.DeleteReply:output_type -> core.v1.DeleteReplyResponse
	15, // 21: core.v1.CommentService.LikeComment:output_type -> core.v1.LikeCommentResponse
	17, // 22: core.v1.CommentService.UnlikeComment:output_type -> core.v1.UnlikeCommentResponse
	19, // 23: core.v1.CommentService.LikeReply:output_type -> core.v1.LikeReplyResponse
	21, // 24: core.v1.CommentService.UnlikeReply:output_type -> core.v1.UnlikeReplyResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_core_v1_comment_proto_init() }
func file_proto_core_v1_comment_proto_init() {
	if File_proto_core_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_comment_proto_rawDesc), len(file_proto_core_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_comment_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_comment_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_comment_proto_msgTypes,
	}.Build()
	File_proto_core_v1_comment_proto = out.File
	file_proto_core_v1_comment_proto_goTypes = nil
	file_proto_core_v1_comment_proto_depIdxs = nil
}
