// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/core/v1/manuscript.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManuscriptInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl          string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	UserId            int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId        int64                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName      string                 `protobuf:"bytes,7,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	ViewCount         int64                  `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount         int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CoinCount         int64                  `protobuf:"varint,10,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`
	CollectCount      int64                  `protobuf:"varint,11,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	ShareCount        int64                  `protobuf:"varint,12,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	CommentCount      int64                  `protobuf:"varint,13,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	DanmakuCount      int64                  `protobuf:"varint,14,opt,name=danmaku_count,json=danmakuCount,proto3" json:"danmaku_count,omitempty"`
	Duration          string                 `protobuf:"bytes,15,opt,name=duration,proto3" json:"duration,omitempty"`
	DurationSeconds   int32                  `protobuf:"varint,16,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Status            int32                  `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	ReviewStatus      int32                  `protobuf:"varint,18,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`
	ReviewReason      string                 `protobuf:"bytes,19,opt,name=review_reason,json=reviewReason,proto3" json:"review_reason,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Uploader          *UserInfo              `protobuf:"bytes,22,opt,name=uploader,proto3" json:"uploader,omitempty"`
	Tags              []string               `protobuf:"bytes,23,rep,name=tags,proto3" json:"tags,omitempty"`
	FirstVideoId      int64                  `protobuf:"varint,24,opt,name=first_video_id,json=firstVideoId,proto3" json:"first_video_id,omitempty"`
	FirstVideoPlayUrl string                 `protobuf:"bytes,25,opt,name=first_video_play_url,json=firstVideoPlayUrl,proto3" json:"first_video_play_url,omitempty"`
	Videos            []*VideoItem           `protobuf:"bytes,26,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ManuscriptInfo) Reset() {
	*x = ManuscriptInfo{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManuscriptInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManuscriptInfo) ProtoMessage() {}

func (x *ManuscriptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManuscriptInfo.ProtoReflect.Descriptor instead.
func (*ManuscriptInfo) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{0}
}

func (x *ManuscriptInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManuscriptInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ManuscriptInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ManuscriptInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *ManuscriptInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ManuscriptInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ManuscriptInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ManuscriptInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ManuscriptInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ManuscriptInfo) GetCoinCount() int64 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

func (x *ManuscriptInfo) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *ManuscriptInfo) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *ManuscriptInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ManuscriptInfo) GetDanmakuCount() int64 {
	if x != nil {
		return x.DanmakuCount
	}
	return 0
}

func (x *ManuscriptInfo) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *ManuscriptInfo) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ManuscriptInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManuscriptInfo) GetReviewStatus() int32 {
	if x != nil {
		return x.ReviewStatus
	}
	return 0
}

func (x *ManuscriptInfo) GetReviewReason() string {
	if x != nil {
		return x.ReviewReason
	}
	return ""
}

func (x *ManuscriptInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ManuscriptInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ManuscriptInfo) GetUploader() *UserInfo {
	if x != nil {
		return x.Uploader
	}
	return nil
}

func (x *ManuscriptInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ManuscriptInfo) GetFirstVideoId() int64 {
	if x != nil {
		return x.FirstVideoId
	}
	return 0
}

func (x *ManuscriptInfo) GetFirstVideoPlayUrl() string {
	if x != nil {
		return x.FirstVideoPlayUrl
	}
	return ""
}

func (x *ManuscriptInfo) GetVideos() []*VideoItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VideoItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PlayUrl         string                 `protobuf:"bytes,4,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	PlayUrlHd       string                 `protobuf:"bytes,5,opt,name=play_url_hd,json=playUrlHd,proto3" json:"play_url_hd,omitempty"`
	PlayUrlSd       string                 `protobuf:"bytes,6,opt,name=play_url_sd,json=playUrlSd,proto3" json:"play_url_sd,omitempty"`
	PlayUrlLd       string                 `protobuf:"bytes,7,opt,name=play_url_ld,json=playUrlLd,proto3" json:"play_url_ld,omitempty"`
	Duration        string                 `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	VideoOrder      int32                  `protobuf:"varint,10,opt,name=video_order,json=videoOrder,proto3" json:"video_order,omitempty"`
	Status          int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	ProcessStatus   int32                  `protobuf:"varint,12,opt,name=process_status,json=processStatus,proto3" json:"process_status,omitempty"`
	ProcessProgress int32                  `protobuf:"varint,13,opt,name=process_progress,json=processProgress,proto3" json:"process_progress,omitempty"`
	ProcessStage    string                 `protobuf:"bytes,14,opt,name=process_stage,json=processStage,proto3" json:"process_stage,omitempty"`
	ProcessError    string                 `protobuf:"bytes,15,opt,name=process_error,json=processError,proto3" json:"process_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoItem) Reset() {
	*x = VideoItem{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoItem) ProtoMessage() {}

func (x *VideoItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoItem.ProtoReflect.Descriptor instead.
func (*VideoItem) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{1}
}

func (x *VideoItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoItem) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *VideoItem) GetPlayUrlHd() string {
	if x != nil {
		return x.PlayUrlHd
	}
	return ""
}

func (x *VideoItem) GetPlayUrlSd() string {
	if x != nil {
		return x.PlayUrlSd
	}
	return ""
}

func (x *VideoItem) GetPlayUrlLd() string {
	if x != nil {
		return x.PlayUrlLd
	}
	return ""
}

func (x *VideoItem) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *VideoItem) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *VideoItem) GetVideoOrder() int32 {
	if x != nil {
		return x.VideoOrder
	}
	return 0
}

func (x *VideoItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoItem) GetProcessStatus() int32 {
	if x != nil {
		return x.ProcessStatus
	}
	return 0
}

func (x *VideoItem) GetProcessProgress() int32 {
	if x != nil {
		return x.ProcessProgress
	}
	return 0
}

func (x *VideoItem) GetProcessStage() string {
	if x != nil {
		return x.ProcessStage
	}
	return ""
}

func (x *VideoItem) GetProcessError() string {
	if x != nil {
		return x.ProcessError
	}
	return ""
}

type UserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Bio            string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Signature      string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	FollowerCount  int32                  `protobuf:"varint,7,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount int32                  `protobuf:"varint,8,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	LikedCount     int32                  `protobuf:"varint,9,opt,name=liked_count,json=likedCount,proto3" json:"liked_count,omitempty"`
	Following      bool                   `protobuf:"varint,10,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserInfo) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *UserInfo) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *UserInfo) GetLikedCount() int32 {
	if x != nil {
		return x.LikedCount
	}
	return 0
}

func (x *UserInfo) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type GetManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManuscriptRequest) Reset() {
	*x = GetManuscriptRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManuscriptRequest) ProtoMessage() {}

func (x *GetManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManuscriptRequest.ProtoReflect.Descriptor instead.
func (*GetManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{3}
}

func (x *GetManuscriptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetManuscriptWithVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentUserId int64                  `protobuf:"varint,2,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManuscriptWithVideosRequest) Reset() {
	*x = GetManuscriptWithVideosRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManuscriptWithVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManuscriptWithVideosRequest) ProtoMessage() {}

func (x *GetManuscriptWithVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManuscriptWithVideosRequest.ProtoReflect.Descriptor instead.
func (*GetManuscriptWithVideosRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{4}
}

func (x *GetManuscriptWithVideosRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetManuscriptWithVideosRequest) GetCurrentUserId() int64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

type GetManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscript    *ManuscriptInfo        `protobuf:"bytes,1,opt,name=manuscript,proto3" json:"manuscript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManuscriptResponse) Reset() {
	*x = GetManuscriptResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManuscriptResponse) ProtoMessage() {}

func (x *GetManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManuscriptResponse.ProtoReflect.Descriptor instead.
func (*GetManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{5}
}

func (x *GetManuscriptResponse) GetManuscript() *ManuscriptInfo {
	if x != nil {
		return x.Manuscript
	}
	return nil
}

type ListUserManuscriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserManuscriptsRequest) Reset() {
	*x = ListUserManuscriptsRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserManuscriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserManuscriptsRequest) ProtoMessage() {}

func (x *ListUserManuscriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserManuscriptsRequest.ProtoReflect.Descriptor instead.
func (*ListUserManuscriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserManuscriptsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserManuscriptsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListUserManuscriptsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserManuscriptsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserManuscriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscripts   []*ManuscriptInfo      `protobuf:"bytes,1,rep,name=manuscripts,proto3" json:"manuscripts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserManuscriptsResponse) Reset() {
	*x = ListUserManuscriptsResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserManuscriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserManuscriptsResponse) ProtoMessage() {}

func (x *ListUserManuscriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserManuscriptsResponse.ProtoReflect.Descriptor instead.
func (*ListUserManuscriptsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserManuscriptsResponse) GetManuscripts() []*ManuscriptInfo {
	if x != nil {
		return x.Manuscripts
	}
	return nil
}

func (x *ListUserManuscriptsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserManuscriptsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserManuscriptsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRecommendedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendedRequest) Reset() {
	*x = ListRecommendedRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendedRequest) ProtoMessage() {}

func (x *ListRecommendedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendedRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendedRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{8}
}

func (x *ListRecommendedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListRecommendedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscripts   []*ManuscriptInfo      `protobuf:"bytes,1,rep,name=manuscripts,proto3" json:"manuscripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendedResponse) Reset() {
	*x = ListRecommendedResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendedResponse) ProtoMessage() {}

func (x *ListRecommendedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendedResponse.ProtoReflect.Descriptor instead.
func (*ListRecommendedResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{9}
}

func (x *ListRecommendedResponse) GetManuscripts() []*ManuscriptInfo {
	if x != nil {
		return x.Manuscripts
	}
	return nil
}

type ListHotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotRequest) Reset() {
	*x = ListHotRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotRequest) ProtoMessage() {}

func (x *ListHotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotRequest.ProtoReflect.Descriptor instead.
func (*ListHotRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{10}
}

func (x *ListHotRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListHotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscripts   []*ManuscriptInfo      `protobuf:"bytes,1,rep,name=manuscripts,proto3" json:"manuscripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotResponse) Reset() {
	*x = ListHotResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotResponse) ProtoMessage() {}

func (x *ListHotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotResponse.ProtoReflect.Descriptor instead.
func (*ListHotResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{11}
}

func (x *ListHotResponse) GetManuscripts() []*ManuscriptInfo {
	if x != nil {
		return x.Manuscripts
	}
	return nil
}

type ListByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByCategoryRequest) Reset() {
	*x = ListByCategoryRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByCategoryRequest) ProtoMessage() {}

func (x *ListByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{12}
}

func (x *ListByCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListByCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListByCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscripts   []*ManuscriptInfo      `protobuf:"bytes,1,rep,name=manuscripts,proto3" json:"manuscripts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByCategoryResponse) Reset() {
	*x = ListByCategoryResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByCategoryResponse) ProtoMessage() {}

func (x *ListByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByCategoryResponse.ProtoReflect.Descriptor instead.
func (*ListByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{13}
}

func (x *ListByCategoryResponse) GetManuscripts() []*ManuscriptInfo {
	if x != nil {
		return x.Manuscripts
	}
	return nil
}

func (x *ListByCategoryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{14}
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryInfo        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{16}
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryInfo {
	if x != nil {
		return x.Categories
	}
	return nil
}

type DeleteManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManuscriptRequest) Reset() {
	*x = DeleteManuscriptRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManuscriptRequest) ProtoMessage() {}

func (x *DeleteManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManuscriptRequest.ProtoReflect.Descriptor instead.
func (*DeleteManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteManuscriptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManuscriptResponse) Reset() {
	*x = DeleteManuscriptResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManuscriptResponse) ProtoMessage() {}

func (x *DeleteManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManuscriptResponse.ProtoReflect.Descriptor instead.
func (*DeleteManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{18}
}

type UpdateManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Videos        []*UpdateVideoItem     `protobuf:"bytes,7,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManuscriptRequest) Reset() {
	*x = UpdateManuscriptRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManuscriptRequest) ProtoMessage() {}

func (x *UpdateManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManuscriptRequest.ProtoReflect.Descriptor instead.
func (*UpdateManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateManuscriptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateManuscriptRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateManuscriptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateManuscriptRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateManuscriptRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateManuscriptRequest) GetVideos() []*UpdateVideoItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

type UpdateVideoItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	VideoOrder      int32                  `protobuf:"varint,3,opt,name=video_order,json=videoOrder,proto3" json:"video_order,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateVideoItem) Reset() {
	*x = UpdateVideoItem{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoItem) ProtoMessage() {}

func (x *UpdateVideoItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoItem.ProtoReflect.Descriptor instead.
func (*UpdateVideoItem) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateVideoItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVideoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoItem) GetVideoOrder() int32 {
	if x != nil {
		return x.VideoOrder
	}
	return 0
}

func (x *UpdateVideoItem) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type UpdateManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscript    *ManuscriptInfo        `protobuf:"bytes,1,opt,name=manuscript,proto3" json:"manuscript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManuscriptResponse) Reset() {
	*x = UpdateManuscriptResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManuscriptResponse) ProtoMessage() {}

func (x *UpdateManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManuscriptResponse.ProtoReflect.Descriptor instead.
func (*UpdateManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateManuscriptResponse) GetManuscript() *ManuscriptInfo {
	if x != nil {
		return x.Manuscript
	}
	return nil
}

type PublishManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishManuscriptRequest) Reset() {
	*x = PublishManuscriptRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishManuscriptRequest) ProtoMessage() {}

func (x *PublishManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishManuscriptRequest.ProtoReflect.Descriptor instead.
func (*PublishManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{22}
}

func (x *PublishManuscriptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PublishManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishManuscriptResponse) Reset() {
	*x = PublishManuscriptResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishManuscriptResponse) ProtoMessage() {}

func (x *PublishManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishManuscriptResponse.ProtoReflect.Descriptor instead.
func (*PublishManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{23}
}

type UnpublishManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishManuscriptRequest) Reset() {
	*x = UnpublishManuscriptRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishManuscriptRequest) ProtoMessage() {}

func (x *UnpublishManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishManuscriptRequest.ProtoReflect.Descriptor instead.
func (*UnpublishManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{24}
}

func (x *UnpublishManuscriptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnpublishManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnpublishManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishManuscriptResponse) Reset() {
	*x = UnpublishManuscriptResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishManuscriptResponse) ProtoMessage() {}

func (x *UnpublishManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishManuscriptResponse.ProtoReflect.Descriptor instead.
func (*UnpublishManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{25}
}

type SearchUserManuscriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserManuscriptsRequest) Reset() {
	*x = SearchUserManuscriptsRequest{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserManuscriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserManuscriptsRequest) ProtoMessage() {}

func (x *SearchUserManuscriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserManuscriptsRequest.ProtoReflect.Descriptor instead.
func (*SearchUserManuscriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{26}
}

func (x *SearchUserManuscriptsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchUserManuscriptsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUserManuscriptsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type SearchUserManuscriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manuscripts   []*ManuscriptInfo      `protobuf:"bytes,1,rep,name=manuscripts,proto3" json:"manuscripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserManuscriptsResponse) Reset() {
	*x = SearchUserManuscriptsResponse{}
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserManuscriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserManuscriptsResponse) ProtoMessage() {}

func (x *SearchUserManuscriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_manuscript_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserManuscriptsResponse.ProtoReflect.Descriptor instead.
func (*SearchUserManuscriptsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_manuscript_proto_rawDescGZIP(), []int{27}
}

func (x *SearchUserManuscriptsResponse) GetManuscripts() []*ManuscriptInfo {
	if x != nil {
		return x.Manuscripts
	}
	return nil
}

var File_proto_core_v1_manuscript_proto protoreflect.FileDescriptor

const file_proto_core_v1_manuscript_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/core/v1/manuscript.proto\x12\acore.v1\"\xee\x06\n" +
	"\x0eManuscriptInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\a \x01(\tR\fcategoryName\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"coin_count\x18\n" +
	" \x01(\x03R\tcoinCount\x12#\n" +
	"\rcollect_count\x18\v \x01(\x03R\fcollectCount\x12\x1f\n" +
	"\vshare_count\x18\f \x01(\x03R\n" +
	"shareCount\x12#\n" +
	"\rcomment_count\x18\r \x01(\x03R\fcommentCount\x12#\n" +
	"\rdanmaku_count\x18\x0e \x01(\x03R\fdanmakuCount\x12\x1a\n" +
	"\bduration\x18\x0f \x01(\tR\bduration\x12)\n" +
	"\x10duration_seconds\x18\x10 \x01(\x05R\x0fdurationSeconds\x12\x16\n" +
	"\x06status\x18\x11 \x01(\x05R\x06status\x12#\n" +
	"\rreview_status\x18\x12 \x01(\x05R\freviewStatus\x12#\n" +
	"\rreview_reason\x18\x13 \x01(\tR\freviewReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\tR\tupdatedAt\x12-\n" +
	"\buploader\x18\x16 \x01(\v2\x11.core.v1.UserInfoR\buploader\x12\x12\n" +
	"\x04tags\x18\x17 \x03(\tR\x04tags\x12$\n" +
	"\x0efirst_video_id\x18\x18 \x01(\x03R\ffirstVideoId\x12/\n" +
	"\x14first_video_play_url\x18\x19 \x01(\tR\x11firstVideoPlayUrl\x12*\n" +
	"\x06videos\x18\x1a \x03(\v2\x12.core.v1.VideoItemR\x06videos\"\xea\x03\n" +
	"\tVideoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bplay_url\x18\x04 \x01(\tR\aplayUrl\x12\x1e\n" +
	"\vplay_url_hd\x18\x05 \x01(\tR\tplayUrlHd\x12\x1e\n" +
	"\vplay_url_sd\x18\x06 \x01(\tR\tplayUrlSd\x12\x1e\n" +
	"\vplay_url_ld\x18\a \x01(\tR\tplayUrlLd\x12\x1a\n" +
	"\bduration\x18\b \x01(\tR\bduration\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x05R\x0fdurationSeconds\x12\x1f\n" +
	"\vvideo_order\x18\n" +
	" \x01(\x05R\n" +
	"videoOrder\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12%\n" +
	"\x0eprocess_status\x18\f \x01(\x05R\rprocessStatus\x12)\n" +
	"\x10process_progress\x18\r \x01(\x05R\x0fprocessProgress\x12#\n" +
	"\rprocess_stage\x18\x0e \x01(\tR\fprocessStage\x12#\n" +
	"\rprocess_error\x18\x0f \x01(\tR\fprocessError\"\x9b\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12%\n" +
	"\x0efollower_count\x18\a \x01(\x05R\rfollowerCount\x12'\n" +
	"\x0ffollowing_count\x18\b \x01(\x05R\x0efollowingCount\x12\x1f\n" +
	"\vliked_count\x18\t \x01(\x05R\n" +
	"likedCount\x12\x1c\n" +
	"\tfollowing\x18\n" +
	" \x01(\bR\tfollowing\"&\n" +
	"\x14GetManuscriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"X\n" +
	"\x1eGetManuscriptWithVideosRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0fcurrent_user_id\x18\x02 \x01(\x03R\rcurrentUserId\"P\n" +
	"\x15GetManuscriptResponse\x127\n" +
	"\n" +
	"manuscript\x18\x01 \x01(\v2\x17.core.v1.ManuscriptInfoR\n" +
	"manuscript\"~\n" +
	"\x1aListUserManuscriptsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x9f\x01\n" +
	"\x1bListUserManuscriptsResponse\x129\n" +
	"\vmanuscripts\x18\x01 \x03(\v2\x17.core.v1.ManuscriptInfoR\vmanuscripts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"1\n" +
	"\x16ListRecommendedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"T\n" +
	"\x17ListRecommendedResponse\x129\n" +
	"\vmanuscripts\x18\x01 \x03(\v2\x17.core.v1.ManuscriptInfoR\vmanuscripts\")\n" +
	"\x0eListHotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"L\n" +
	"\x0fListHotResponse\x129\n" +
	"\vmanuscripts\x18\x01 \x03(\v2\x17.core.v1.ManuscriptInfoR\vmanuscripts\"i\n" +
	"\x15ListByCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"i\n" +
	"\x16ListByCategoryResponse\x129\n" +
	"\vmanuscripts\x18\x01 \x03(\v2\x17.core.v1.ManuscriptInfoR\vmanuscripts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x17\n" +
	"\x15ListCategoriesRequest\"e\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"O\n" +
	"\x16ListCategoriesResponse\x125\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x15.core.v1.CategoryInfoR\n" +
	"categories\"B\n" +
	"\x17DeleteManuscriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x1a\n" +
	"\x18DeleteManuscriptResponse\"\xe1\x01\n" +
	"\x17UpdateManuscriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x120\n" +
	"\x06videos\x18\a \x03(\v2\x18.core.v1.UpdateVideoItemR\x06videos\"\x83\x01\n" +
	"\x0fUpdateVideoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vvideo_order\x18\x03 \x01(\x05R\n" +
	"videoOrder\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\"S\n" +
	"\x18UpdateManuscriptResponse\x127\n" +
	"\n" +
	"manuscript\x18\x01 \x01(\v2\x17.core.v1.ManuscriptInfoR\n" +
	"manuscript\"C\n" +
	"\x18PublishManuscriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x1b\n" +
	"\x19PublishManuscriptResponse\"E\n" +
	"\x1aUnpublishManuscriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x1d\n" +
	"\x1bUnpublishManuscriptResponse\"e\n" +
	"\x1cSearchUserManuscriptsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\"Z\n" +
	"\x1dSearchUserManuscriptsResponse\x129\n" +
	"\vmanuscripts\x18\x01 \x03(\v2\x17.core.v1.ManuscriptInfoR\vmanuscripts2\xbb\b\n" +
	"\x11ManuscriptService\x12N\n" +
	"\rGetManuscript\x12\x1d.core.v1.GetManuscriptRequest\x1a\x1e.core.v1.GetManuscriptResponse\x12b\n" +
	"\x17GetManuscriptWithVideos\x12'.core.v1.GetManuscriptWithVideosRequest\x1a\x1e.core.v1.GetManuscriptResponse\x12`\n" +
	"\x13ListUserManuscripts\x12#.core.v1.ListUserManuscriptsRequest\x1a$.core.v1.ListUserManuscriptsResponse\x12T\n" +
	"\x0fListRecommended\x12\x1f.core.v1.ListRecommendedRequest\x1a .core.v1.ListRecommendedResponse\x12<\n" +
	"\aListHot\x12\x17.core.v1.ListHotRequest\x1a\x18.core.v1.ListHotResponse\x12Q\n" +
	"\x0eListByCategory\x12\x1e.core.v1.ListByCategoryRequest\x1a\x1f.core.v1.ListByCategoryResponse\x12Q\n" +
	"\x0eListCategories\x12\x1e.core.v1.ListCategoriesRequest\x1a\x1f.core.v1.ListCategoriesResponse\x12W\n" +
	"\x10DeleteManuscript\x12 .core.v1.DeleteManuscriptRequest\x1a!.core.v1.DeleteManuscriptResponse\x12W\n" +
	"\x10UpdateManuscript\x12 .core.v1.UpdateManuscriptRequest\x1a!.core.v1.UpdateManuscriptResponse\x12Z\n" +
	"\x11PublishManuscript\x12!.core.v1.PublishManuscriptRequest\x1a\".core.v1.PublishManuscriptResponse\x12`\n" +
	"\x13UnpublishManuscript\x12#.core.v1.UnpublishManuscriptRequest\x1a$.core.v1.UnpublishManuscriptResponse\x12f\n" +
	"\x15SearchUserManuscripts\x12%.core.v1.SearchUserManuscriptsRequest\x1a&.core.v1.SearchUserManuscriptsResponseB\x1dZ\x1bmybilibili/internal/core/pbb\x06proto3"

var (
	file_proto_core_v1_manuscript_proto_rawDescOnce sync.Once
	file_proto_core_v1_manuscript_proto_rawDescData []byte
)

func file_proto_core_v1_manuscript_proto_rawDescGZIP() []byte {
	file_proto_core_v1_manuscript_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_manuscript_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_manuscript_proto_rawDesc), len(file_proto_core_v1_manuscript_proto_rawDesc)))
	})
	return file_proto_core_v1_manuscript_proto_rawDescData
}

var file_proto_core_v1_manuscript_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_core_v1_manuscript_proto_goTypes = []any{
	(*ManuscriptInfo)(nil),                 // 0: core.v1.ManuscriptInfo
	(*VideoItem)(nil),                      // 1: core.v1.VideoItem
	(*UserInfo)(nil),                       // 2: core.v1.UserInfo
	(*GetManuscriptRequest)(nil),           // 3: core.v1.GetManuscriptRequest
	(*GetManuscriptWithVideosRequest)(nil), // 4: core.v1.GetManuscriptWithVideosRequest
	(*GetManuscriptResponse)(nil),          // 5: core.v1.GetManuscriptResponse
	(*ListUserManuscriptsRequest)(nil),     // 6: core.v1.ListUserManuscriptsRequest
	(*ListUserManuscriptsResponse)(nil),    // 7: core.v1.ListUserManuscriptsResponse
	(*ListRecommendedRequest)(nil),         // 8: core.v1.ListRecommendedRequest
	(*ListRecommendedResponse)(nil),        // 9: core.v1.ListRecommendedResponse
	(*ListHotRequest)(nil),                 // 10: core.v1.ListHotRequest
	(*ListHotResponse)(nil),                // 11: core.v1.ListHotResponse
	(*ListByCategoryRequest)(nil),          // 12: core.v1.ListByCategoryRequest
	(*ListByCategoryResponse)(nil),         // 13: core.v1.ListByCategoryResponse
	(*ListCategoriesRequest)(nil),          // 14: core.v1.ListCategoriesRequest
	(*CategoryInfo)(nil),                   // 15: core.v1.CategoryInfo
	(*ListCategoriesResponse)(nil),         // 16: core.v1.ListCategoriesResponse
	(*DeleteManuscriptRequest)(nil),        // 17: core.v1.DeleteManuscriptRequest
	(*DeleteManuscriptResponse)(nil),       // 18: core.v1.DeleteManuscriptResponse
	(*UpdateManuscriptRequest)(nil),        // 19: core.v1.UpdateManuscriptRequest
	(*UpdateVideoItem)(nil),                // 20: core.v1.UpdateVideoItem
	(*UpdateManuscriptResponse)(nil),       // 21: core.v1.UpdateManuscriptResponse
	(*PublishManuscriptRequest)(nil),       // 22: core.v1.PublishManuscriptRequest
	(*PublishManuscriptResponse)(nil),      // 23: core.v1.PublishManuscriptResponse
	(*UnpublishManuscriptRequest)(nil),     // 24: core.v1.UnpublishManuscriptRequest
	(*UnpublishManuscriptResponse)(nil),    // 25: core.v1.UnpublishManuscriptResponse
	(*SearchUserManuscriptsRequest)(nil),   // 26: core.v1.SearchUserManuscriptsRequest
	(*SearchUserManuscriptsResponse)(nil),  // 27: core.v1.SearchUserManuscriptsResponse
}
var file_proto_core_v1_manuscript_proto_depIdxs = []int32{
	2,  // 0: core.v1.ManuscriptInfo.uploader:type_name -> core.v1.UserInfo
	1,  // 1: core.v1.ManuscriptInfo.videos:type_name -> core.v1.VideoItem
	0,  // 2: core.v1.GetManuscriptResponse.manuscript:type_name -> core.v1.ManuscriptInfo
	0,  // 3: core.v1.ListUserManuscriptsResponse.manuscripts:type_name -> core.v1.ManuscriptInfo
	0,  // 4: core.v1.ListRecommendedResponse.manuscripts:type_name -> core.v1.ManuscriptInfo
	0,  // 5: core.v1.ListHotResponse.manuscripts:type_name -> core.v1.ManuscriptInfo
	0,  // 6: core.v1.ListByCategoryResponse.manuscripts:type_name -> core.v1.ManuscriptInfo
	15, // 7: core.v1.ListCategoriesResponse.categories:type_name -> core.v1.CategoryInfo
	20, // 8: core.v1.UpdateManuscriptRequest.videos:type_name -> core.v1.UpdateVideoItem
	0,  // 9: core.v1.UpdateManuscriptResponse.manuscript:type_name -> core.v1.ManuscriptInfo
	0,  // 10: core.v1.SearchUserManuscriptsResponse.manuscripts:type_name -> core.v1.ManuscriptInfo
	3,  // 11: core.v1.ManuscriptService.GetManuscript:input_type -> core.v1.GetManuscriptRequest
	4,  // 12: core.v1.ManuscriptService.GetManuscriptWithVideos:input_type -> core.v1.GetManuscriptWithVideosRequest
	6,  // 13: core.v1.ManuscriptService.ListUserManuscripts:input_type -> core.v1.ListUserManuscriptsRequest
	8,  // 14: core.v1.ManuscriptService.ListRecommended:input_type -> core.v1.ListRecommendedRequest
	10, // 15: core.v1.ManuscriptService.ListHot:input_type -> core.v1.ListHotRequest
	12, // 16: core.v1.ManuscriptService.ListByCategory:input_type -> core.v1.ListByCategoryRequest
	14, // 17: core.v1.ManuscriptService.ListCategories:input_type -> core.v1.ListCategoriesRequest
	17, // 18: core.v1.ManuscriptService.DeleteManuscript:input_type -> core.v1.DeleteManuscriptRequest
	19, // 19: core.v1.ManuscriptService.UpdateManuscript:input_type -> core.v1.UpdateManuscriptRequest
	22, // 20: core.v1.ManuscriptService.PublishManuscript:input_type -> core.v1.PublishManuscriptRequest
	24, // 21: core.v1.ManuscriptService.UnpublishManuscript:input_type -> core.v1.UnpublishManuscriptRequest
	26, // 22: core.v1.ManuscriptService.SearchUserManuscripts:input_type -> core.v1.SearchUserManuscriptsRequest
	5,  // 23: core.v1.ManuscriptService.GetManuscript:output_type -> core.v1.GetManuscriptResponse
	5,  // 24: core.v1.ManuscriptService.GetManuscriptWithVideos:output_type -> core.v1.GetManuscriptResponse
	7,  // 25: core.v1.ManuscriptService.ListUserManuscripts:output_type -> core.v1.ListUserManuscriptsResponse
	9,  // 26: core.v1.ManuscriptService.ListRecommended:output_type -> core.v1.ListRecommendedResponse
	11, // 27: core.v1.ManuscriptService.ListHot:output_type -> core.v1.ListHotResponse
	13, // 28: core.v1.ManuscriptService.ListByCategory:output_type -> core.v1.ListByCategoryResponse
	16, // 29: core.v1.ManuscriptService.ListCategories:output_type -> core.v1.ListCategoriesResponse
	18, // 30: core.v1.ManuscriptService.DeleteManuscript:output_type -> core.v1.DeleteManuscriptResponse
	21, // 31: core.v1.ManuscriptService.UpdateManuscript:output_type -> core.v1.UpdateManuscriptResponse
	23, // 32: core.v1.ManuscriptService.PublishManuscript:output_type -> core.v1.PublishManuscriptResponse
	25, // 33: core.v1.ManuscriptService.UnpublishManuscript:output_type -> core.v1.UnpublishManuscriptResponse
	27, // 34: core.v1.ManuscriptService.SearchUserManuscripts:output_type -> core.v1.SearchUserManuscriptsResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_core_v1_manuscript_proto_init() }
func file_proto_core_v1_manuscript_proto_init() {
	if File_proto_core_v1_manuscript_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_manuscript_proto_rawDesc), len(file_proto_core_v1_manuscript_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_manuscript_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_manuscript_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_manuscript_proto_msgTypes,
	}.Build()
	File_proto_core_v1_manuscript_proto = out.File
	file_proto_core_v1_manuscript_proto_goTypes = nil
	file_proto_core_v1_manuscript_proto_depIdxs = nil
}
