// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: core/v1/msg_danmaku.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   int32                  `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_core_v1_msg_danmaku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_msg_danmaku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_msg_danmaku_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_core_v1_msg_danmaku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_msg_danmaku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_msg_danmaku_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_core_v1_msg_danmaku_proto protoreflect.FileDescriptor

const file_core_v1_msg_danmaku_proto_rawDesc = "" +
	"\n" +
	"\x19core/v1/msg_danmaku.proto\x12\acore.v1\"\x8f\x01\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\x05R\vmessageType\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId2]\n" +
	"\x11MsgDanmakuService\x12H\n" +
	"\vSendMessage\x12\x1b.core.v1.SendMessageRequest\x1a\x1c.core.v1.SendMessageResponseB\x13Z\x11mybilibili/pkg/pbb\x06proto3"

var (
	file_core_v1_msg_danmaku_proto_rawDescOnce sync.Once
	file_core_v1_msg_danmaku_proto_rawDescData []byte
)

func file_core_v1_msg_danmaku_proto_rawDescGZIP() []byte {
	file_core_v1_msg_danmaku_proto_rawDescOnce.Do(func() {
		file_core_v1_msg_danmaku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_msg_danmaku_proto_rawDesc), len(file_core_v1_msg_danmaku_proto_rawDesc)))
	})
	return file_core_v1_msg_danmaku_proto_rawDescData
}

var file_core_v1_msg_danmaku_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_msg_danmaku_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: core.v1.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: core.v1.SendMessageResponse
}
var file_core_v1_msg_danmaku_proto_depIdxs = []int32{
	0, // 0: core.v1.MsgDanmakuService.SendMessage:input_type -> core.v1.SendMessageRequest
	1, // 1: core.v1.MsgDanmakuService.SendMessage:output_type -> core.v1.SendMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_msg_danmaku_proto_init() }
func file_core_v1_msg_danmaku_proto_init() {
	if File_core_v1_msg_danmaku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_msg_danmaku_proto_rawDesc), len(file_core_v1_msg_danmaku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_msg_danmaku_proto_goTypes,
		DependencyIndexes: file_core_v1_msg_danmaku_proto_depIdxs,
		MessageInfos:      file_core_v1_msg_danmaku_proto_msgTypes,
	}.Build()
	File_core_v1_msg_danmaku_proto = out.File
	file_core_v1_msg_danmaku_proto_goTypes = nil
	file_core_v1_msg_danmaku_proto_depIdxs = nil
}
