apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studio-data
  namespace: mybilibili
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 5Gi}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: work-tmp
  namespace: mybilibili
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 5Gi}}