// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/core/v1/manuscript.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManuscriptService_GetManuscript_FullMethodName           = "/core.v1.ManuscriptService/GetManuscript"
	ManuscriptService_GetManuscriptWithVideos_FullMethodName = "/core.v1.ManuscriptService/GetManuscriptWithVideos"
	ManuscriptService_ListUserManuscripts_FullMethodName     = "/core.v1.ManuscriptService/ListUserManuscripts"
	ManuscriptService_ListRecommended_FullMethodName         = "/core.v1.ManuscriptService/ListRecommended"
	ManuscriptService_ListHot_FullMethodName                 = "/core.v1.ManuscriptService/ListHot"
	ManuscriptService_ListByCategory_FullMethodName          = "/core.v1.ManuscriptService/ListByCategory"
	ManuscriptService_ListCategories_FullMethodName          = "/core.v1.ManuscriptService/ListCategories"
	ManuscriptService_DeleteManuscript_FullMethodName        = "/core.v1.ManuscriptService/DeleteManuscript"
	ManuscriptService_UpdateManuscript_FullMethodName        = "/core.v1.ManuscriptService/UpdateManuscript"
	ManuscriptService_PublishManuscript_FullMethodName       = "/core.v1.ManuscriptService/PublishManuscript"
	ManuscriptService_UnpublishManuscript_FullMethodName     = "/core.v1.ManuscriptService/UnpublishManuscript"
	ManuscriptService_SearchUserManuscripts_FullMethodName   = "/core.v1.ManuscriptService/SearchUserManuscripts"
)

// ManuscriptServiceClient is the client API for ManuscriptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManuscriptServiceClient interface {
	GetManuscript(ctx context.Context, in *GetManuscriptRequest, opts ...grpc.CallOption) (*GetManuscriptResponse, error)
	GetManuscriptWithVideos(ctx context.Context, in *GetManuscriptWithVideosRequest, opts ...grpc.CallOption) (*GetManuscriptResponse, error)
	ListUserManuscripts(ctx context.Context, in *ListUserManuscriptsRequest, opts ...grpc.CallOption) (*ListUserManuscriptsResponse, error)
	ListRecommended(ctx context.Context, in *ListRecommendedRequest, opts ...grpc.CallOption) (*ListRecommendedResponse, error)
	ListHot(ctx context.Context, in *ListHotRequest, opts ...grpc.CallOption) (*ListHotResponse, error)
	ListByCategory(ctx context.Context, in *ListByCategoryRequest, opts ...grpc.CallOption) (*ListByCategoryResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	DeleteManuscript(ctx context.Context, in *DeleteManuscriptRequest, opts ...grpc.CallOption) (*DeleteManuscriptResponse, error)
	UpdateManuscript(ctx context.Context, in *UpdateManuscriptRequest, opts ...grpc.CallOption) (*UpdateManuscriptResponse, error)
	PublishManuscript(ctx context.Context, in *PublishManuscriptRequest, opts ...grpc.CallOption) (*PublishManuscriptResponse, error)
	UnpublishManuscript(ctx context.Context, in *UnpublishManuscriptRequest, opts ...grpc.CallOption) (*UnpublishManuscriptResponse, error)
	SearchUserManuscripts(ctx context.Context, in *SearchUserManuscriptsRequest, opts ...grpc.CallOption) (*SearchUserManuscriptsResponse, error)
}

type manuscriptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManuscriptServiceClient(cc grpc.ClientConnInterface) ManuscriptServiceClient {
	return &manuscriptServiceClient{cc}
}

func (c *manuscriptServiceClient) GetManuscript(ctx context.Context, in *GetManuscriptRequest, opts ...grpc.CallOption) (*GetManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManuscriptResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_GetManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) GetManuscriptWithVideos(ctx context.Context, in *GetManuscriptWithVideosRequest, opts ...grpc.CallOption) (*GetManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManuscriptResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_GetManuscriptWithVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) ListUserManuscripts(ctx context.Context, in *ListUserManuscriptsRequest, opts ...grpc.CallOption) (*ListUserManuscriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserManuscriptsResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_ListUserManuscripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) ListRecommended(ctx context.Context, in *ListRecommendedRequest, opts ...grpc.CallOption) (*ListRecommendedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendedResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_ListRecommended_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) ListHot(ctx context.Context, in *ListHotRequest, opts ...grpc.CallOption) (*ListHotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHotResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_ListHot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) ListByCategory(ctx context.Context, in *ListByCategoryRequest, opts ...grpc.CallOption) (*ListByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListByCategoryResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_ListByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) DeleteManuscript(ctx context.Context, in *DeleteManuscriptRequest, opts ...grpc.CallOption) (*DeleteManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManuscriptResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_DeleteManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) UpdateManuscript(ctx context.Context, in *UpdateManuscriptRequest, opts ...grpc.CallOption) (*UpdateManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManuscriptResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_UpdateManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) PublishManuscript(ctx context.Context, in *PublishManuscriptRequest, opts ...grpc.CallOption) (*PublishManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishManuscriptResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_PublishManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) UnpublishManuscript(ctx context.Context, in *UnpublishManuscriptRequest, opts ...grpc.CallOption) (*UnpublishManuscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishManuscriptResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_UnpublishManuscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manuscriptServiceClient) SearchUserManuscripts(ctx context.Context, in *SearchUserManuscriptsRequest, opts ...grpc.CallOption) (*SearchUserManuscriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUserManuscriptsResponse)
	err := c.cc.Invoke(ctx, ManuscriptService_SearchUserManuscripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManuscriptServiceServer is the server API for ManuscriptService service.
// All implementations must embed UnimplementedManuscriptServiceServer
// for forward compatibility.
type ManuscriptServiceServer interface {
	GetManuscript(context.Context, *GetManuscriptRequest) (*GetManuscriptResponse, error)
	GetManuscriptWithVideos(context.Context, *GetManuscriptWithVideosRequest) (*GetManuscriptResponse, error)
	ListUserManuscripts(context.Context, *ListUserManuscriptsRequest) (*ListUserManuscriptsResponse, error)
	ListRecommended(context.Context, *ListRecommendedRequest) (*ListRecommendedResponse, error)
	ListHot(context.Context, *ListHotRequest) (*ListHotResponse, error)
	ListByCategory(context.Context, *ListByCategoryRequest) (*ListByCategoryResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	DeleteManuscript(context.Context, *DeleteManuscriptRequest) (*DeleteManuscriptResponse, error)
	UpdateManuscript(context.Context, *UpdateManuscriptRequest) (*UpdateManuscriptResponse, error)
	PublishManuscript(context.Context, *PublishManuscriptRequest) (*PublishManuscriptResponse, error)
	UnpublishManuscript(context.Context, *UnpublishManuscriptRequest) (*UnpublishManuscriptResponse, error)
	SearchUserManuscripts(context.Context, *SearchUserManuscriptsRequest) (*SearchUserManuscriptsResponse, error)
	mustEmbedUnimplementedManuscriptServiceServer()
}

// UnimplementedManuscriptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManuscriptServiceServer struct{}

func (UnimplementedManuscriptServiceServer) GetManuscript(context.Context, *GetManuscriptRequest) (*GetManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManuscript not implemented")
}
func (UnimplementedManuscriptServiceServer) GetManuscriptWithVideos(context.Context, *GetManuscriptWithVideosRequest) (*GetManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManuscriptWithVideos not implemented")
}
func (UnimplementedManuscriptServiceServer) ListUserManuscripts(context.Context, *ListUserManuscriptsRequest) (*ListUserManuscriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserManuscripts not implemented")
}
func (UnimplementedManuscriptServiceServer) ListRecommended(context.Context, *ListRecommendedRequest) (*ListRecommendedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecommended not implemented")
}
func (UnimplementedManuscriptServiceServer) ListHot(context.Context, *ListHotRequest) (*ListHotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHot not implemented")
}
func (UnimplementedManuscriptServiceServer) ListByCategory(context.Context, *ListByCategoryRequest) (*ListByCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByCategory not implemented")
}
func (UnimplementedManuscriptServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedManuscriptServiceServer) DeleteManuscript(context.Context, *DeleteManuscriptRequest) (*DeleteManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManuscript not implemented")
}
func (UnimplementedManuscriptServiceServer) UpdateManuscript(context.Context, *UpdateManuscriptRequest) (*UpdateManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateManuscript not implemented")
}
func (UnimplementedManuscriptServiceServer) PublishManuscript(context.Context, *PublishManuscriptRequest) (*PublishManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishManuscript not implemented")
}
func (UnimplementedManuscriptServiceServer) UnpublishManuscript(context.Context, *UnpublishManuscriptRequest) (*UnpublishManuscriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishManuscript not implemented")
}
func (UnimplementedManuscriptServiceServer) SearchUserManuscripts(context.Context, *SearchUserManuscriptsRequest) (*SearchUserManuscriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUserManuscripts not implemented")
}
func (UnimplementedManuscriptServiceServer) mustEmbedUnimplementedManuscriptServiceServer() {}
func (UnimplementedManuscriptServiceServer) testEmbeddedByValue()                           {}

// UnsafeManuscriptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManuscriptServiceServer will
// result in compilation errors.
type UnsafeManuscriptServiceServer interface {
	mustEmbedUnimplementedManuscriptServiceServer()
}

func RegisterManuscriptServiceServer(s grpc.ServiceRegistrar, srv ManuscriptServiceServer) {
	// If the following call panics, it indicates UnimplementedManuscriptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManuscriptService_ServiceDesc, srv)
}

func _ManuscriptService_GetManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).GetManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_GetManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).GetManuscript(ctx, req.(*GetManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_GetManuscriptWithVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManuscriptWithVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).GetManuscriptWithVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_GetManuscriptWithVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).GetManuscriptWithVideos(ctx, req.(*GetManuscriptWithVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_ListUserManuscripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserManuscriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).ListUserManuscripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_ListUserManuscripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).ListUserManuscripts(ctx, req.(*ListUserManuscriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_ListRecommended_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).ListRecommended(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_ListRecommended_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).ListRecommended(ctx, req.(*ListRecommendedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_ListHot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).ListHot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_ListHot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).ListHot(ctx, req.(*ListHotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_ListByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).ListByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_ListByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).ListByCategory(ctx, req.(*ListByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_DeleteManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).DeleteManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_DeleteManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).DeleteManuscript(ctx, req.(*DeleteManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_UpdateManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).UpdateManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_UpdateManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).UpdateManuscript(ctx, req.(*UpdateManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_PublishManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).PublishManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_PublishManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).PublishManuscript(ctx, req.(*PublishManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_UnpublishManuscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishManuscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).UnpublishManuscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_UnpublishManuscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).UnpublishManuscript(ctx, req.(*UnpublishManuscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManuscriptService_SearchUserManuscripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserManuscriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManuscriptServiceServer).SearchUserManuscripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManuscriptService_SearchUserManuscripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManuscriptServiceServer).SearchUserManuscripts(ctx, req.(*SearchUserManuscriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManuscriptService_ServiceDesc is the grpc.ServiceDesc for ManuscriptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManuscriptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.v1.ManuscriptService",
	HandlerType: (*ManuscriptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManuscript",
			Handler:    _ManuscriptService_GetManuscript_Handler,
		},
		{
			MethodName: "GetManuscriptWithVideos",
			Handler:    _ManuscriptService_GetManuscriptWithVideos_Handler,
		},
		{
			MethodName: "ListUserManuscripts",
			Handler:    _ManuscriptService_ListUserManuscripts_Handler,
		},
		{
			MethodName: "ListRecommended",
			Handler:    _ManuscriptService_ListRecommended_Handler,
		},
		{
			MethodName: "ListHot",
			Handler:    _ManuscriptService_ListHot_Handler,
		},
		{
			MethodName: "ListByCategory",
			Handler:    _ManuscriptService_ListByCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _ManuscriptService_ListCategories_Handler,
		},
		{
			MethodName: "DeleteManuscript",
			Handler:    _ManuscriptService_DeleteManuscript_Handler,
		},
		{
			MethodName: "UpdateManuscript",
			Handler:    _ManuscriptService_UpdateManuscript_Handler,
		},
		{
			MethodName: "PublishManuscript",
			Handler:    _ManuscriptService_PublishManuscript_Handler,
		},
		{
			MethodName: "UnpublishManuscript",
			Handler:    _ManuscriptService_UnpublishManuscript_Handler,
		},
		{
			MethodName: "SearchUserManuscripts",
			Handler:    _ManuscriptService_SearchUserManuscripts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/manuscript.proto",
}
