// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/core/v1/interaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeManuscriptRequest) Reset() {
	*x = LikeManuscriptRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeManuscriptRequest) ProtoMessage() {}

func (x *LikeManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeManuscriptRequest.ProtoReflect.Descriptor instead.
func (*LikeManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeManuscriptRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *LikeManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikeManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikeCount     int32                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeManuscriptResponse) Reset() {
	*x = LikeManuscriptResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeManuscriptResponse) ProtoMessage() {}

func (x *LikeManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeManuscriptResponse.ProtoReflect.Descriptor instead.
func (*LikeManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeManuscriptResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *LikeManuscriptResponse) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type UnlikeManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeManuscriptRequest) Reset() {
	*x = UnlikeManuscriptRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeManuscriptRequest) ProtoMessage() {}

func (x *UnlikeManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeManuscriptRequest.ProtoReflect.Descriptor instead.
func (*UnlikeManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeManuscriptRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *UnlikeManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlikeManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikeCount     int32                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeManuscriptResponse) Reset() {
	*x = UnlikeManuscriptResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeManuscriptResponse) ProtoMessage() {}

func (x *UnlikeManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeManuscriptResponse.ProtoReflect.Descriptor instead.
func (*UnlikeManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *UnlikeManuscriptResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *UnlikeManuscriptResponse) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type CoinManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoinCount     int32                  `protobuf:"varint,3,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinManuscriptRequest) Reset() {
	*x = CoinManuscriptRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinManuscriptRequest) ProtoMessage() {}

func (x *CoinManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinManuscriptRequest.ProtoReflect.Descriptor instead.
func (*CoinManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *CoinManuscriptRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *CoinManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CoinManuscriptRequest) GetCoinCount() int32 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

type CoinManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinManuscriptResponse) Reset() {
	*x = CoinManuscriptResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinManuscriptResponse) ProtoMessage() {}

func (x *CoinManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinManuscriptResponse.ProtoReflect.Descriptor instead.
func (*CoinManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *CoinManuscriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CollectManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectManuscriptRequest) Reset() {
	*x = CollectManuscriptRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectManuscriptRequest) ProtoMessage() {}

func (x *CollectManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectManuscriptRequest.ProtoReflect.Descriptor instead.
func (*CollectManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *CollectManuscriptRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *CollectManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectManuscriptRequest) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type CollectManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collected     bool                   `protobuf:"varint,1,opt,name=collected,proto3" json:"collected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectManuscriptResponse) Reset() {
	*x = CollectManuscriptResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectManuscriptResponse) ProtoMessage() {}

func (x *CollectManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectManuscriptResponse.ProtoReflect.Descriptor instead.
func (*CollectManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *CollectManuscriptResponse) GetCollected() bool {
	if x != nil {
		return x.Collected
	}
	return false
}

type UncollectManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectManuscriptRequest) Reset() {
	*x = UncollectManuscriptRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectManuscriptRequest) ProtoMessage() {}

func (x *UncollectManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectManuscriptRequest.ProtoReflect.Descriptor instead.
func (*UncollectManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *UncollectManuscriptRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *UncollectManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UncollectManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collected     bool                   `protobuf:"varint,1,opt,name=collected,proto3" json:"collected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectManuscriptResponse) Reset() {
	*x = UncollectManuscriptResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectManuscriptResponse) ProtoMessage() {}

func (x *UncollectManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectManuscriptResponse.ProtoReflect.Descriptor instead.
func (*UncollectManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *UncollectManuscriptResponse) GetCollected() bool {
	if x != nil {
		return x.Collected
	}
	return false
}

type ShareManuscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareManuscriptRequest) Reset() {
	*x = ShareManuscriptRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareManuscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareManuscriptRequest) ProtoMessage() {}

func (x *ShareManuscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareManuscriptRequest.ProtoReflect.Descriptor instead.
func (*ShareManuscriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *ShareManuscriptRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *ShareManuscriptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShareManuscriptRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ShareManuscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareManuscriptResponse) Reset() {
	*x = ShareManuscriptResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareManuscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareManuscriptResponse) ProtoMessage() {}

func (x *ShareManuscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareManuscriptResponse.ProtoReflect.Descriptor instead.
func (*ShareManuscriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *ShareManuscriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInteractionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId  int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractionStatusRequest) Reset() {
	*x = GetInteractionStatusRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionStatusRequest) ProtoMessage() {}

func (x *GetInteractionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInteractionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *GetInteractionStatusRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *GetInteractionStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetInteractionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	Collected     bool                   `protobuf:"varint,2,opt,name=collected,proto3" json:"collected,omitempty"`
	Shared        bool                   `protobuf:"varint,3,opt,name=shared,proto3" json:"shared,omitempty"`
	CoinCount     int32                  `protobuf:"varint,4,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractionStatusResponse) Reset() {
	*x = GetInteractionStatusResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionStatusResponse) ProtoMessage() {}

func (x *GetInteractionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInteractionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *GetInteractionStatusResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *GetInteractionStatusResponse) GetCollected() bool {
	if x != nil {
		return x.Collected
	}
	return false
}

func (x *GetInteractionStatusResponse) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *GetInteractionStatusResponse) GetCoinCount() int32 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *FollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *FollowUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *FollowUserResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *UnfollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *UnfollowUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnfollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserResponse) Reset() {
	*x = UnfollowUserResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResponse) ProtoMessage() {}

func (x *UnfollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnfollowUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *UnfollowUserResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type CheckFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowRequest) Reset() {
	*x = CheckFollowRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowRequest) ProtoMessage() {}

func (x *CheckFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowRequest.ProtoReflect.Descriptor instead.
func (*CheckFollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *CheckFollowRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *CheckFollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowResponse) Reset() {
	*x = CheckFollowResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowResponse) ProtoMessage() {}

func (x *CheckFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowResponse.ProtoReflect.Descriptor instead.
func (*CheckFollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *CheckFollowResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type GetFollowCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowCountRequest) Reset() {
	*x = GetFollowCountRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowCountRequest) ProtoMessage() {}

func (x *GetFollowCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowCountRequest.ProtoReflect.Descriptor instead.
func (*GetFollowCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{20}
}

func (x *GetFollowCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowCountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowingCount int32                  `protobuf:"varint,1,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowerCount  int32                  `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFollowCountResponse) Reset() {
	*x = GetFollowCountResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowCountResponse) ProtoMessage() {}

func (x *GetFollowCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowCountResponse.ProtoReflect.Descriptor instead.
func (*GetFollowCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{21}
}

func (x *GetFollowCountResponse) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *GetFollowCountResponse) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

type GetLikedManuscriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikedManuscriptsRequest) Reset() {
	*x = GetLikedManuscriptsRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikedManuscriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikedManuscriptsRequest) ProtoMessage() {}

func (x *GetLikedManuscriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikedManuscriptsRequest.ProtoReflect.Descriptor instead.
func (*GetLikedManuscriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{22}
}

func (x *GetLikedManuscriptsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLikedManuscriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptIds []int64                `protobuf:"varint,1,rep,packed,name=manuscript_ids,json=manuscriptIds,proto3" json:"manuscript_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikedManuscriptsResponse) Reset() {
	*x = GetLikedManuscriptsResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikedManuscriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikedManuscriptsResponse) ProtoMessage() {}

func (x *GetLikedManuscriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikedManuscriptsResponse.ProtoReflect.Descriptor instead.
func (*GetLikedManuscriptsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{23}
}

func (x *GetLikedManuscriptsResponse) GetManuscriptIds() []int64 {
	if x != nil {
		return x.ManuscriptIds
	}
	return nil
}

type GetCollectedManuscriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectedManuscriptsRequest) Reset() {
	*x = GetCollectedManuscriptsRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectedManuscriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectedManuscriptsRequest) ProtoMessage() {}

func (x *GetCollectedManuscriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectedManuscriptsRequest.ProtoReflect.Descriptor instead.
func (*GetCollectedManuscriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{24}
}

func (x *GetCollectedManuscriptsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCollectedManuscriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptIds []int64                `protobuf:"varint,1,rep,packed,name=manuscript_ids,json=manuscriptIds,proto3" json:"manuscript_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectedManuscriptsResponse) Reset() {
	*x = GetCollectedManuscriptsResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectedManuscriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectedManuscriptsResponse) ProtoMessage() {}

func (x *GetCollectedManuscriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectedManuscriptsResponse.ProtoReflect.Descriptor instead.
func (*GetCollectedManuscriptsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{25}
}

func (x *GetCollectedManuscriptsResponse) GetManuscriptIds() []int64 {
	if x != nil {
		return x.ManuscriptIds
	}
	return nil
}

type AddWatchHistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ManuscriptId    int64                  `protobuf:"varint,2,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	ProgressSeconds int32                  `protobuf:"varint,3,opt,name=progress_seconds,json=progressSeconds,proto3" json:"progress_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddWatchHistoryRequest) Reset() {
	*x = AddWatchHistoryRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchHistoryRequest) ProtoMessage() {}

func (x *AddWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*AddWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{26}
}

func (x *AddWatchHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddWatchHistoryRequest) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *AddWatchHistoryRequest) GetProgressSeconds() int32 {
	if x != nil {
		return x.ProgressSeconds
	}
	return 0
}

type AddWatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWatchHistoryResponse) Reset() {
	*x = AddWatchHistoryResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchHistoryResponse) ProtoMessage() {}

func (x *AddWatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*AddWatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{27}
}

type GetWatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchHistoryRequest) Reset() {
	*x = GetWatchHistoryRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchHistoryRequest) ProtoMessage() {}

func (x *GetWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{28}
}

func (x *GetWatchHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetWatchHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWatchHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type WatchHistoryItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManuscriptId    int64                  `protobuf:"varint,1,opt,name=manuscript_id,json=manuscriptId,proto3" json:"manuscript_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl        string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	ProgressSeconds int32                  `protobuf:"varint,4,opt,name=progress_seconds,json=progressSeconds,proto3" json:"progress_seconds,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	WatchedAt       string                 `protobuf:"bytes,6,opt,name=watched_at,json=watchedAt,proto3" json:"watched_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchHistoryItem) Reset() {
	*x = WatchHistoryItem{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchHistoryItem) ProtoMessage() {}

func (x *WatchHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchHistoryItem.ProtoReflect.Descriptor instead.
func (*WatchHistoryItem) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{29}
}

func (x *WatchHistoryItem) GetManuscriptId() int64 {
	if x != nil {
		return x.ManuscriptId
	}
	return 0
}

func (x *WatchHistoryItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WatchHistoryItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *WatchHistoryItem) GetProgressSeconds() int32 {
	if x != nil {
		return x.ProgressSeconds
	}
	return 0
}

func (x *WatchHistoryItem) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *WatchHistoryItem) GetWatchedAt() string {
	if x != nil {
		return x.WatchedAt
	}
	return ""
}

type GetWatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WatchHistoryItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchHistoryResponse) Reset() {
	*x = GetWatchHistoryResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchHistoryResponse) ProtoMessage() {}

func (x *GetWatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{30}
}

func (x *GetWatchHistoryResponse) GetItems() []*WatchHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClearWatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearWatchHistoryRequest) Reset() {
	*x = ClearWatchHistoryRequest{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearWatchHistoryRequest) ProtoMessage() {}

func (x *ClearWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{31}
}

func (x *ClearWatchHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearWatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearWatchHistoryResponse) Reset() {
	*x = ClearWatchHistoryResponse{}
	mi := &file_proto_core_v1_interaction_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearWatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearWatchHistoryResponse) ProtoMessage() {}

func (x *ClearWatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_interaction_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearWatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*ClearWatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_interaction_proto_rawDescGZIP(), []int{32}
}

var File_proto_core_v1_interaction_proto protoreflect.FileDescriptor

const file_proto_core_v1_interaction_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/core/v1/interaction.proto\x12\acore.v1\"U\n" +
	"\x15LikeManuscriptRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"M\n" +
	"\x16LikeManuscriptResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x05R\tlikeCount\"W\n" +
	"\x17UnlikeManuscriptRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"O\n" +
	"\x18UnlikeManuscriptResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x05R\tlikeCount\"t\n" +
	"\x15CoinManuscriptRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"coin_count\x18\x03 \x01(\x05R\tcoinCount\"2\n" +
	"\x16CoinManuscriptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"u\n" +
	"\x18CollectManuscriptRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x03 \x01(\x03R\bfolderId\"9\n" +
	"\x19CollectManuscriptResponse\x12\x1c\n" +
	"\tcollected\x18\x01 \x01(\bR\tcollected\"Z\n" +
	"\x1aUncollectManuscriptRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\";\n" +
	"\x1bUncollectManuscriptResponse\x12\x1c\n" +
	"\tcollected\x18\x01 \x01(\bR\tcollected\"p\n" +
	"\x16ShareManuscriptRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"3\n" +
	"\x17ShareManuscriptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x1bGetInteractionStatusRequest\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x89\x01\n" +
	"\x1cGetInteractionStatusResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1c\n" +
	"\tcollected\x18\x02 \x01(\bR\tcollected\x12\x16\n" +
	"\x06shared\x18\x03 \x01(\bR\x06shared\x12\x1d\n" +
	"\n" +
	"coin_count\x18\x04 \x01(\x05R\tcoinCount\"R\n" +
	"\x11FollowUserRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"2\n" +
	"\x12FollowUserResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\"T\n" +
	"\x13UnfollowUserRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"4\n" +
	"\x14UnfollowUserResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\"S\n" +
	"\x12CheckFollowRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"3\n" +
	"\x13CheckFollowResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\"0\n" +
	"\x15GetFollowCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"h\n" +
	"\x16GetFollowCountResponse\x12'\n" +
	"\x0ffollowing_count\x18\x01 \x01(\x05R\x0efollowingCount\x12%\n" +
	"\x0efollower_count\x18\x02 \x01(\x05R\rfollowerCount\"5\n" +
	"\x1aGetLikedManuscriptsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"D\n" +
	"\x1bGetLikedManuscriptsResponse\x12%\n" +
	"\x0emanuscript_ids\x18\x01 \x03(\x03R\rmanuscriptIds\"9\n" +
	"\x1eGetCollectedManuscriptsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x1fGetCollectedManuscriptsResponse\x12%\n" +
	"\x0emanuscript_ids\x18\x01 \x03(\x03R\rmanuscriptIds\"\x81\x01\n" +
	"\x16AddWatchHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rmanuscript_id\x18\x02 \x01(\x03R\fmanuscriptId\x12)\n" +
	"\x10progress_seconds\x18\x03 \x01(\x05R\x0fprogressSeconds\"\x19\n" +
	"\x17AddWatchHistoryResponse\"b\n" +
	"\x16GetWatchHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xdf\x01\n" +
	"\x10WatchHistoryItem\x12#\n" +
	"\rmanuscript_id\x18\x01 \x01(\x03R\fmanuscriptId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12)\n" +
	"\x10progress_seconds\x18\x04 \x01(\x05R\x0fprogressSeconds\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"watched_at\x18\x06 \x01(\tR\twatchedAt\"J\n" +
	"\x17GetWatchHistoryResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.core.v1.WatchHistoryItemR\x05items\"3\n" +
	"\x18ClearWatchHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x1b\n" +
	"\x19ClearWatchHistoryResponse2\x95\v\n" +
	"\x12InteractionService\x12Q\n" +
	"\x0eLikeManuscript\x12\x1e.core.v1.LikeManuscriptRequest\x1a\x1f.core.v1.LikeManuscriptResponse\x12W\n" +
	"\x10UnlikeManuscript\x12 .core.v1.UnlikeManuscriptRequest\x1a!.core.v1.UnlikeManuscriptResponse\x12Q\n" +
	"\x0eCoinManuscript\x12\x1e.core.v1.CoinManuscriptRequest\x1a\x1f.core.v1.CoinManuscriptResponse\x12Z\n" +
	"\x11CollectManuscript\x12!.core.v1.CollectManuscriptRequest\x1a\".core.v1.CollectManuscriptResponse\x12`\n" +
	"\x13UncollectManuscript\x12#.core.v1.UncollectManuscriptRequest\x1a$.core.v1.UncollectManuscriptResponse\x12T\n" +
	"\x0fShareManuscript\x12\x1f.core.v1.ShareManuscriptRequest\x1a .core.v1.ShareManuscriptResponse\x12c\n" +
	"\x14GetInteractionStatus\x12$.core.v1.GetInteractionStatusRequest\x1a%.core.v1.GetInteractionStatusResponse\x12E\n" +
	"\n" +
	"FollowUser\x12\x1a.core.v1.FollowUserRequest\x1a\x1b.core.v1.FollowUserResponse\x12K\n" +
	"\fUnfollowUser\x12\x1c.core.v1.UnfollowUserRequest\x1a\x1d.core.v1.UnfollowUserResponse\x12H\n" +
	"\vCheckFollow\x12\x1b.core.v1.CheckFollowRequest\x1a\x1c.core.v1.CheckFollowResponse\x12Q\n" +
	"\x0eGetFollowCount\x12\x1e.core.v1.GetFollowCountRequest\x1a\x1f.core.v1.GetFollowCountResponse\x12`\n" +
	"\x13GetLikedManuscripts\x12#.core.v1.GetLikedManuscriptsRequest\x1a$.core.v1.GetLikedManuscriptsResponse\x12l\n" +
	"\x17GetCollectedManuscripts\x12'.core.v1.GetCollectedManuscriptsRequest\x1a(.core.v1.GetCollectedManuscriptsResponse\x12T\n" +
	"\x0fAddWatchHistory\x12\x1f.core.v1.AddWatchHistoryRequest\x1a .core.v1.AddWatchHistoryResponse\x12T\n" +
	"\x0fGetWatchHistory\x12\x1f.core.v1.GetWatchHistoryRequest\x1a .core.v1.GetWatchHistoryResponse\x12Z\n" +
	"\x11ClearWatchHistory\x12!.core.v1.ClearWatchHistoryRequest\x1a\".core.v1.ClearWatchHistoryResponseB\x1dZ\x1bmybilibili/internal/core/pbb\x06proto3"

var (
	file_proto_core_v1_interaction_proto_rawDescOnce sync.Once
	file_proto_core_v1_interaction_proto_rawDescData []byte
)

func file_proto_core_v1_interaction_proto_rawDescGZIP() []byte {
	file_proto_core_v1_interaction_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_interaction_proto_rawDesc), len(file_proto_core_v1_interaction_proto_rawDesc)))
	})
	return file_proto_core_v1_interaction_proto_rawDescData
}

var file_proto_core_v1_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_core_v1_interaction_proto_goTypes = []any{
	(*LikeManuscriptRequest)(nil),           // 0: core.v1.LikeManuscriptRequest
	(*LikeManuscriptResponse)(nil),          // 1: core.v1.LikeManuscriptResponse
	(*UnlikeManuscriptRequest)(nil),         // 2: core.v1.UnlikeManuscriptRequest
	(*UnlikeManuscriptResponse)(nil),        // 3: core.v1.UnlikeManuscriptResponse
	(*CoinManuscriptRequest)(nil),           // 4: core.v1.CoinManuscriptRequest
	(*CoinManuscriptResponse)(nil),          // 5: core.v1.CoinManuscriptResponse
	(*CollectManuscriptRequest)(nil),        // 6: core.v1.CollectManuscriptRequest
	(*CollectManuscriptResponse)(nil),       // 7: core.v1.CollectManuscriptResponse
	(*UncollectManuscriptRequest)(nil),      // 8: core.v1.UncollectManuscriptRequest
	(*UncollectManuscriptResponse)(nil),     // 9: core.v1.UncollectManuscriptResponse
	(*ShareManuscriptRequest)(nil),          // 10: core.v1.ShareManuscriptRequest
	(*ShareManuscriptResponse)(nil),         // 11: core.v1.ShareManuscriptResponse
	(*GetInteractionStatusRequest)(nil),     // 12: core.v1.GetInteractionStatusRequest
	(*GetInteractionStatusResponse)(nil),    // 13: core.v1.GetInteractionStatusResponse
	(*FollowUserRequest)(nil),               // 14: core.v1.FollowUserRequest
	(*FollowUserResponse)(nil),              // 15: core.v1.FollowUserResponse
	(*UnfollowUserRequest)(nil),             // 16: core.v1.UnfollowUserRequest
	(*UnfollowUserResponse)(nil),            // 17: core.v1.UnfollowUserResponse
	(*CheckFollowRequest)(nil),              // 18: core.v1.CheckFollowRequest
	(*CheckFollowResponse)(nil),             // 19: core.v1.CheckFollowResponse
	(*GetFollowCountRequest)(nil),           // 20: core.v1.GetFollowCountRequest
	(*GetFollowCountResponse)(nil),          // 21: core.v1.GetFollowCountResponse
	(*GetLikedManuscriptsRequest)(nil),      // 22: core.v1.GetLikedManuscriptsRequest
	(*GetLikedManuscriptsResponse)(nil),     // 23: core.v1.GetLikedManuscriptsResponse
	(*GetCollectedManuscriptsRequest)(nil),  // 24: core.v1.GetCollectedManuscriptsRequest
	(*GetCollectedManuscriptsResponse)(nil), // 25: core.v1.GetCollectedManuscriptsResponse
	(*AddWatchHistoryRequest)(nil),          // 26: core.v1.AddWatchHistoryRequest
	(*AddWatchHistoryResponse)(nil),         // 27: core.v1.AddWatchHistoryResponse
	(*GetWatchHistoryRequest)(nil),          // 28: core.v1.GetWatchHistoryRequest
	(*WatchHistoryItem)(nil),                // 29: core.v1.WatchHistoryItem
	(*GetWatchHistoryResponse)(nil),         // 30: core.v1.GetWatchHistoryResponse
	(*ClearWatchHistoryRequest)(nil),        // 31: core.v1.ClearWatchHistoryRequest
	(*ClearWatchHistoryResponse)(nil),       // 32: core.v1.ClearWatchHistoryResponse
}
var file_proto_core_v1_interaction_proto_depIdxs = []int32{
	29, // 0: core.v1.GetWatchHistoryResponse.items:type_name -> core.v1.WatchHistoryItem
	0,  // 1: core.v1.InteractionService.LikeManuscript:input_type -> core.v1.LikeManuscriptRequest
	2,  // 2: core.v1.InteractionService.UnlikeManuscript:input_type -> core.v1.UnlikeManuscriptRequest
	4,  // 3: core.v1.InteractionService.CoinManuscript:input_type -> core.v1.CoinManuscriptRequest
	6,  // 4: core.v1.InteractionService.CollectManuscript:input_type -> core.v1.CollectManuscriptRequest
	8,  // 5: core.v1.InteractionService.UncollectManuscript:input_type -> core.v1.UncollectManuscriptRequest
	10, // 6: core.v1.InteractionService.ShareManuscript:input_type -> core.v1.ShareManuscriptRequest
	12, // 7: core.v1.InteractionService.GetInteractionStatus:input_type -> core.v1.GetInteractionStatusRequest
	14, // 8: core.v1.InteractionService.FollowUser:input_type -> core.v1.FollowUserRequest
	16, // 9: core.v1.InteractionService.UnfollowUser:input_type -> core.v1.UnfollowUserRequest
	18, // 10: core.v1.InteractionService.CheckFollow:input_type -> core.v1.CheckFollowRequest
	20, // 11: core.v1.InteractionService.GetFollowCount:input_type -> core.v1.GetFollowCountRequest
	22, // 12: core.v1.InteractionService.GetLikedManuscripts:input_type -> core.v1.GetLikedManuscriptsRequest
	24, // 13: core.v1.InteractionService.GetCollectedManuscripts:input_type -> core.v1.GetCollectedManuscriptsRequest
	26, // 14: core.v1.InteractionService.AddWatchHistory:input_type -> core.v1.AddWatchHistoryRequest
	28, // 15: core.v1.InteractionService.GetWatchHistory:input_type -> core.v1.GetWatchHistoryRequest
	31, // 16: core.v1.InteractionService.ClearWatchHistory:input_type -> core.v1.ClearWatchHistoryRequest
	1,  // 17: core.v1.InteractionService.LikeManuscript:output_type -> core.v1.LikeManuscriptResponse
	3,  // 18: core.v1.InteractionService.UnlikeManuscript:output_type -> core.v1.UnlikeManuscriptResponse
	5,  // 19: core.v1.InteractionService.CoinManuscript:output_type -> core.v1.CoinManuscriptResponse
	7,  // 20: core.v1.InteractionService.CollectManuscript:output_type -> core.v1.CollectManuscriptResponse
	9,  // 21: core.v1.InteractionService.UncollectManuscript:output_type -> core.v1.UncollectManuscriptResponse
	11, // 22: core.v1.InteractionService.ShareManuscript:output_type -> core.v1.ShareManuscriptResponse
	13, // 23: core.v1.InteractionService.GetInteractionStatus:output_type -> core.v1.GetInteractionStatusResponse
	15, // 24: core.v1.InteractionService.FollowUser:output_type -> core.v1.FollowUserResponse
	17, // 25: core.v1.InteractionService.UnfollowUser:output_type -> core.v1.UnfollowUserResponse
	19, // 26: core.v1.InteractionService.CheckFollow:output_type -> core.v1.CheckFollowResponse
	21, // 27: core.v1.InteractionService.GetFollowCount:output_type -> core.v1.GetFollowCountResponse
	23, // 28: core.v1.InteractionService.GetLikedManuscripts:output_type -> core.v1.GetLikedManuscriptsResponse
	25, // 29: core.v1.InteractionService.GetCollectedManuscripts:output_type -> core.v1.GetCollectedManuscriptsResponse
	27, // 30: core.v1.InteractionService.AddWatchHistory:output_type -> core.v1.AddWatchHistoryResponse
	30, // 31: core.v1.InteractionService.GetWatchHistory:output_type -> core.v1.GetWatchHistoryResponse
	32, // 32: core.v1.InteractionService.ClearWatchHistory:output_type -> core.v1.ClearWatchHistoryResponse
	17, // [17:33] is the sub-list for method output_type
	1,  // [1:17] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_core_v1_interaction_proto_init() }
func file_proto_core_v1_interaction_proto_init() {
	if File_proto_core_v1_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_interaction_proto_rawDesc), len(file_proto_core_v1_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_interaction_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_interaction_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_interaction_proto_msgTypes,
	}.Build()
	File_proto_core_v1_interaction_proto = out.File
	file_proto_core_v1_interaction_proto_goTypes = nil
	file_proto_core_v1_interaction_proto_depIdxs = nil
}
